# Import Library

In [285]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_selection import mutual_info_regression
from scipy.stats import f_oneway
import numpy as np
pd.set_option('display.max_columns', None)

# Read and clean data

In [286]:
df = pd.read_excel("05. Database RP May 2025 - AC REGISTER.xlsx", sheet_name="Raw", skiprows=1)

In [287]:
# Ganti 'df' dengan nama variabel dataframe kamu (misal df1 atau df)
print(df[['LANDING', 'HANDLING', 'AIR TRAFFIC CONTROL']].head())

     LANDING    HANDLING  AIR TRAFFIC CONTROL
0  30.289484  358.895323           154.756355
1  30.289484  358.895323           154.756355
2  30.289484  358.895323           154.756355
3  30.289484  358.895323           154.756355
4  30.289484  358.895323           154.756355

In [288]:
df

,Unnamed: 0,YEAR,PERIODE,AIRCRAFT TYPE,FLIGHT NUMBER_CITYPAIR,SERVICE TYPE,SUB-SERVICE,ROUNDTRIPROUTE,FLIGHT ROUTE,AC REG,DATE,PASSENGER REVENUE GROSS,EXCESS BAGGAGE REVENUE,PASSENGER REVENUE DISCOUNT,PASSENGER REVENUE NETT,FREIGHT REVENUE GROSS,FREIGHT REVENUE DISCOUNT,FREIGHT REVENUE NETT,MAIL REVENUE,OTHER REVENUE,NETT REVENUES,COSTS :,DIRECT COSTS :,DIRECT TRAFFIC COSTS :,PASSENGER COMMISSION,FREIGHT COMMISSION,CREDIT CARD COMMISSION,CATERING,ON BOARD SERVICE,RESERVATION,TOTAL DIRECT TRAFFIC COSTS,DIRECT FLIGHT COSTS :,FUEL AIRCRAFT,LANDING,HANDLING,AIR TRAFFIC CONTROL,COCKPIT CREW TRAVEL,CABIN CREW TRAVEL,VARIABLE MAINTENANCE,TOTAL DIRECT FLIGHT COSTS,TOTAL DIRECT COSTS,CONTRIBUTION MARGIN 1,INDIRECT COSTS :,COCKPIT CREW PERSON,CABIN CREW PERSON,AIRCRAFT MAINTENANCE,TOTAL INDIRECT COSTS,TOTAL DIRECT AND INDIRECT COSTS,CONTRIBUTION MARGIN 2,DEPRECIATION AIRCRAFT,LEASE AIRCRAFT,INSURANCE,MAINTENANCE RESERVE,TOTAL FLEET COST,"TOTAL DIRECT,INDIRECT,FLEET COSTS",CONTRIBUTION MARGIN 3,STATION,SALES ORGANIZATION,MARKETING,ADMINISTRATION BO,TOTAL OVERHEAD COST BO,TOTAL BO COSTS,ROUTE RESULT PERFORMANCE BO,ADMINISTRATION HO,TOTAL COSTS,ROUTE RESULT 1,ADJUSTMENT,ROUTE RESULT 2,FLIGHT ROUTES,NUMBER OF LANDING,BLOCK HOURS,FLIGHT HOURS,FLIGHT KILOMETERS,ATK (000),FUEL BURN (IN LITER),SEAT OFFERED,PASSENGER CARRIED,ASK (000),RPK (000),SLF (%),FREIGHT CARRIED,MAIL CARRIED,CARGO CARRIED,RTK FREIGHT (000),RTK MAIL (000),RTK CARGO (000),RTK PASSENGER (000),RTK (000),ATK CARGO (000),ATK CARGO GF (000),ATK FREIGHT GF (000),ATK MAIL GF (000),ATK PASSENGER (000),CLF (%),CLF-GF (%),LOAD FACTOR (%),BREAK EVEN LF (%),BREAK EVEN SLF-RR1 (%),NETT REVENUE/ATK (USC),NETT REVENUE/ASK (USC),PAX YIELD (USC),FREIGHT YIELD (USC),MAIL YIELD (USC),CARGO YIELD (USC),COST/ASK RR 1 (USC),COST/ASK EXCFUEL-RR1,COST PER RPK (USC),COST PER ATK (USC),COST/BLOCKHOURS,MARGIN/ASK RR 1(USC),AVERAGE FUEL PRICE,PROFIT MARGIN (%),COST COVERAGE (%),AVERAGE STAGE LENGTH,PASSENGER REVENUE GROSS F CLASS,PASSENGER REVENUE GROSS C CLASS,PASSENGER REVENUE GROSS Y CLASS,PASSENGER REVENUE DISCOUNT F CLASS,PASSENGER REVENUE DISCOUNT C CLASS,PASSENGER REVENUE DISCOUNT Y CLASS,PASSENGER REVENUE NETT F CLASS,PASSENGER REVENUE NETT C CLASS,PASSENGER REVENUE NETT Y CLASS,PASSENGER REVENUE NETT (EXCLUDE EBT) F CLASS,PASSENGER REVENUE NETT (EXCLUDE EBT) C CLASS,PASSENGER REVENUE NETT (EXCLUDE EBT) Y CLASS,SEAT OFFERED F CLASS,SEAT OFFERED C CLASS,SEAT OFFERED Y CLASS,PASSENGER CARRIED F CLASS,PASSENGER CARRIED C CLASS,PASSENGER CARRIED Y CLASS,ASK (000) F CLASS,ASK (000) C CLASS,ASK (000) Y CLASS,RPK (000) F CLASS,RPK (000) C CLASS,RPK (000) Y CLASS,OTHER REVENUE PASSENGER,OTHER REVENUE FREIGHT,QUARTER,STATUS,AIRCRAFT TYPE GROUPING,FLIGHT TYPE,GA Service,Region
0,NaN,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGNR,30012024,4097.393360,41.899458,0.706168,4138.586650,4.33,0,4.33,0.0,383.531648,4526.448297,NaN,NaN,NaN,146.331215,0.252392,13.765684,363.075018,0.990068,408.315673,932.730050,NaN,1256.095846,30.289484,358.895323,154.756355,77.115384,93.222903,239.000762,2209.376056,3142.106106,1384.342191,NaN,299.002595,46.533742,14.305586,359.841923,3501.948029,1024.500268,254.956363,661.655443,14.989873,454.143155,1385.744834,4887.692863,-361.244566,31.192382,5.614019,0.128285,18.941017,55.875704,4943.568567,-417.120270,122.408937,5065.977504,-539.529207,39.744139,-579.273346,1.0,1,0.733333,0.383333,191.0,3.638548,1747.0,162,151,30.942,28.841,93.209877,9.0,0.0,9.0,0.001719,0.0,0.001719,2.797570,2.821526,0.637419,0.553912,0.553903,0.553903,3.000871,0.269701,0.310361,77.545362,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,57.686882,4165.471873,0.0,0.000100,0.706067,0.0,57.686482,4215.173124,0.0,57.686875,4164.620068,0,12,150,0,3,148,0.0,2.292,28.650,0.0,0.573,28.268,382.164660,1.366988,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
1,NaN,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGFJ,31012024,4580.064734,46.835198,0.789354,4626.110578,47.76,0,47.76,0.0,442.261415,5116.131993,NaN,NaN,NaN,163.568976,2.783893,15.531319,363.075018,0.990068,461.509055,1007.458329,NaN,1547.291506,30.289484,358.895323,154.756355,92.312743,93.222903,315.046459,2591.814772,3599.273100,1516.858893,NaN,388.627069,46.533742,18.857364,454.018174,4053.291275,1062.840718,336.078842,872.182175,16.942681,612.105992,1837.309689,5890.600964,-774.468971,35.255974,6.345386,0.144997,21.408561,63.154919,5953.755883,-837.623890,138.355779,6092.111662,-975.979669,47.794474,-1023.774143,1.0,1,0.966667,0.516667,191.0,3.638548,2152.0,162,151,30.942,28.841,93.209877,123.0,0.0,123.0,0.023495,0.0,0.023495,2.797570,2.843474,0.637419,0.553912,0.553903,0.553903,3.000871,3.685911,4.241598,78.148585,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,759.890061,3976.008816,0.0,0.000112,0.789242,0.0,759.884803,4023.449447,0.0,759.889973,3975.195755,0,12,150,0,5,146,0.0,2.292,28.650,0.0,0.955,27.886,427.183511,15.077904,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
2,NaN,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGNA,1012024,5248.905413,53.674683,0.904626,5301.675470,151.53,0,151.53,0.0,537.404658,5990.610128,NaN,NaN,NaN,187.455447,8.832565,18.124257,365.479488,0.996625,540.392786,1121.281168,NaN,1164.782639,30.289484,358.895323,154.756355,73.858808,93.222903,222.705255,2098.510766,3219.791934,2770.818194,NaN,279.797350,46.533742,13.330205,339.661298,3559.453232,2431.156897,237.572974,616.542572,19.838619,493.633864,1367.588030,4927.041262,1063.568867,41.282124,7.429975,0.169781,25.067833,73.949714,5000.990976,989.619153,162.004329,5162.995304,827.614824,40.505273,787.109551,1.0,1,0.683333,0.416667,191.0,3.638548,1620.0,162,152,30.942,29.032,93.827160,180.0,0.0,180.0,0.034382,0.0,0.034382,2.816097,2.873122,0.637419,0.553912,0.553903,0.553903,3.000871,5.394015,6.207217,78.963427,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,259.915266,5003.755505,0.0,0.000128,0.904497,0.0,259.913467,5063.458922,0.0,259.915236,5002.732278,0,12,150,0,1,151,0.0,2.292,28.650,0.0,0.191,28.841,489.566409,47.838249,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
3,NaN,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGNR,2012024,6358.607841,65.022368,1.095878,6422.534332,4.36,0,4.36,0.0,594.445025,7021.339356,NaN,NaN,NaN,227.086522,0.254141,21.354586,382.310780,1.042522,633.371402,1265.419954,NaN,1328.715010,30.289484,358.895323,154.756355,82.543012,93.222903,266.159939,2314.582026,3580.001980,3441.337376,NaN,331.011335,46.533742,15.931221,393.476299,3973.478279,3047.861077,283.928677,736.843562,23.252002,552.869928,1596.894168,5570.372447,1450.966909,48.385022,8.708358,0.198993,29.380941,86.673315,5657.045762,1364.293594,189.878384,5846.924146,1174.415211,45.870903,1128.544307,1.0,1,0.816667,0.466667,191.0,3.638548,1848.0,162,159,30.942,30.369,98.148148,9.0,0.0,9.0,0.001719,0.0,0.001719,2.945786,2.970919,0.637419,0.553912,0.553903,0.553903,3.000871,0.269701,0.310361,81.651203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1803.219124,4552.398247,0.0,0.000156,1.095722,0.0,1803.206646,4606.716195,0.0,1803.218913,4551.467319,0,12,150,0,13,146,0.0,2.292,28.650,0.0,2.483,27.886,593.068566,1.376459,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
4,NaN,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGMW,19012024,4807.854135,49.164545,0.828612,4856.190067,97.35,0,97.35,0.0,479.163014,5432.703081,NaN,NaN,NaN,171.704075,5.674455,16.462224,360.670548,0.983512,490.065868,1045.560681,NaN,1246.748825,30.289484,358.895323,154.756355,76.029859,93.222903,233.568926,2193.511674,3239.072355,2193.630726,NaN,292.600847,46.533742,13.980459,353.115048,3592.187403,1840.515678,249.161900,646.617820,17.991044,513.379219,1427.149982,5019.337385,413.365696,37.437510,6.738020,0.153969,22.733260,67.062758,5086.400143,346.302938,146.916824,5233.316968,199.386113,41.056968,158.329146,1.0,1,0.716667,0.433333,191.0,3.638548,1734.0,162,150,30.942,28.650,92.592593,321.0,0.0,321.0,0.061315,0.0,0.061315,2.779043,2.862921,0.637419,0.553912,0.553903,0.553903,3.000871,9.619327,11.069537,78.683058,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,275.548070,4498.982388,0.0,0.000118,0.828495,0.0,275.546164,4552.662994,0.0,275.548038,4498.062384,0,12,150,0,3,147,0.0,2.292,28.650,0.0,0.573,28.077,448.429472,30.733542,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110775,NaN,2025,MAY,AC738,GA6054.KDI-UPG.[KDI-UPG],DOM,DOM_4 (UPG),UPG-KDI-UPG,KDI-UPG,PKGUF,24052025,8005.084000,-0.843000,-0.051000,8004.292000,0.00,0,0.00,0.0,460.586000,8464.878000,NaN,NaN,NaN,108.665000,0.000000,39.504297,309.880000,32.163000,819.951000,1310.163297,NaN,1888.962000,61.781000,138.074000,86.791000,96.747000,107.324000,528.304000,2907.983000,4218.146297,4246.731703,NaN,399.652000,127.997000,24.491300,552.140300,4770.286596,3694.591404,349.298927,683.495005,18.985764,678.361573,1730.141269,6500.427866,1964.450134,70.597000,9.246000,2.419000,53.399000,135.661000,6636.088866,1828.789134,303.945021,6940.033887,1524.844113,-146.615000,1671.459113,1.0,1,0.900000,0.633333,336.0,6.401000,2479.0,162,158,54.432,53.088,97.530864,0.0,0.0,0.0,0.000000,0.0,0.000000,5.150000,5.149000,1.121000,0.974400,0.974000,0.974000,5.279000,0.000000,0.000000,80.440556,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,820.777000,7184.308000,0.0,-0.004000,-0.047000,0.0,820.716000,7183.576000,0.0,820.781000,7184.355000,0,12,150,0,12,146,0.0,4.032,50.400,0.0,4.032,49.056,460.586000,0.000000,Q2,ACTUAL,B738NG,PAX & CARGO,IBT,DOM_EAST
110776,NaN,2025,MAY,AC73H,GA2084.CGK-YIA.[CGK-YIA],DOM,DOM_3 (SUB),CGK-YIA-CGK,CGK-YIA,PKGUH,28052025,6477.089000,24.671000,-0.047000,6501.807000,304.91,0,304.91,0.0,460.849000,7267.566000,NaN,NaN,NaN,262.142000,9.770000,31.963821,236.790000,29.284000,594.228000,1164.177821,NaN,2008.047000,65.141000,327.444000,98.851000,117.624000,132.126000,730.894000,3480.127000,4644.304821,2623.261179,NaN,515.661000,170.510000,32.869902,719.040902,5363.345723,1904.220277,446.326407,873.354729,24.259587,866.795343,2210.736066,7574.081789,-306.515789,93.486000,12.243000,3.203000,70.712000,179.644000,7753.725789,-486.159789,402.490394,8156.216183,-888.650183,-264.542000,-624.108183,1.0,1,1.150000,0.850000,424.0,8.077000,3544.0,170,114,72.080,48.336,67.058824,507.5,0.0,507.5,0.215000,0.0,0.215000,4.689000,4.917000,1.086000,1.229767,1.230000,1.230000,6.991000,19.797422,17.482992,60.876563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,674.619000,5802.470000,0.0,-0.003000,-0.044000,0.0,674.575000,5827.232000,0.0,674.622000,5802.514000,0,8,162,0,7,107,0.0,3.392,68.688,0.0,2.968,45.368,372.671000,88.178000,Q2,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
110777,NaN,2025,MAY,AC73H,GA2094.YIA-CGK.[YIA-CGK],DOM,DOM_3 (SUB),CGK-YIA-CGK,YIA-CGK,PKGUH,28052025,7729.572000,34.973000,-0.048000,7764.593000,810.19,0,810.19,0.0,679.035000,9253.818000,NaN,NaN,NaN,323.630000,40.320000,38.144666,243.570000,30.312000,612.621000,1288.597666,NaN,2349.846000,66.681000,379.414000,98.851000,120.408000,132.126000,659.237000,3806.563000,5095.160666,4158.657334,NaN,530.608000,170.766000,29.647363,731.021363,5826.182029,3427.635971,459.134034,898.416213,24.955732,891.668600,2274.174579,8100.356608,1153.461392,93.486000,12.243000,3.203000,70.712000,179.644000,8280.000608,973.817392,402.490394,8682.491002,571.326998,-272.210000,843.536998,1.0,1,1.183333,0.766667,424.0,8.077000,3165.0,170,118,72.080,50.032,69.411765,49.0,0.0,49.0,0.021000,0.0,0.021000,4.853000,4.891000,1.086000,1.229767,1.230000,1.230000,6.991000,1.933702,1.707641,60.554661,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1523.609000,6205.963000,0.0,-0.003000,-0.045000,0.0,1523.558000,6241.035000,0.0,1523.612000,6206.008000,0,8,162,0,8,110,0.0,3.392,68.688,0.0,3.392,46.640,444.734000,234.301000,Q2,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
110778,NaN,2025,MAY,AC73H,GA4324.CGK-AMI.[CGK-AMI],DOM,DOM_2 (JKT),CGK-AMI-CGK,CGK-AMI,PKGUI,29052025,15713.245000,41.607000,-0.182000,15755.034000,1373.88,0,1373.88,0.0,1301.409000,18430.323000,NaN,NaN,NaN,573.266000,38.080000,77.543712,449.540000,114.064000,904.834000,2157.327712,NaN,3729.392000,50.381000,327.444000,188.221000,188.606000,293.876000,1418.793000,6196.713000,8354.040712,10076.282288,NaN,896.802000,435.184000,63.806281,1395.792281,9749.832993,8680.490007,776.219838,1518.877790,42.190587,1507.470161,3844.758376,13594.591369,4835.731631,242.756000,31.792000,8.317000,183.617000,466.482000,14061.073369,4369.249631,1045.146047,15106.219416,3324.103584,-460.072000,3784.175584,1.0,1,2.000000,1.650000,1101.0,20.974000,6582.0,170,171,187.170,188.271,100.588235,3376.5,0.0,3376.5,3.718000,0.0,3.718000,18.262000,22.015000,2.820000,3.637177,3.193000,3.193000,18.152000,131.843972,102.222141,104.963288,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1499.764000,14213.481000,0.0,-0.007000,-0.175000,0.0,1499.649000,14255.385000,0.0,1499.771000,14213.656000,0,8,162,0,7,164,0.0,8.808,178.362,0.0,7.707,180.564,904.093000,397.316000,Q2,ACTUAL,B738NG,PAX & CARGO,IBT,DOM_EAST
110779,NaN,2025,MAY,AC73H,GA4344.AMI-CGK.[AMI-CGK],DOM,DOM_2 (JKT),CGK-AMI-CGK,AMI-CGK,PKGUI,29052025,8425.103000,33.184000,6.667000,8451.620000,902.05,0,902.05,0.0,745.232000,10098.902000,NaN,NaN,NaN,319.813000,33.960000,41.543883,296.990000,60.701000,482.521000,1235.528883,NaN,4391.674000,66.681000,379.414000,188.221000,206.700000,293.876000,1605.100000,7131.666000,8367.194883,1731.707117,NaN,993.956000,436.849000,72.184883,1502.989883,9870.184766,228.717234,860.439691,1683.676030,46.768266,1671.030674,4261.914660,14132.099426,-4033.197426,242.756000,31.792000,8.317000,183.617000,466.482000,14598.581426,-4499.679426,1045.146047,15643.727473,-5544.825473,-509.914000,-5034.911473,1.0,1,2.216667,1.866667,1101.0,20.974000,6075.0,170,91,187.170,100.191,53.529412,1991.0,0.0,1991.0,2.192000,0.0,2.192000,9.719000,11.942000,2.820000,3.216021,3.193000,3.193000,18.152000,77.730496,68.158759,56.937160,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1657.367000,6767.736000,0.0,-0.005000,6.672000,0.0,1657.285000,6794.335000,0.0,1657.372000,6761.064000,0,8,162,0,5,86,0.0,8.808,178.362,0.0,5.505,94.686,484.366000,260.866000,Q2,ACTUAL,B738NG,PAX & CARGO,IBT,DOM_EAST

In [289]:
df = df.iloc[:, 1:]

In [290]:
print([df])

[        YEAR PERIODE AIRCRAFT TYPE    FLIGHT NUMBER_CITYPAIR SERVICE TYPE  \
0       2024     JAN         AC738  GA0072.CGK-TKG.[CGK-TKG]          DOM
1       2024     JAN         AC738  GA0072.CGK-TKG.[CGK-TKG]          DOM
2       2024     JAN         AC738  GA0072.CGK-TKG.[CGK-TKG]          DOM
3       2024     JAN         AC738  GA0072.CGK-TKG.[CGK-TKG]          DOM
4       2024     JAN         AC738  GA0072.CGK-TKG.[CGK-TKG]          DOM
...      ...     ...           ...                       ...          ...
110775  2025     MAY         AC738  GA6054.KDI-UPG.[KDI-UPG]          DOM
110776  2025     MAY         AC73H  GA2084.CGK-YIA.[CGK-YIA]          DOM
110777  2025     MAY         AC73H  GA2094.YIA-CGK.[YIA-CGK]          DOM
110778  2025     MAY         AC73H  GA4324.CGK-AMI.[CGK-AMI]          DOM
110779  2025     MAY         AC73H  GA4344.AMI-CGK.[AMI-CGK]          DOM

        SUB-SERVICE ROUNDTRIPROUTE FLIGHT ROUTE AC REG      DATE  \
0       DOM_2 (JKT)    CGK-TKG-CGK      CGK-TKG  PKGNR  30012024
1       DOM_2 (JKT)    CGK-TKG-CGK      CGK-TKG  PKGFJ  31012024
2       DOM_2 (JKT)    CGK-TKG-CGK      CGK-TKG  PKGNA   1012024
3       DOM_2 (JKT)    CGK-TKG-CGK      CGK-TKG  PKGNR   2012024
4       DOM_2 (JKT)    CGK-TKG-CGK      CGK-TKG  PKGMW  19012024
...             ...            ...          ...    ...       ...
110775  DOM_4 (UPG)    UPG-KDI-UPG      KDI-UPG  PKGUF  24052025
110776  DOM_3 (SUB)    CGK-YIA-CGK      CGK-YIA  PKGUH  28052025
110777  DOM_3 (SUB)    CGK-YIA-CGK      YIA-CGK  PKGUH  28052025
110778  DOM_2 (JKT)    CGK-AMI-CGK      CGK-AMI  PKGUI  29052025
110779  DOM_2 (JKT)    CGK-AMI-CGK      AMI-CGK  PKGUI  29052025

        PASSENGER REVENUE GROSS  EXCESS BAGGAGE REVENUE  \
0                   4097.393360               41.899458
1                   4580.064734               46.835198
2                   5248.905413               53.674683
3                   6358.607841               65.022368
4                   4807.854135               49.164545
...                         ...                     ...
110775              8005.084000               -0.843000
110776              6477.089000               24.671000
110777              7729.572000               34.973000
110778             15713.245000               41.607000
110779              8425.103000               33.184000

        PASSENGER REVENUE DISCOUNT  PASSENGER REVENUE NETT  \
0                         0.706168             4138.586650
1                         0.789354             4626.110578
2                         0.904626             5301.675470
3                         1.095878             6422.534332
4                         0.828612             4856.190067
...                            ...                     ...
110775                   -0.051000             8004.292000
110776                   -0.047000             6501.807000
110777                   -0.048000             7764.593000
110778                   -0.182000            15755.034000
110779                    6.667000             8451.620000

        FREIGHT REVENUE GROSS  FREIGHT REVENUE DISCOUNT  FREIGHT REVENUE NETT  \
0                        4.33                         0                  4.33
1                       47.76                         0                 47.76
2                      151.53                         0                151.53
3                        4.36                         0                  4.36
4                       97.35                         0                 97.35
...                       ...                       ...                   ...
110775                   0.00                         0                  0.00
110776                 304.91                         0                304.91
110777                 810.19                         0                810.19
110778                1373.88                         0               1373.88
110779                 902.05                         0                902.05

        MAIL REVENUE  OTHER REVENUE  NETT REVENUES  COSTS :  DIRECT COSTS :  \
0                0.0     383.531648    4526.448297      NaN             NaN
1                0.0     442.261415    5116.131993      NaN             NaN
2                0.0     537.404658    5990.610128      NaN             NaN
3                0.0     594.445025    7021.339356      NaN             NaN
4                0.0     479.163014    5432.703081      NaN             NaN
...              ...            ...            ...      ...             ...
110775           0.0     460.586000    8464.878000      NaN             NaN
110776           0.0     460.849000    7267.566000      NaN             NaN
110777           0.0     679.035000    9253.818000      NaN             NaN
110778           0.0    1301.409000   18430.323000      NaN             NaN
110779           0.0     745.232000   10098.902000      NaN             NaN

        DIRECT TRAFFIC COSTS :  PASSENGER COMMISSION  FREIGHT COMMISSION  \
0                          NaN            146.331215            0.252392
1                          NaN            163.568976            2.783893
2                          NaN            187.455447            8.832565
3                          NaN            227.086522            0.254141
4                          NaN            171.704075            5.674455
...                        ...                   ...                 ...
110775                     NaN            108.665000            0.000000
110776                     NaN            262.142000            9.770000
110777                     NaN            323.630000           40.320000
110778                     NaN            573.266000           38.080000
110779                     NaN            319.813000           33.960000

        CREDIT CARD COMMISSION    CATERING  ON BOARD SERVICE  RESERVATION  \
0                    13.765684  363.075018          0.990068   408.315673
1                    15.531319  363.075018          0.990068   461.509055
2                    18.124257  365.479488          0.996625   540.392786
3                    21.354586  382.310780          1.042522   633.371402
4                    16.462224  360.670548          0.983512   490.065868
...                        ...         ...               ...          ...
110775               39.504297  309.880000         32.163000   819.951000
110776               31.963821  236.790000         29.284000   594.228000
110777               38.144666  243.570000         30.312000   612.621000
110778               77.543712  449.540000        114.064000   904.834000
110779               41.543883  296.990000         60.701000   482.521000

        TOTAL DIRECT TRAFFIC COSTS  DIRECT FLIGHT COSTS :  FUEL AIRCRAFT  \
0                       932.730050                    NaN    1256.095846
1                      1007.458329                    NaN    1547.291506
2                      1121.281168                    NaN    1164.782639
3                      1265.419954                    NaN    1328.715010
4                      1045.560681                    NaN    1246.748825
...                            ...                    ...            ...
110775                 1310.163297                    NaN    1888.962000
110776                 1164.177821                    NaN    2008.047000
110777                 1288.597666                    NaN    2349.846000
110778                 2157.327712                    NaN    3729.392000
110779                 1235.528883                    NaN    4391.674000

          LANDING    HANDLING  AIR TRAFFIC CONTROL  COCKPIT CREW TRAVEL  \
0       30.289484  358.895323           154.756355            77.115384
1       30.289484  358.895323           154.756355            92.312743
2       30.289484  358.895323           154.756355            73.858808
3       30.289484  358.895323           154.756355            82.543012
4       30.289484  358.895323           154.756355            76.029859
...           ...         ...                  ...                  ...
110775  61.781000  138.074000            86.791000            96.747000
110776  65.141000  327.444000            98.851000           117.624000
110777  66.681000  379.414000            98.851000           120.408000
110778  50.381000  327.444000           188.221000           188.606000
110779  66.681000  379.414000           188.221000           206.700000

        CABIN CREW TRAVEL  VARIABLE MAINTENANCE  TOTAL DIRECT FLIGHT COSTS  \
0               93.222903            239.000762                2209.376056
1               93.222903            315.046459                2591.814772
2               93.222903            222.705255                2098.510766
3               93.222903            266.159939                2314.582026
4               93.222903            233.568926                2193.511674
...                   ...                   ...                        ...
110775         107.324000            528.304000                2907.983000
110776         132.126000            730.894000                3480.127000
110777         132.126000            659.237000                3806.563000
110778         293.876000           1418.793000                6196.713000
110779         293.876000           1605.100000                7131.666000

        TOTAL DIRECT COSTS  CONTRIBUTION MARGIN 1  INDIRECT COSTS :  \
0              3142.106106            1384.342191               NaN
1              3599.273100            1516.858893               NaN
2              3219.791934            2770.818194               NaN
3              3580.001980            3441.337376               NaN
4              3239.072355            2193.630726               NaN
...                    ...                    ...               ...
110775         4218.146297            4246.731703               NaN
110776         4644.304821            2623.261179               NaN
110777         5095.160666            4158.657334               NaN
110778         8354.040712           10076.282288               NaN
110779         8367.194883            1731.707117               NaN

        COCKPIT CREW PERSON  CABIN CREW PERSON  AIRCRAFT MAINTENANCE  \
0                299.002595          46.533742             14.305586
1                388.627069          46.533742             18.857364
2                279.797350          46.533742             13.330205
3                331.011335          46.533742             15.931221
4                292.600847          46.533742             13.980459
...                     ...                ...                   ...
110775           399.652000         127.997000             24.491300
110776           515.661000         170.510000             32.869902
110777           530.608000         170.766000             29.647363
110778           896.802000         435.184000             63.806281
110779           993.956000         436.849000             72.184883

        TOTAL INDIRECT COSTS  TOTAL DIRECT AND INDIRECT COSTS  \
0                 359.841923                      3501.948029
1                 454.018174                      4053.291275
2                 339.661298                      3559.453232
3                 393.476299                      3973.478279
4                 353.115048                      3592.187403
...                      ...                              ...
110775            552.140300                      4770.286596
110776            719.040902                      5363.345723
110777            731.021363                      5826.182029
110778           1395.792281                      9749.832993
110779           1502.989883                      9870.184766

        CONTRIBUTION MARGIN 2  DEPRECIATION AIRCRAFT  LEASE AIRCRAFT  \
0                 1024.500268             254.956363      661.655443
1                 1062.840718             336.078842      872.182175
2                 2431.156897             237.572974      616.542572
3                 3047.861077             283.928677      736.843562
4                 1840.515678             249.161900      646.617820
...                       ...                    ...             ...
110775            3694.591404             349.298927      683.495005
110776            1904.220277             446.326407      873.354729
110777            3427.635971             459.134034      898.416213
110778            8680.490007             776.219838     1518.877790
110779             228.717234             860.439691     1683.676030

        INSURANCE  MAINTENANCE RESERVE  TOTAL FLEET COST  \
0       14.989873           454.143155       1385.744834
1       16.942681           612.105992       1837.309689
2       19.838619           493.633864       1367.588030
3       23.252002           552.869928       1596.894168
4       17.991044           513.379219       1427.149982
...           ...                  ...               ...
110775  18.985764           678.361573       1730.141269
110776  24.259587           866.795343       2210.736066
110777  24.955732           891.668600       2274.174579
110778  42.190587          1507.470161       3844.758376
110779  46.768266          1671.030674       4261.914660

        TOTAL DIRECT,INDIRECT,FLEET COSTS  CONTRIBUTION MARGIN 3     STATION  \
0                             4887.692863            -361.244566   31.192382
1                             5890.600964            -774.468971   35.255974
2                             4927.041262            1063.568867   41.282124
3                             5570.372447            1450.966909   48.385022
4                             5019.337385             413.365696   37.437510
...                                   ...                    ...         ...
110775                        6500.427866            1964.450134   70.597000
110776                        7574.081789            -306.515789   93.486000
110777                        8100.356608            1153.461392   93.486000
110778                       13594.591369            4835.731631  242.756000
110779                       14132.099426           -4033.197426  242.756000

        SALES ORGANIZATION  MARKETING  ADMINISTRATION BO  \
0                 5.614019   0.128285          18.941017
1                 6.345386   0.144997          21.408561
2                 7.429975   0.169781          25.067833
3                 8.708358   0.198993          29.380941
4                 6.738020   0.153969          22.733260
...                    ...        ...                ...
110775            9.246000   2.419000          53.399000
110776           12.243000   3.203000          70.712000
110777           12.243000   3.203000          70.712000
110778           31.792000   8.317000         183.617000
110779           31.792000   8.317000         183.617000

        TOTAL OVERHEAD COST BO  TOTAL BO COSTS  ROUTE RESULT PERFORMANCE BO  \
0                    55.875704     4943.568567                  -417.120270
1                    63.154919     5953.755883                  -837.623890
2                    73.949714     5000.990976                   989.619153
3                    86.673315     5657.045762                  1364.293594
4                    67.062758     5086.400143                   346.302938
...                        ...             ...                          ...
110775              135.661000     6636.088866                  1828.789134
110776              179.644000     7753.725789                  -486.159789
110777              179.644000     8280.000608                   973.817392
110778              466.482000    14061.073369                  4369.249631
110779              466.482000    14598.581426                 -4499.679426

        ADMINISTRATION HO   TOTAL COSTS  ROUTE RESULT 1  ADJUSTMENT  \
0              122.408937   5065.977504     -539.529207   39.744139
1              138.355779   6092.111662     -975.979669   47.794474
2              162.004329   5162.995304      827.614824   40.505273
3              189.878384   5846.924146     1174.415211   45.870903
4              146.916824   5233.316968      199.386113   41.056968
...                   ...           ...             ...         ...
110775         303.945021   6940.033887     1524.844113 -146.615000
110776         402.490394   8156.216183     -888.650183 -264.542000
110777         402.490394   8682.491002      571.326998 -272.210000
110778        1045.146047  15106.219416     3324.103584 -460.072000
110779        1045.146047  15643.727473    -5544.825473 -509.914000

        ROUTE RESULT 2  FLIGHT ROUTES  NUMBER OF LANDING  BLOCK HOURS  \
0          -579.273346            1.0                  1     0.733333
1         -1023.774143            1.0                  1     0.966667
2           787.109551            1.0                  1     0.683333
3          1128.544307            1.0                  1     0.816667
4           158.329146            1.0                  1     0.716667
...                ...            ...                ...          ...
110775     1671.459113            1.0                  1     0.900000
110776     -624.108183            1.0                  1     1.150000
110777      843.536998            1.0                  1     1.183333
110778     3784.175584            1.0                  1     2.000000
110779    -5034.911473            1.0                  1     2.216667

        FLIGHT HOURS  FLIGHT KILOMETERS  ATK (000)  FUEL BURN (IN LITER)  \
0           0.383333              191.0   3.638548                1747.0
1           0.516667              191.0   3.638548                2152.0
2           0.416667              191.0   3.638548                1620.0
3           0.466667              191.0   3.638548                1848.0
4           0.433333              191.0   3.638548                1734.0
...              ...                ...        ...                   ...
110775      0.633333              336.0   6.401000                2479.0
110776      0.850000              424.0   8.077000                3544.0
110777      0.766667              424.0   8.077000                3165.0
110778      1.650000             1101.0  20.974000                6582.0
110779      1.866667             1101.0  20.974000                6075.0

        SEAT OFFERED  PASSENGER CARRIED  ASK (000)  RPK (000)     SLF (%)  \
0                162                151     30.942     28.841   93.209877
1                162                151     30.942     28.841   93.209877
2                162                152     30.942     29.032   93.827160
3                162                159     30.942     30.369   98.148148
4                162                150     30.942     28.650   92.592593
...              ...                ...        ...        ...         ...
110775           162                158     54.432     53.088   97.530864
110776           170                114     72.080     48.336   67.058824
110777           170                118     72.080     50.032   69.411765
110778           170                171    187.170    188.271  100.588235
110779           170                 91    187.170    100.191   53.529412

        FREIGHT CARRIED  MAIL CARRIED  CARGO CARRIED  RTK FREIGHT (000)  \
0                   9.0           0.0            9.0           0.001719
1                 123.0           0.0          123.0           0.023495
2                 180.0           0.0          180.0           0.034382
3                   9.0           0.0            9.0           0.001719
4                 321.0           0.0          321.0           0.061315
...                 ...           ...            ...                ...
110775              0.0           0.0            0.0           0.000000
110776            507.5           0.0          507.5           0.215000
110777             49.0           0.0           49.0           0.021000

In [ ]:
df1 = df[
    (df['BLOCK HOURS'] > 0) & 
    (df['ASK (000)'] > 0) &
    (df['LANDING'] > 0) &
    (df['HANDLING'] > 0) &
    (df['AIR TRAFFIC CONTROL'] > 0)
].copy()

# Corr

## Num Corr

### LANDING

In [292]:
df_num = df.select_dtypes(include=["number"])

corr = df_num.corrwith(df_num['LANDING']).sort_values(ascending=False).dropna()

print(corr.head(60))

LANDING                                         1.000000
TOTAL DIRECT FLIGHT COSTS                       0.843416
TOTAL DIRECT COSTS                              0.841866
TOTAL DIRECT AND INDIRECT COSTS                 0.840289
TOTAL DIRECT,INDIRECT,FLEET COSTS               0.833005
TOTAL BO COSTS                                  0.833004
TOTAL COSTS                                     0.829786
ASK (000) C CLASS                               0.826459
CABIN CREW TRAVEL                               0.822218
FUEL BURN (IN LITER)                            0.819790
ATK (000)                                       0.819552
FUEL AIRCRAFT                                   0.815488
ATK PASSENGER (000)                             0.806120
ASK (000)                                       0.804341
LEASE AIRCRAFT                                  0.799613
ASK (000) Y CLASS                               0.795705
CABIN CREW PERSON                               0.792786
TOTAL INDIRECT COSTS                            0.789951
TOTAL FLEET COST                                0.785807
COCKPIT CREW TRAVEL                             0.778726
COCKPIT CREW PERSON                             0.774433
FLIGHT KILOMETERS                               0.772233
FLIGHT HOURS                                    0.770008
BLOCK HOURS                                     0.769269
RTK (000)                                       0.768028
RPK (000) C CLASS                               0.758891
MAINTENANCE RESERVE                             0.751886
RTK PASSENGER (000)                             0.746956
RPK (000)                                       0.744814
INSURANCE                                       0.732300
HANDLING                                        0.732266
RPK (000) Y CLASS                               0.732052
ADMINISTRATION HO                               0.725834
NETT REVENUES                                   0.716344
TOTAL DIRECT TRAFFIC COSTS                      0.709679
SEAT OFFERED                                    0.706289
SEAT OFFERED C CLASS                            0.705465
PASSENGER REVENUE NETT                          0.705055
PASSENGER REVENUE GROSS                         0.704939
VARIABLE MAINTENANCE                            0.689778
SEAT OFFERED Y CLASS                            0.685456
AIR TRAFFIC CONTROL                             0.682647
PASSENGER REVENUE NETT (EXCLUDE EBT) C CLASS    0.679644
PASSENGER REVENUE GROSS C CLASS                 0.679595
OTHER REVENUE PASSENGER                         0.676267
PASSENGER REVENUE NETT Y CLASS                  0.668330
PASSENGER REVENUE NETT C CLASS                  0.667227
PASSENGER REVENUE NETT (EXCLUDE EBT) Y CLASS    0.665728
PASSENGER REVENUE GROSS Y CLASS                 0.665659
CATERING                                        0.625374
OTHER REVENUE                                   0.603330
PASSENGER COMMISSION                            0.601498
PASSENGER CARRIED C CLASS                       0.591475
STATION                                         0.590949
MARKETING                                       0.587931
TOTAL OVERHEAD COST BO                          0.584409
AIRCRAFT MAINTENANCE                            0.553287
CREDIT CARD COMMISSION                          0.549683
ATK CARGO (000)                                 0.548927
RTK FREIGHT (000)                               0.533264
dtype: float64

c:\Oscar\GDI\ML GI\.venv\Lib\site-packages\numpy\lib\_function_base_impl.py:3045: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
c:\Oscar\GDI\ML GI\.venv\Lib\site-packages\numpy\lib\_function_base_impl.py:3046: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

### HANDLING

In [293]:
df_num = df.select_dtypes(include=["number"])

corr = df_num.corrwith(df_num['HANDLING']).sort_values(ascending=False).dropna()

print(corr.head(50))

c:\Oscar\GDI\ML GI\.venv\Lib\site-packages\numpy\lib\_function_base_impl.py:3045: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
c:\Oscar\GDI\ML GI\.venv\Lib\site-packages\numpy\lib\_function_base_impl.py:3046: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

HANDLING                                        1.000000
LANDING                                         0.732266
TOTAL DIRECT COSTS                              0.729117
TOTAL DIRECT AND INDIRECT COSTS                 0.727172
TOTAL DIRECT FLIGHT COSTS                       0.722809
TOTAL BO COSTS                                  0.715057
TOTAL DIRECT,INDIRECT,FLEET COSTS               0.714944
TOTAL COSTS                                     0.709631
ASK (000) C CLASS                               0.707095
COCKPIT CREW PERSON                             0.689632
BLOCK HOURS                                     0.686510
FUEL BURN (IN LITER)                            0.683605
CABIN CREW TRAVEL                               0.681485
FLIGHT HOURS                                    0.680105
LEASE AIRCRAFT                                  0.679383
TOTAL INDIRECT COSTS                            0.677698
FUEL AIRCRAFT                                   0.672462
COCKPIT CREW TRAVEL                             0.670379
SEAT OFFERED C CLASS                            0.669681
TOTAL DIRECT TRAFFIC COSTS                      0.668157
ATK (000)                                       0.667801
FLIGHT KILOMETERS                               0.665015
ATK PASSENGER (000)                             0.663103
ASK (000)                                       0.661278
ASK (000) Y CLASS                               0.652467
TOTAL FLEET COST                                0.652284
CABIN CREW PERSON                               0.643155
RPK (000) C CLASS                               0.643028
SEAT OFFERED                                    0.629336
RTK (000)                                       0.626704
INSURANCE                                       0.625488
CATERING                                        0.622467
VARIABLE MAINTENANCE                            0.611552
SEAT OFFERED Y CLASS                            0.606665
RTK PASSENGER (000)                             0.599436
ADMINISTRATION HO                               0.599138
PASSENGER REVENUE NETT (EXCLUDE EBT) C CLASS    0.597404
PASSENGER REVENUE GROSS C CLASS                 0.597355
RPK (000)                                       0.597255
NETT REVENUES                                   0.591731
PASSENGER REVENUE NETT C CLASS                  0.589719
MAINTENANCE RESERVE                             0.585243
RPK (000) Y CLASS                               0.584034
PASSENGER REVENUE NETT                          0.580501
PASSENGER REVENUE GROSS                         0.579856
PASSENGER COMMISSION                            0.578936
PASSENGER CARRIED C CLASS                       0.557756
AIR TRAFFIC CONTROL                             0.557409
PASSENGER REVENUE NETT Y CLASS                  0.542197
PASSENGER REVENUE NETT (EXCLUDE EBT) Y CLASS    0.539889
dtype: float64

In [294]:
corr.to_csv("correlation.csv")

### AIR TRAFFIC CONTROL

In [337]:
df_num = df.select_dtypes(include=["number"])

corr = df_num.corrwith(df_num['AIR TRAFFIC CONTROL']).sort_values(ascending=False).dropna()

print(corr.head(50))

AIR TRAFFIC CONTROL                             1.000000
CABIN CREW PERSON                               0.838056
TOTAL INDIRECT COSTS                            0.834713
LEASE AIRCRAFT                                  0.834246
TOTAL FLEET COST                                0.832443
TOTAL DIRECT,INDIRECT,FLEET COSTS               0.829669
TOTAL DIRECT FLIGHT COSTS                       0.828713
TOTAL BO COSTS                                  0.827855
TOTAL COSTS                                     0.824963
TOTAL DIRECT AND INDIRECT COSTS                 0.823491
ATK (000)                                       0.821873
COCKPIT CREW PERSON                             0.820498
FUEL AIRCRAFT                                   0.819637
FUEL BURN (IN LITER)                            0.819141
TOTAL DIRECT COSTS                              0.819099
MAINTENANCE RESERVE                             0.813695
ATK PASSENGER (000)                             0.813386
ASK (000)                                       0.813312
CABIN CREW TRAVEL                               0.811941
ASK (000) Y CLASS                               0.807405
ASK (000) C CLASS                               0.801466
FLIGHT KILOMETERS                               0.793545
FLIGHT HOURS                                    0.783813
BLOCK HOURS                                     0.783321
COCKPIT CREW TRAVEL                             0.775213
RTK (000)                                       0.760913
RTK PASSENGER (000)                             0.754567
RPK (000)                                       0.754117
RPK (000) Y CLASS                               0.747133
ADMINISTRATION HO                               0.724101
INSURANCE                                       0.719012
RPK (000) C CLASS                               0.704671
NETT REVENUES                                   0.687619
LANDING                                         0.682647
VARIABLE MAINTENANCE                            0.681073
PASSENGER REVENUE NETT                          0.677260
PASSENGER REVENUE GROSS                         0.676875
PASSENGER REVENUE NETT Y CLASS                  0.652689
PASSENGER REVENUE NETT (EXCLUDE EBT) Y CLASS    0.652584
PASSENGER REVENUE GROSS Y CLASS                 0.652554
SEAT OFFERED                                    0.636766
TOTAL DIRECT TRAFFIC COSTS                      0.633774
OTHER REVENUE PASSENGER                         0.633046
SEAT OFFERED Y CLASS                            0.625489
ON BOARD SERVICE                                0.595915
PASSENGER REVENUE NETT (EXCLUDE EBT) C CLASS    0.591348
OTHER REVENUE                                   0.591318
PASSENGER REVENUE GROSS C CLASS                 0.591311
PASSENGER REVENUE NETT C CLASS                  0.589888
SEAT OFFERED C CLASS                            0.574371
dtype: float64

c:\Oscar\GDI\ML GI\.venv\Lib\site-packages\numpy\lib\_function_base_impl.py:3045: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
c:\Oscar\GDI\ML GI\.venv\Lib\site-packages\numpy\lib\_function_base_impl.py:3046: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

In [338]:

corr.to_csv("correlation_atc.csv")

## Cat Corr

In [296]:
def anova_eta_squared(df, cat_col, target_col):
    groups = [
        df[df[cat_col] == cat][target_col].dropna()
        for cat in df[cat_col].dropna().unique()
    ]

    # minimal 2 grup
    if len(groups) < 2:
        return np.nan

    f_stat, p_val = f_oneway(*groups)

    overall_mean = df[target_col].mean()

    ss_between = sum(
        len(g) * (g.mean() - overall_mean) ** 2 for g in groups
    )
    ss_total = sum(
        (df[target_col] - overall_mean) ** 2
    )

    eta_sq = ss_between / ss_total if ss_total != 0 else np.nan

    return eta_sq

In [297]:
df_cat = df.select_dtypes(include=["object"])
categorical_cols  = ['AIRCRAFT TYPE', 
                     'SERVICE TYPE', 
                     'SUB-SERVICE',
                     'ROUNDTRIPROUTE', 
                     'FLIGHT ROUTE', 
                     'AC REG',
                     'QUARTER',
                     'STATUS',
                     'AIRCRAFT TYPE GROUPING',
                     'FLIGHT TYPE',
                     'GA Service', 
                     'Region']
df_cat

,PERIODE,AIRCRAFT TYPE,FLIGHT NUMBER_CITYPAIR,SERVICE TYPE,SUB-SERVICE,ROUNDTRIPROUTE,FLIGHT ROUTE,AC REG,QUARTER,STATUS,AIRCRAFT TYPE GROUPING,FLIGHT TYPE,GA Service,Region
0,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGNR,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
1,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGFJ,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
2,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGNA,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
3,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGNR,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
4,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGMW,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110775,MAY,AC738,GA6054.KDI-UPG.[KDI-UPG],DOM,DOM_4 (UPG),UPG-KDI-UPG,KDI-UPG,PKGUF,Q2,ACTUAL,B738NG,PAX & CARGO,IBT,DOM_EAST
110776,MAY,AC73H,GA2084.CGK-YIA.[CGK-YIA],DOM,DOM_3 (SUB),CGK-YIA-CGK,CGK-YIA,PKGUH,Q2,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
110777,MAY,AC73H,GA2094.YIA-CGK.[YIA-CGK],DOM,DOM_3 (SUB),CGK-YIA-CGK,YIA-CGK,PKGUH,Q2,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
110778,MAY,AC73H,GA4324.CGK-AMI.[CGK-AMI],DOM,DOM_2 (JKT),CGK-AMI-CGK,CGK-AMI,PKGUI,Q2,ACTUAL,B738NG,PAX & CARGO,IBT,DOM_EAST
110779,MAY,AC73H,GA4344.AMI-CGK.[AMI-CGK],DOM,DOM_2 (JKT),CGK-AMI-CGK,AMI-CGK,PKGUI,Q2,ACTUAL,B738NG,PAX & CARGO,IBT,DOM_EAST

### LANDING

In [298]:
anova_results = []

for col in categorical_cols:
    eta = anova_eta_squared(df, col, "LANDING")
    anova_results.append({
        "feature": col,
        "eta_squared": eta
    })

anova_df = pd.DataFrame(anova_results).sort_values(
    "eta_squared", ascending=False
)

anova_df

                   feature  eta_squared
4             FLIGHT ROUTE     0.924902
3           ROUNDTRIPROUTE     0.869027
2              SUB-SERVICE     0.824754
10              GA Service     0.824719
11                  Region     0.719191
1             SERVICE TYPE     0.675900
5                   AC REG     0.635556
0            AIRCRAFT TYPE     0.632864
8   AIRCRAFT TYPE GROUPING     0.627319
6                  QUARTER     0.000327
7                   STATUS          NaN
9              FLIGHT TYPE          NaN

### HANDLING

In [299]:
anova_results = []

for col in categorical_cols:
    eta = anova_eta_squared(df, col, "HANDLING")
    anova_results.append({
        "feature": col,
        "eta_squared": eta
    })

anova_df = pd.DataFrame(anova_results).sort_values(
    "eta_squared", ascending=False
)

anova_df

                   feature  eta_squared
4             FLIGHT ROUTE     0.957647
3           ROUNDTRIPROUTE     0.751808
2              SUB-SERVICE     0.729299
10              GA Service     0.728878
11                  Region     0.645983
1             SERVICE TYPE     0.645716
5                   AC REG     0.533235
0            AIRCRAFT TYPE     0.530681
8   AIRCRAFT TYPE GROUPING     0.525810
6                  QUARTER     0.001016
7                   STATUS          NaN
9              FLIGHT TYPE          NaN

### AIR TRAFFIC CONTROL

In [300]:
anova_results = []

for col in categorical_cols:
    eta = anova_eta_squared(df, col, "AIR TRAFFIC CONTROL")
    anova_results.append({
        "feature": col,
        "eta_squared": eta
    })

anova_df = pd.DataFrame(anova_results).sort_values(
    "eta_squared", ascending=False
)

anova_df

                   feature  eta_squared
4             FLIGHT ROUTE     0.748179
3           ROUNDTRIPROUTE     0.722753
2              SUB-SERVICE     0.646527
10              GA Service     0.646376
5                   AC REG     0.469666
0            AIRCRAFT TYPE     0.457969
8   AIRCRAFT TYPE GROUPING     0.456625
11                  Region     0.397909
1             SERVICE TYPE     0.298846
6                  QUARTER     0.003318
7                   STATUS          NaN
9              FLIGHT TYPE          NaN

# Model

## LANDING

### FITUR

In [307]:
fitur_num = [ 
    'ASK (000) C CLASS',
    'ASK (000) Y CLASS',
    'SEAT OFFERED C CLASS',
    'ATK PASSENGER (000)',
    'ASK (000)',            
    'ATK (000)', 
    'SEAT OFFERED',
    'BLOCK HOURS',          
    'FLIGHT KILOMETERS',       
]

fitur_cat = [
    'GA Service',
    'AIRCRAFT TYPE GROUPING',
    'Region',
    'SUB-SERVICE',       
    'SERVICE TYPE',         
    'ROUNDTRIPROUTE', 
    'FLIGHT ROUTE', 
    'AC REG',
    'AIRCRAFT TYPE', 
]

fitur = fitur_num + fitur_cat

In [308]:
# fitur_num = [
#     'FLIGHT KILOMETERS',    
#     'ATK (000)', 
#     'SEAT OFFERED',
#     'ATK PASSENGER (000)',    
# ]

# fitur_cat = [
#     'AIRCRAFT TYPE',        
#     'FLIGHT ROUTE', 
# ]

# fitur = fitur_num + fitur_cat

### TRAIN-TEST MODEL

In [309]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import mean_absolute_percentage_error, mean_absolute_error, r2_score
from xgboost import XGBRegressor

In [310]:
def train_model(target_name, df_data,fitur,fitur_cat):
    print(f"--- TRAINING MODEL FOR: {target_name} ---")
    
    data = df_data[df_data[target_name] > 0].copy()
    
    X = data[fitur]
    y = data[target_name]
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    categorical_cols = fitur_cat
    numeric_cols = list(set(fitur) - set(categorical_cols))
    
    encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
    encoder.fit(X_train[categorical_cols])
    
    X_train_enc = encoder.transform(X_train[categorical_cols])
    X_test_enc = encoder.transform(X_test[categorical_cols])
    enc_cols = encoder.get_feature_names_out(categorical_cols)
    
    X_train_final = pd.concat([
        X_train[numeric_cols].reset_index(drop=True),
        pd.DataFrame(X_train_enc, columns=enc_cols)
    ], axis=1)
    
    X_test_final = pd.concat([
        X_test[numeric_cols].reset_index(drop=True),
        pd.DataFrame(X_test_enc, columns=enc_cols)
    ], axis=1)
    
    model = XGBRegressor(
        n_estimators=500,
        max_depth=6,
        learning_rate=0.05,
        n_jobs=-1,
        objective="reg:absoluteerror" 
    )
    
    model.fit(X_train_final, y_train)
    y_pred = model.predict(X_test_final)
    
    # Evaluasi
    mape = mean_absolute_percentage_error(y_test, y_pred)

    print(f"MAPE: {mape:.4f} ({mape*100:.2f}%)")
    
    return model, encoder, X_test_final, y_test, y_pred

In [311]:
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_percentage_error
import pandas as pd
from tqdm import tqdm

def backward_feature_elimination(target_name, df_data, fitur, fitur_cat, tol=0.005, n_estimators=500):
    """
    Backward Feature Elimination untuk XGBoost dengan progress bar
    """
    # --- Data split ---
    data = df_data[df_data[target_name] > 0].copy()
    X = data[fitur]
    y = data[target_name]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    # --- Encode categorical ---
    if fitur_cat:
        categorical_cols = fitur_cat
        numeric_cols = list(set(fitur) - set(categorical_cols))
        
        encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
        encoder.fit(X_train[categorical_cols])
        
        X_train_enc = encoder.transform(X_train[categorical_cols])
        X_test_enc = encoder.transform(X_test[categorical_cols])
        enc_cols = encoder.get_feature_names_out(categorical_cols)
        
        X_train_final = pd.concat([
            X_train[numeric_cols].reset_index(drop=True),
            pd.DataFrame(X_train_enc, columns=enc_cols)
        ], axis=1)
        
        X_test_final = pd.concat([
            X_test[numeric_cols].reset_index(drop=True),
            pd.DataFrame(X_test_enc, columns=enc_cols)
        ], axis=1)
    else:
        X_train_final = X_train.copy()
        X_test_final = X_test.copy()
    
    
    # --- Full model ---
    model_full = XGBRegressor(
        n_estimators=n_estimators, max_depth=6, learning_rate=0.05, n_jobs=-1,
        objective="reg:absoluteerror"
    )
    model_full.fit(X_train_final, y_train)
    y_pred_full = model_full.predict(X_test_final)
    mape_full = mean_absolute_percentage_error(y_test, y_pred_full)
    print(f"Full model MAPE: {mape_full:.4f}")
    
    # --- Backward elimination dengan tqdm ---
    features = list(X_train_final.columns)
    best_features = features.copy()
    
    # fitur asli = numeric + categorical
    original_features = fitur_num + fitur_cat   # 10 numeric + 7 categorical = 17
    best_original_features = original_features.copy()

    for feat in tqdm(original_features, desc="Backward Elimination", unit="feat"):
        print(feat)
        # jika feat kategorikal → hapus semua kolom hasil encoding untuk fitur ini
        if feat in fitur_cat:
            cols_to_remove = [c for c in best_features if c.startswith(feat)]
        else:
            cols_to_remove = [feat]
        
        temp_features = [f for f in best_features if f not in cols_to_remove]
        
        # ... training model sama seperti sebelumnya

        model = XGBRegressor(
            n_estimators=n_estimators, max_depth=6, learning_rate=0.05, n_jobs=-1,
            objective="reg:absoluteerror"
        )
        model.fit(X_train_final[temp_features], y_train)
        y_pred = model.predict(X_test_final[temp_features])
        mape = mean_absolute_percentage_error(y_test, y_pred)

        
        if (abs(mape - mape_full) <= tol) or (mape <= mape_full):
            print("remove")
            best_original_features.remove(feat)
            for col in cols_to_remove:
                best_features.remove(col)

        print(f"MAPE: {mape:.4f} ({mape*100:.2f}%)")
        print(f"MAPE full: {mape_full:.4f} ({mape_full*100:.2f}%)\n")
        
    print(f"\nFinal features ({len(best_original_features)}): {best_original_features}")
    print(f"final MAPE: {mape_full:.4f} ({mape_full*100:.2f}%)")
    
    # --- Train final model full trees ---
    final_model = XGBRegressor(
        n_estimators=2000, max_depth=6, learning_rate=0.05, n_jobs=-1,
        objective="reg:absoluteerror"
    )
    final_model.fit(X_train_final[best_features], y_train)
    
    return final_model, best_original_features, X_test_final[best_features], y_test, y_pred_full

In [312]:
model_landing, features_landing, X_test_landing, y_test_landing, y_pred_landing = backward_feature_elimination(
    target_name="LANDING",
    df_data=df1,
    fitur=fitur,
    fitur_cat=fitur_cat,
    tol=0.005,       # MAPE ±0.5%
    n_estimators=2000 # pakai lebih sedikit trees saat seleksi
)

Full model MAPE: 0.0949

Backward Elimination:   0%|          | 0/18 [00:00<?, ?feat/s]

ASK (000) C CLASS

Backward Elimination:   6%|▌         | 1/18 [01:02<17:39, 62.35s/feat]

remove
MAPE: 0.0981 (9.81%)
MAPE full: 0.0949 (9.49%)

ASK (000) Y CLASS

Backward Elimination:  11%|█         | 2/18 [02:00<16:00, 60.05s/feat]

remove
MAPE: 0.0955 (9.55%)
MAPE full: 0.0949 (9.49%)

SEAT OFFERED C CLASS

Backward Elimination:  17%|█▋        | 3/18 [02:59<14:53, 59.60s/feat]

remove
MAPE: 0.0953 (9.53%)
MAPE full: 0.0949 (9.49%)

ATK PASSENGER (000)

Backward Elimination:  22%|██▏       | 4/18 [04:00<14:01, 60.11s/feat]

MAPE: 0.1297 (12.97%)
MAPE full: 0.0949 (9.49%)

ASK (000)

Backward Elimination:  28%|██▊       | 5/18 [05:01<13:05, 60.42s/feat]

remove
MAPE: 0.0941 (9.41%)
MAPE full: 0.0949 (9.49%)

ATK (000)

Backward Elimination:  33%|███▎      | 6/18 [06:01<12:01, 60.10s/feat]

MAPE: 0.1078 (10.78%)
MAPE full: 0.0949 (9.49%)

SEAT OFFERED

Backward Elimination:  39%|███▉      | 7/18 [07:01<11:02, 60.27s/feat]

remove
MAPE: 0.0950 (9.50%)
MAPE full: 0.0949 (9.49%)

BLOCK HOURS

Backward Elimination:  44%|████▍     | 8/18 [08:00<09:56, 59.68s/feat]

MAPE: 0.1002 (10.02%)
MAPE full: 0.0949 (9.49%)

FLIGHT KILOMETERS

Backward Elimination:  50%|█████     | 9/18 [08:58<08:53, 59.25s/feat]

remove
MAPE: 0.0957 (9.57%)
MAPE full: 0.0949 (9.49%)

GA Service

Backward Elimination:  56%|█████▌    | 10/18 [10:02<08:06, 60.77s/feat]

remove
MAPE: 0.0975 (9.75%)
MAPE full: 0.0949 (9.49%)

AIRCRAFT TYPE GROUPING

Backward Elimination:  61%|██████    | 11/18 [10:58<06:55, 59.39s/feat]

MAPE: 0.1007 (10.07%)
MAPE full: 0.0949 (9.49%)

Region

Backward Elimination:  67%|██████▋   | 12/18 [12:05<06:09, 61.62s/feat]

remove
MAPE: 0.0957 (9.57%)
MAPE full: 0.0949 (9.49%)

SUB-SERVICE

Backward Elimination:  72%|███████▏  | 13/18 [13:06<05:06, 61.34s/feat]

remove
MAPE: 0.0965 (9.65%)
MAPE full: 0.0949 (9.49%)

SERVICE TYPE

Backward Elimination:  78%|███████▊  | 14/18 [14:03<04:00, 60.06s/feat]

remove
MAPE: 0.0979 (9.79%)
MAPE full: 0.0949 (9.49%)

ROUNDTRIPROUTE

Backward Elimination:  83%|████████▎ | 15/18 [14:57<02:54, 58.21s/feat]

remove
MAPE: 0.0974 (9.74%)
MAPE full: 0.0949 (9.49%)

FLIGHT ROUTE

Backward Elimination:  89%|████████▉ | 16/18 [15:43<01:49, 54.63s/feat]

MAPE: 0.1503 (15.03%)
MAPE full: 0.0949 (9.49%)

AC REG

Backward Elimination:  94%|█████████▍| 17/18 [16:33<00:53, 53.10s/feat]

MAPE: 0.1019 (10.19%)
MAPE full: 0.0949 (9.49%)

AIRCRAFT TYPE

Backward Elimination: 100%|██████████| 18/18 [17:25<00:00, 58.10s/feat]

MAPE: 0.1022 (10.22%)
MAPE full: 0.0949 (9.49%)


Final features (7): ['ATK PASSENGER (000)', 'ATK (000)', 'BLOCK HOURS', 'AIRCRAFT TYPE GROUPING', 'FLIGHT ROUTE', 'AC REG', 'AIRCRAFT TYPE']
final MAPE: 0.0949 (9.49%)

In [313]:
print("\nLANDING")
results_landing = pd.DataFrame({'Actual': y_test_landing.values, 'Predicted': y_pred_landing})
results_landing['Diff'] = results_landing['Actual'] - results_landing['Predicted']
print(results_landing.head())

LANDING
       Actual   Predicted       Diff
0  122.290000  127.369644  -5.079644
1   25.160000   29.611059  -4.451059
2   44.274500   46.536270  -2.261770
3   59.060667   47.245167  11.815500
4   50.451207   45.262905   5.188302

## HANDLING

### FITUR

In [320]:
fitur_num = [
    'ASK (000) C CLASS',
    'ASK (000) Y CLASS',
    'SEAT OFFERED C CLASS',
    'ATK PASSENGER (000)',
    'SEAT OFFERED Y CLASS',
    'ASK (000)',            
    'ATK (000)', 
    'SEAT OFFERED',
    'BLOCK HOURS',          
    'FLIGHT KILOMETERS',     
]

fitur_cat = [
    'GA Service',
    'Region',
    'SUB-SERVICE',           
    'SERVICE TYPE',
    'AIRCRAFT TYPE GROUPING',
    'ROUNDTRIPROUTE', 
    'FLIGHT ROUTE',
    'AIRCRAFT TYPE',
    'AC REG',
]

fitur = fitur_num + fitur_cat

### TRAIN-TEST MODEL

In [321]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import mean_absolute_percentage_error, mean_absolute_error, r2_score
from xgboost import XGBRegressor

In [322]:
def train_model(target_name, df_data,fitur,fitur_cat):
    print(f"--- TRAINING MODEL FOR: {target_name} ---")
    
    data = df_data[df_data[target_name] > 0].copy()
    
    X = data[fitur]
    y = data[target_name]
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    categorical_cols = fitur_cat
    numeric_cols = list(set(fitur) - set(categorical_cols))
    
    encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
    encoder.fit(X_train[categorical_cols])
    
    X_train_enc = encoder.transform(X_train[categorical_cols])
    X_test_enc = encoder.transform(X_test[categorical_cols])
    enc_cols = encoder.get_feature_names_out(categorical_cols)
    
    X_train_final = pd.concat([
        X_train[numeric_cols].reset_index(drop=True),
        pd.DataFrame(X_train_enc, columns=enc_cols)
    ], axis=1)
    
    X_test_final = pd.concat([
        X_test[numeric_cols].reset_index(drop=True),
        pd.DataFrame(X_test_enc, columns=enc_cols)
    ], axis=1)
    
    model = XGBRegressor(
        n_estimators=500,
        max_depth=6,
        learning_rate=0.05,
        n_jobs=-1,
        objective="reg:absoluteerror" 
    )
    
    model.fit(X_train_final, y_train)
    y_pred = model.predict(X_test_final)
    
    # Evaluasi
    mape = mean_absolute_percentage_error(y_test, y_pred)

    print(f"MAPE: {mape:.4f} ({mape*100:.2f}%)")
    
    return model, encoder, X_test_final, y_test, y_pred

In [ ]:
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_percentage_error
import pandas as pd
from tqdm import tqdm

def backward_feature_elimination(target_name, df_data, fitur, fitur_cat, tol=0.005, n_estimators=500):
    """
    Backward Feature Elimination untuk XGBoost dengan progress bar
    """
    # --- Data split ---
    data = df_data[df_data[target_name] > 0].copy()
    X = data[fitur]
    y = data[target_name]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    # --- Encode categorical ---
    if fitur_cat:
        categorical_cols = fitur_cat
        numeric_cols = list(set(fitur) - set(categorical_cols))
        
        encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
        encoder.fit(X_train[categorical_cols])
        
        X_train_enc = encoder.transform(X_train[categorical_cols])
        X_test_enc = encoder.transform(X_test[categorical_cols])
        enc_cols = encoder.get_feature_names_out(categorical_cols)
        
        X_train_final = pd.concat([
            X_train[numeric_cols].reset_index(drop=True),
            pd.DataFrame(X_train_enc, columns=enc_cols)
        ], axis=1)
        
        X_test_final = pd.concat([
            X_test[numeric_cols].reset_index(drop=True),
            pd.DataFrame(X_test_enc, columns=enc_cols)
        ], axis=1)
    else:
        X_train_final = X_train.copy()
        X_test_final = X_test.copy()
    
    
    # --- Full model ---
    model_full = XGBRegressor(
        n_estimators=n_estimators, max_depth=6, learning_rate=0.05, n_jobs=-1,
        objective="reg:absoluteerror"
    )
    model_full.fit(X_train_final, y_train)
    y_pred_full = model_full.predict(X_test_final)
    mape_full = mean_absolute_percentage_error(y_test, y_pred_full)
    print(f"Full model MAPE: {mape_full:.4f}")
    
    # --- Backward elimination dengan tqdm ---
    features = list(X_train_final.columns)
    best_features = features.copy()
    
    # fitur asli = numeric + categorical
    original_features = fitur_num + fitur_cat   # 10 numeric + 7 categorical = 17
    best_original_features = original_features.copy()

    for feat in tqdm(original_features, desc="Backward Elimination", unit="feat"):
        print(feat)
        # jika feat kategorikal → hapus semua kolom hasil encoding untuk fitur ini
        if feat in fitur_cat:
            cols_to_remove = [c for c in best_features if c.startswith(feat)]
        else:
            cols_to_remove = [feat]
        
        temp_features = [f for f in best_features if f not in cols_to_remove]
        
        # ... training model sama seperti sebelumnya

        model = XGBRegressor(
            n_estimators=n_estimators, max_depth=6, learning_rate=0.05, n_jobs=-1,
            objective="reg:absoluteerror"
        )
        model.fit(X_train_final[temp_features], y_train)
        y_pred = model.predict(X_test_final[temp_features])
        mape = mean_absolute_percentage_error(y_test, y_pred)

        
        if (abs(mape - mape_full) <= tol) or (mape <= mape_full):
            print("remove")
            best_original_features.remove(feat)
            for col in cols_to_remove:
                best_features.remove(col)

        print(f"MAPE: {mape:.4f} ({mape*100:.2f}%)")
        print(f"MAPE full: {mape_full:.4f} ({mape_full*100:.2f}%)\n")
        
    print(f"\nFinal features ({len(best_original_features)}): {best_original_features}")
    print(f"final MAPE: {mape:.4f} ({mape*100:.2f}%)")
    
    # --- Train final model full trees ---
    final_model = XGBRegressor(
        n_estimators=2000, max_depth=6, learning_rate=0.05, n_jobs=-1,
        objective="reg:absoluteerror"
    )
    final_model.fit(X_train_final[best_features], y_train)
    
    return final_model, best_original_features, X_test_final[best_features], y_test, y_pred_full

In [324]:
model_handling, features_handling, X_test_handling, y_test_handling, y_pred_handling = backward_feature_elimination(
    target_name="HANDLING",
    df_data=df1,
    fitur=fitur,
    fitur_cat=fitur_cat,
    tol=0.005,       # MAPE ±0.5%
    n_estimators=2000 # pakai lebih sedikit trees saat seleksi
)

Full model MAPE: 0.0645

Backward Elimination:   0%|          | 0/19 [00:00<?, ?feat/s]

ASK (000) C CLASS

Backward Elimination:   5%|▌         | 1/19 [00:57<17:08, 57.14s/feat]

remove
MAPE: 0.0683 (6.83%)
MAPE full: 0.0645 (6.45%)

ASK (000) Y CLASS

Backward Elimination:  11%|█         | 2/19 [01:55<16:22, 57.78s/feat]

remove
MAPE: 0.0623 (6.23%)
MAPE full: 0.0645 (6.45%)

SEAT OFFERED C CLASS

Backward Elimination:  16%|█▌        | 3/19 [02:55<15:41, 58.85s/feat]

remove
MAPE: 0.0680 (6.80%)
MAPE full: 0.0645 (6.45%)

ATK PASSENGER (000)

Backward Elimination:  21%|██        | 4/19 [03:54<14:41, 58.78s/feat]

MAPE: 0.0821 (8.21%)
MAPE full: 0.0645 (6.45%)

SEAT OFFERED Y CLASS

Backward Elimination:  26%|██▋       | 5/19 [04:50<13:30, 57.88s/feat]

remove
MAPE: 0.0674 (6.74%)
MAPE full: 0.0645 (6.45%)

ASK (000)

Backward Elimination:  32%|███▏      | 6/19 [05:46<12:25, 57.38s/feat]

remove
MAPE: 0.0630 (6.30%)
MAPE full: 0.0645 (6.45%)

ATK (000)

Backward Elimination:  37%|███▋      | 7/19 [06:42<11:21, 56.78s/feat]

MAPE: 0.0734 (7.34%)
MAPE full: 0.0645 (6.45%)

SEAT OFFERED

Backward Elimination:  42%|████▏     | 8/19 [07:37<10:18, 56.27s/feat]

remove
MAPE: 0.0668 (6.68%)
MAPE full: 0.0645 (6.45%)

BLOCK HOURS

Backward Elimination:  47%|████▋     | 9/19 [08:32<09:19, 55.93s/feat]

MAPE: 0.0698 (6.98%)
MAPE full: 0.0645 (6.45%)

FLIGHT KILOMETERS

Backward Elimination:  53%|█████▎    | 10/19 [09:39<08:53, 59.31s/feat]

remove
MAPE: 0.0630 (6.30%)
MAPE full: 0.0645 (6.45%)

GA Service

Backward Elimination:  58%|█████▊    | 11/19 [10:41<08:01, 60.23s/feat]

remove
MAPE: 0.0656 (6.56%)
MAPE full: 0.0645 (6.45%)

Region

Backward Elimination:  63%|██████▎   | 12/19 [11:37<06:51, 58.75s/feat]

remove
MAPE: 0.0628 (6.28%)
MAPE full: 0.0645 (6.45%)

SUB-SERVICE

Backward Elimination:  68%|██████▊   | 13/19 [12:33<05:47, 57.84s/feat]

remove
MAPE: 0.0632 (6.32%)
MAPE full: 0.0645 (6.45%)

SERVICE TYPE

Backward Elimination:  74%|███████▎  | 14/19 [13:27<04:44, 56.94s/feat]

remove
MAPE: 0.0624 (6.24%)
MAPE full: 0.0645 (6.45%)

AIRCRAFT TYPE GROUPING

Backward Elimination:  79%|███████▉  | 15/19 [14:22<03:45, 56.32s/feat]

remove
MAPE: 0.0658 (6.58%)
MAPE full: 0.0645 (6.45%)

ROUNDTRIPROUTE

Backward Elimination:  84%|████████▍ | 16/19 [15:14<02:45, 55.07s/feat]

remove
MAPE: 0.0653 (6.53%)
MAPE full: 0.0645 (6.45%)

FLIGHT ROUTE

Backward Elimination:  89%|████████▉ | 17/19 [16:00<01:44, 52.29s/feat]

MAPE: 0.1297 (12.97%)
MAPE full: 0.0645 (6.45%)

AIRCRAFT TYPE

Backward Elimination:  95%|█████████▍| 18/19 [16:52<00:52, 52.18s/feat]

remove
MAPE: 0.0633 (6.33%)
MAPE full: 0.0645 (6.45%)

AC REG

Backward Elimination: 100%|██████████| 19/19 [17:43<00:00, 55.96s/feat]

MAPE: 0.0763 (7.63%)
MAPE full: 0.0645 (6.45%)


Final features (5): ['ATK PASSENGER (000)', 'ATK (000)', 'BLOCK HOURS', 'FLIGHT ROUTE', 'AC REG']
final MAPE: 0.0763 (7.63%)

In [325]:
print("\nHANDLING")
results_handling = pd.DataFrame({'Actual': y_test_handling.values, 'Predicted': y_pred_handling})
results_handling['Diff'] = results_handling['Actual'] - results_handling['Predicted']
print(results_handling.head())

HANDLING
       Actual   Predicted       Diff
0  230.977000  275.224701 -44.247701
1  288.667500  349.818573 -61.151073
2  446.808333  436.793701  10.014632
3  327.443810  365.317841 -37.874031
4  416.989034  360.045624  56.943411

## AIR TRAFFIC CONTROL

### FITUR

In [326]:
fitur_num = [   
    'ASK (000) C CLASS',
    'ASK (000) Y CLASS',
    'SEAT OFFERED C CLASS',
    'SEAT OFFERED Y CLASS',
    'ATK PASSENGER (000)',
    'SEAT OFFERED',
    'ASK (000)',            
    'ATK (000)',
    'BLOCK HOURS',          
    'FLIGHT KILOMETERS',      
]

fitur_cat = [
    'GA Service',
    'Region',
    'SUB-SERVICE',           
    'SERVICE TYPE',
    'AIRCRAFT TYPE GROUPING',
    'ROUNDTRIPROUTE', 
    'FLIGHT ROUTE',
    'AIRCRAFT TYPE',
    'AC REG',
]

fitur = fitur_num + fitur_cat

In [327]:
# fitur_num = [
#     'FLIGHT KILOMETERS',    
#     'ATK (000)', 
#     'SEAT OFFERED',
#     'ATK PASSENGER (000)',    
# ]

# fitur_cat = [
#     'AIRCRAFT TYPE',        
#     'FLIGHT ROUTE', 
# ]

# fitur = fitur_num + fitur_cat

### TRAIN-TEST MODEL

In [328]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import mean_absolute_percentage_error, mean_absolute_error, r2_score
from xgboost import XGBRegressor

In [329]:
def train_model(target_name, df_data,fitur,fitur_cat):
    print(f"--- TRAINING MODEL FOR: {target_name} ---")
    
    data = df_data[df_data[target_name] > 0].copy()
    
    X = data[fitur]
    y = data[target_name]
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    categorical_cols = fitur_cat
    numeric_cols = list(set(fitur) - set(categorical_cols))
    
    encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
    encoder.fit(X_train[categorical_cols])
    
    X_train_enc = encoder.transform(X_train[categorical_cols])
    X_test_enc = encoder.transform(X_test[categorical_cols])
    enc_cols = encoder.get_feature_names_out(categorical_cols)
    
    X_train_final = pd.concat([
        X_train[numeric_cols].reset_index(drop=True),
        pd.DataFrame(X_train_enc, columns=enc_cols)
    ], axis=1)
    
    X_test_final = pd.concat([
        X_test[numeric_cols].reset_index(drop=True),
        pd.DataFrame(X_test_enc, columns=enc_cols)
    ], axis=1)
    
    model = XGBRegressor(
        n_estimators=500,
        max_depth=6,
        learning_rate=0.05,
        n_jobs=-1,
        objective="reg:absoluteerror" 
    )
    
    model.fit(X_train_final, y_train)
    y_pred = model.predict(X_test_final)
    
    # Evaluasi
    mape = mean_absolute_percentage_error(y_test, y_pred)

    print(f"MAPE: {mape:.4f} ({mape*100:.2f}%)")
    
    return model, encoder, X_test_final, y_test, y_pred

In [335]:
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_percentage_error
import pandas as pd
from tqdm import tqdm

def backward_feature_elimination(target_name, df_data, fitur, fitur_cat, tol=0.005, n_estimators=500):
    """
    Backward Feature Elimination untuk XGBoost dengan progress bar
    """
    # --- Data split ---
    data = df_data[df_data[target_name] > 0].copy()
    X = data[fitur]
    y = data[target_name]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    # --- Encode categorical ---
    if fitur_cat:
        categorical_cols = fitur_cat
        numeric_cols = list(set(fitur) - set(categorical_cols))
        
        encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
        encoder.fit(X_train[categorical_cols])
        
        X_train_enc = encoder.transform(X_train[categorical_cols])
        X_test_enc = encoder.transform(X_test[categorical_cols])
        enc_cols = encoder.get_feature_names_out(categorical_cols)
        
        X_train_final = pd.concat([
            X_train[numeric_cols].reset_index(drop=True),
            pd.DataFrame(X_train_enc, columns=enc_cols)
        ], axis=1)
        
        X_test_final = pd.concat([
            X_test[numeric_cols].reset_index(drop=True),
            pd.DataFrame(X_test_enc, columns=enc_cols)
        ], axis=1)
    else:
        X_train_final = X_train.copy()
        X_test_final = X_test.copy()
    
    
    # --- Full model ---
    model_full = XGBRegressor(
        n_estimators=n_estimators, max_depth=6, learning_rate=0.05, n_jobs=-1,
        objective="reg:absoluteerror"
    )
    model_full.fit(X_train_final, y_train)
    y_pred_full = model_full.predict(X_test_final)
    mape_full = mean_absolute_percentage_error(y_test, y_pred_full)
    print(f"Full model MAPE: {mape_full:.4f}")
    
    # --- Backward elimination dengan tqdm ---
    features = list(X_train_final.columns)
    best_features = features.copy()
    
    # fitur asli = numeric + categorical
    original_features = fitur_num + fitur_cat   # 10 numeric + 7 categorical = 17
    best_original_features = original_features.copy()

    for feat in tqdm(original_features, desc="Backward Elimination", unit="feat"):
        print(feat)
        # jika feat kategorikal → hapus semua kolom hasil encoding untuk fitur ini
        if feat in fitur_cat:
            cols_to_remove = [c for c in best_features if c.startswith(feat)]
        else:
            cols_to_remove = [feat]
        
        temp_features = [f for f in best_features if f not in cols_to_remove]
        
        # ... training model sama seperti sebelumnya

        model = XGBRegressor(
            n_estimators=n_estimators, max_depth=6, learning_rate=0.05, n_jobs=-1,
            objective="reg:absoluteerror"
        )
        model.fit(X_train_final[temp_features], y_train)
        y_pred = model.predict(X_test_final[temp_features])
        mape = mean_absolute_percentage_error(y_test, y_pred)

        
        if (abs(mape - mape_full) <= tol) or (mape <= mape_full):
            print("remove")
            best_original_features.remove(feat)
            for col in cols_to_remove:
                best_features.remove(col)

        print(f"MAPE: {mape:.4f} ({mape*100:.2f}%)")
        print(f"MAPE full: {mape_full:.4f} ({mape_full*100:.2f}%)\n")
        
    print(f"\nFinal features ({len(best_original_features)}): {best_original_features}")
    
    # --- Train final model full trees ---
    final_model = XGBRegressor(
        n_estimators=2000, max_depth=6, learning_rate=0.05, n_jobs=-1,
        objective="reg:absoluteerror"
    )
    final_model.fit(X_train_final[best_features], y_train)
    y_pred = model.predict(X_test_final[temp_features])
    mape = mean_absolute_percentage_error(y_test, y_pred)
    
    print(f"final MAPE: {mape:.4f} ({mape_full*100:.2f}%)")
    
    return final_model, best_original_features, X_test_final[best_features], y_test, y_pred_full

In [336]:
model_atc, features_atc, X_test_atc, y_test_atc, y_pred_atc = backward_feature_elimination(
    target_name="AIR TRAFFIC CONTROL",
    df_data=df1,
    fitur=fitur,
    fitur_cat=fitur_cat,
    tol=0.005,       # MAPE ±0.5%
    n_estimators=2000 # pakai lebih sedikit trees saat seleksi
)

Full model MAPE: 0.1953

Backward Elimination:   0%|          | 0/19 [00:00<?, ?feat/s]

ASK (000) C CLASS

Backward Elimination:   5%|▌         | 1/19 [00:54<16:15, 54.17s/feat]

remove
MAPE: 0.1962 (19.62%)
MAPE full: 0.1953 (19.53%)

ASK (000) Y CLASS

Backward Elimination:  11%|█         | 2/19 [01:51<15:51, 55.96s/feat]

remove
MAPE: 0.1924 (19.24%)
MAPE full: 0.1953 (19.53%)

SEAT OFFERED C CLASS

Backward Elimination:  16%|█▌        | 3/19 [02:42<14:22, 53.92s/feat]

remove
MAPE: 0.1859 (18.59%)
MAPE full: 0.1953 (19.53%)

SEAT OFFERED Y CLASS

Backward Elimination:  21%|██        | 4/19 [03:35<13:21, 53.43s/feat]

remove
MAPE: 0.1890 (18.90%)
MAPE full: 0.1953 (19.53%)

ATK PASSENGER (000)

Backward Elimination:  26%|██▋       | 5/19 [04:31<12:41, 54.38s/feat]

MAPE: 0.2378 (23.78%)
MAPE full: 0.1953 (19.53%)

SEAT OFFERED

Backward Elimination:  32%|███▏      | 6/19 [05:26<11:50, 54.67s/feat]

remove
MAPE: 0.1892 (18.92%)
MAPE full: 0.1953 (19.53%)

ASK (000)

Backward Elimination:  37%|███▋      | 7/19 [06:22<11:01, 55.15s/feat]

remove
MAPE: 0.2001 (20.01%)
MAPE full: 0.1953 (19.53%)

ATK (000)

Backward Elimination:  42%|████▏     | 8/19 [07:17<10:04, 54.92s/feat]

MAPE: 0.2267 (22.67%)
MAPE full: 0.1953 (19.53%)

BLOCK HOURS

Backward Elimination:  47%|████▋     | 9/19 [08:09<09:00, 54.03s/feat]

MAPE: 0.2075 (20.75%)
MAPE full: 0.1953 (19.53%)

FLIGHT KILOMETERS

Backward Elimination:  53%|█████▎    | 10/19 [09:01<08:01, 53.52s/feat]

remove
MAPE: 0.1852 (18.52%)
MAPE full: 0.1953 (19.53%)

GA Service

Backward Elimination:  58%|█████▊    | 11/19 [09:54<07:07, 53.39s/feat]

remove
MAPE: 0.1868 (18.68%)
MAPE full: 0.1953 (19.53%)

Region

Backward Elimination:  63%|██████▎   | 12/19 [10:46<06:09, 52.79s/feat]

remove
MAPE: 0.1895 (18.95%)
MAPE full: 0.1953 (19.53%)

SUB-SERVICE

Backward Elimination:  68%|██████▊   | 13/19 [11:38<05:14, 52.46s/feat]

remove
MAPE: 0.1869 (18.69%)
MAPE full: 0.1953 (19.53%)

SERVICE TYPE

Backward Elimination:  74%|███████▎  | 14/19 [12:30<04:22, 52.57s/feat]

remove
MAPE: 0.1924 (19.24%)
MAPE full: 0.1953 (19.53%)

AIRCRAFT TYPE GROUPING

Backward Elimination:  79%|███████▉  | 15/19 [13:22<03:29, 52.34s/feat]

remove
MAPE: 0.1858 (18.58%)
MAPE full: 0.1953 (19.53%)

ROUNDTRIPROUTE

Backward Elimination:  84%|████████▍ | 16/19 [14:11<02:34, 51.37s/feat]

remove
MAPE: 0.1870 (18.70%)
MAPE full: 0.1953 (19.53%)

FLIGHT ROUTE

Backward Elimination:  89%|████████▉ | 17/19 [14:51<01:35, 47.84s/feat]

remove
MAPE: 0.1886 (18.86%)
MAPE full: 0.1953 (19.53%)

AIRCRAFT TYPE

Backward Elimination:  95%|█████████▍| 18/19 [15:31<00:45, 45.45s/feat]

remove
MAPE: 0.1879 (18.79%)
MAPE full: 0.1953 (19.53%)

AC REG

Backward Elimination: 100%|██████████| 19/19 [16:00<00:00, 50.58s/feat]

remove
MAPE: 0.1993 (19.93%)
MAPE full: 0.1953 (19.53%)


Final features (3): ['ATK PASSENGER (000)', 'ATK (000)', 'BLOCK HOURS']

final MAPE: 0.1993 (19.53%)

In [341]:
## LANDING
NUMERICAL_COLS_LANDING = ['ATK PASSENGER (000)', 'ATK (000)', 'BLOCK HOURS', ]
CATEGORICAL_COLS_LANDING = ['AIRCRAFT TYPE GROUPING', 'FLIGHT ROUTE', 'AC REG', 'AIRCRAFT TYPE']

SELECTED_FEATURES_LANDING = NUMERICAL_COLS_LANDING + CATEGORICAL_COLS_LANDING

## HANDLING
NUMERICAL_COLS_HANDLING = ['ATK PASSENGER (000)', 'ATK (000)', 'BLOCK HOURS', ]
CATEGORICAL_COLS_HANDLING = ['FLIGHT ROUTE', 'AC REG']
SELECTED_FEATURES_HANDLING = NUMERICAL_COLS_HANDLING + CATEGORICAL_COLS_HANDLING

## AIR TRAFFIC CONTROL
NUMERICAL_COLS_ATC = ['ATK PASSENGER (000)', 'ATK (000)', 'BLOCK HOURS',]
CATEGORICAL_COLS_ATC = ['AIRCRAFT TYPE GROUPING', 'FLIGHT ROUTE', 'ROUNDTRIPROUTE', 'AC REG', 'AIRCRAFT TYPE']
SELECTED_FEATURES_ATC = NUMERICAL_COLS_ATC + CATEGORICAL_COLS_ATC

def clean_col_name(col):
    return (
        col.replace(" ", "_")
           .replace("(", "")
           .replace(")", "")
    )


NUMERICAL_COLS_LANDING = [clean_col_name(c) for c in [
    'ATK PASSENGER (000)', 
    'ATK (000)', 
    'BLOCK HOURS',
]]

CATEGORICAL_COLS_LANDING = [clean_col_name(c) for c in [
    'AIRCRAFT TYPE GROUPING', 
    'FLIGHT ROUTE', 
    'AC REG', 
    'AIRCRAFT TYPE'
]]

SELECTED_FEATURES_LANDING = NUMERICAL_COLS_LANDING + CATEGORICAL_COLS_LANDING
NUMERICAL_COLS_LANDING

['ATK_PASSENGER_000', 'ATK_000', 'BLOCK_HOURS']

In [ ]:
['ATK PASSENGER (000)', 'ATK (000)', 'BLOCK HOURS','AIRCRAFT TYPE GROUPING', 'FLIGHT ROUTE', 'ROUNDTRIPROUTE' 'AC REG', 'AIRCRAFT TYPE']

In [ ]:
print("\nATC")
results_atc = pd.DataFrame({'Actual': y_test_atc.values, 'Predicted': y_pred_atc})
results_atc['Diff'] = results_atc['Actual'] - results_atc['Predicted']
print(results_atc.head())

COCKPIT CREW TRAVEL
       Actual   Predicted       Diff
0  182.585041  156.679657  25.905384
1  106.171559  119.615593 -13.444034
2  184.391236  184.417679  -0.026442
3  128.758906  129.485184  -0.726277
4  126.732800  123.699890   3.032910

COCKPIT CREW TRAVEL
       Actual   Predicted       Diff
0  395.460020  386.801361   8.658659
1  161.768471  173.225525 -11.457054
2  268.813794  277.358032  -8.544238
3  138.513795  134.575378   3.938417
4  157.169144  160.428909  -3.259765