In [28]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_selection import mutual_info_regression
from scipy.stats import f_oneway
import numpy as np
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_excel("05. Database RP May 2025 - AC REGISTER.xlsx", sheet_name="Raw", skiprows=1)

In [4]:
# Ganti 'df' dengan nama variabel dataframe kamu (misal df1 atau df)
print(df[['LANDING', 'HANDLING', 'AIR TRAFFIC CONTROL']].head())

     LANDING    HANDLING  AIR TRAFFIC CONTROL
0  30.289484  358.895323           154.756355
1  30.289484  358.895323           154.756355
2  30.289484  358.895323           154.756355
3  30.289484  358.895323           154.756355
4  30.289484  358.895323           154.756355

In [5]:
df

,Unnamed: 0,YEAR,PERIODE,AIRCRAFT TYPE,FLIGHT NUMBER_CITYPAIR,SERVICE TYPE,SUB-SERVICE,ROUNDTRIPROUTE,FLIGHT ROUTE,AC REG,...,RPK (000) C CLASS,RPK (000) Y CLASS,OTHER REVENUE PASSENGER,OTHER REVENUE FREIGHT,QUARTER,STATUS,AIRCRAFT TYPE GROUPING,FLIGHT TYPE,GA Service,Region
0,NaN,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGNR,...,0.573,28.268,382.164660,1.366988,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
1,NaN,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGFJ,...,0.955,27.886,427.183511,15.077904,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
2,NaN,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGNA,...,0.191,28.841,489.566409,47.838249,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
3,NaN,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGNR,...,2.483,27.886,593.068566,1.376459,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
4,NaN,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGMW,...,0.573,28.077,448.429472,30.733542,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110775,NaN,2025,MAY,AC738,GA6054.KDI-UPG.[KDI-UPG],DOM,DOM_4 (UPG),UPG-KDI-UPG,KDI-UPG,PKGUF,...,4.032,49.056,460.586000,0.000000,Q2,ACTUAL,B738NG,PAX & CARGO,IBT,DOM_EAST
110776,NaN,2025,MAY,AC73H,GA2084.CGK-YIA.[CGK-YIA],DOM,DOM_3 (SUB),CGK-YIA-CGK,CGK-YIA,PKGUH,...,2.968,45.368,372.671000,88.178000,Q2,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
110777,NaN,2025,MAY,AC73H,GA2094.YIA-CGK.[YIA-CGK],DOM,DOM_3 (SUB),CGK-YIA-CGK,YIA-CGK,PKGUH,...,3.392,46.640,444.734000,234.301000,Q2,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
110778,NaN,2025,MAY,AC73H,GA4324.CGK-AMI.[CGK-AMI],DOM,DOM_2 (JKT),CGK-AMI-CGK,CGK-AMI,PKGUI,...,7.707,180.564,904.093000,397.316000,Q2,ACTUAL,B738NG,PAX & CARGO,IBT,DOM_EAST
110779,NaN,2025,MAY,AC73H,GA4344.AMI-CGK.[AMI-CGK],DOM,DOM_2 (JKT),CGK-AMI-CGK,AMI-CGK,PKGUI,...,5.505,94.686,484.366000,260.866000,Q2,ACTUAL,B738NG,PAX & CARGO,IBT,DOM_EAST

In [6]:
df = df.iloc[:, 1:]

In [7]:
print([df])

[        YEAR PERIODE AIRCRAFT TYPE    FLIGHT NUMBER_CITYPAIR SERVICE TYPE  \
0       2024     JAN         AC738  GA0072.CGK-TKG.[CGK-TKG]          DOM
1       2024     JAN         AC738  GA0072.CGK-TKG.[CGK-TKG]          DOM
2       2024     JAN         AC738  GA0072.CGK-TKG.[CGK-TKG]          DOM
3       2024     JAN         AC738  GA0072.CGK-TKG.[CGK-TKG]          DOM
4       2024     JAN         AC738  GA0072.CGK-TKG.[CGK-TKG]          DOM
...      ...     ...           ...                       ...          ...
110775  2025     MAY         AC738  GA6054.KDI-UPG.[KDI-UPG]          DOM
110776  2025     MAY         AC73H  GA2084.CGK-YIA.[CGK-YIA]          DOM
110777  2025     MAY         AC73H  GA2094.YIA-CGK.[YIA-CGK]          DOM
110778  2025     MAY         AC73H  GA4324.CGK-AMI.[CGK-AMI]          DOM
110779  2025     MAY         AC73H  GA4344.AMI-CGK.[AMI-CGK]          DOM

        SUB-SERVICE ROUNDTRIPROUTE FLIGHT ROUTE AC REG      DATE  ...  \
0       DOM_2 (JKT)    CGK-TKG-CGK      CGK-TKG  PKGNR  30012024  ...
1       DOM_2 (JKT)    CGK-TKG-CGK      CGK-TKG  PKGFJ  31012024  ...
2       DOM_2 (JKT)    CGK-TKG-CGK      CGK-TKG  PKGNA   1012024  ...
3       DOM_2 (JKT)    CGK-TKG-CGK      CGK-TKG  PKGNR   2012024  ...
4       DOM_2 (JKT)    CGK-TKG-CGK      CGK-TKG  PKGMW  19012024  ...
...             ...            ...          ...    ...       ...  ...
110775  DOM_4 (UPG)    UPG-KDI-UPG      KDI-UPG  PKGUF  24052025  ...
110776  DOM_3 (SUB)    CGK-YIA-CGK      CGK-YIA  PKGUH  28052025  ...
110777  DOM_3 (SUB)    CGK-YIA-CGK      YIA-CGK  PKGUH  28052025  ...
110778  DOM_2 (JKT)    CGK-AMI-CGK      CGK-AMI  PKGUI  29052025  ...
110779  DOM_2 (JKT)    CGK-AMI-CGK      AMI-CGK  PKGUI  29052025  ...

        RPK (000) C CLASS  RPK (000) Y CLASS  OTHER REVENUE PASSENGER  \
0                   0.573             28.268               382.164660
1                   0.955             27.886               427.183511
2                   0.191             28.841               489.566409
3                   2.483             27.886               593.068566
4                   0.573             28.077               448.429472
...                   ...                ...                      ...
110775              4.032             49.056               460.586000
110776              2.968             45.368               372.671000
110777              3.392             46.640               444.734000
110778              7.707            180.564               904.093000
110779              5.505             94.686               484.366000

        OTHER REVENUE FREIGHT  QUARTER  STATUS  AIRCRAFT TYPE GROUPING  \
0                    1.366988       Q1  ACTUAL                  B738NG
1                   15.077904       Q1  ACTUAL                  B738NG
2                   47.838249       Q1  ACTUAL                  B738NG
3                    1.376459       Q1  ACTUAL                  B738NG
4                   30.733542       Q1  ACTUAL                  B738NG
...                       ...      ...     ...                     ...
110775               0.000000       Q2  ACTUAL                  B738NG
110776              88.178000       Q2  ACTUAL                  B738NG
110777             234.301000       Q2  ACTUAL                  B738NG
110778             397.316000       Q2  ACTUAL                  B738NG
110779             260.866000       Q2  ACTUAL                  B738NG

        FLIGHT TYPE  GA Service    Region
0       PAX & CARGO         IBB  DOM_WEST
1       PAX & CARGO         IBB  DOM_WEST
2       PAX & CARGO         IBB  DOM_WEST
3       PAX & CARGO         IBB  DOM_WEST
4       PAX & CARGO         IBB  DOM_WEST
...             ...         ...       ...
110775  PAX & CARGO         IBT  DOM_EAST
110776  PAX & CARGO         IBB  DOM_WEST
110777  PAX & CARGO         IBB  DOM_WEST
110778  PAX & CARGO         IBT  DOM_EAST
110779  PAX & CARGO         IBT  DOM_EAST

[110780 rows x 145 columns]]

In [69]:
df1 = df[
    (df['BLOCK HOURS'] > 0) & 
    (df['ASK (000)'] > 0) &
    (df['COCKPIT CREW TRAVEL'] >= 0) &
    (df['CABIN CREW TRAVEL'] >= 0)
].copy()

# Corr

## Num Corr

### LANDING

In [25]:
df_num = df.select_dtypes(include=["number"])

corr = df_num.corrwith(df_num['LANDING']).sort_values(ascending=False).dropna()

print(corr.head(60))

LANDING                                         1.000000
TOTAL DIRECT FLIGHT COSTS                       0.843416
TOTAL DIRECT COSTS                              0.841866
TOTAL DIRECT AND INDIRECT COSTS                 0.840289
TOTAL DIRECT,INDIRECT,FLEET COSTS               0.833005
TOTAL BO COSTS                                  0.833004
TOTAL COSTS                                     0.829786
ASK (000) C CLASS                               0.826459
CABIN CREW TRAVEL                               0.822218
FUEL BURN (IN LITER)                            0.819790
ATK (000)                                       0.819552
FUEL AIRCRAFT                                   0.815488
ATK PASSENGER (000)                             0.806120
ASK (000)                                       0.804341
LEASE AIRCRAFT                                  0.799613
ASK (000) Y CLASS                               0.795705
CABIN CREW PERSON                               0.792786
TOTAL INDIRECT COSTS                            0.789951
TOTAL FLEET COST                                0.785807
COCKPIT CREW TRAVEL                             0.778726
COCKPIT CREW PERSON                             0.774433
FLIGHT KILOMETERS                               0.772233
FLIGHT HOURS                                    0.770008
BLOCK HOURS                                     0.769269
RTK (000)                                       0.768028
RPK (000) C CLASS                               0.758891
MAINTENANCE RESERVE                             0.751886
RTK PASSENGER (000)                             0.746956
RPK (000)                                       0.744814
INSURANCE                                       0.732300
HANDLING                                        0.732266
RPK (000) Y CLASS                               0.732052
ADMINISTRATION HO                               0.725834
NETT REVENUES                                   0.716344
TOTAL DIRECT TRAFFIC COSTS                      0.709679
SEAT OFFERED                                    0.706289
SEAT OFFERED C CLASS                            0.705465
PASSENGER REVENUE NETT                          0.705055
PASSENGER REVENUE GROSS                         0.704939
VARIABLE MAINTENANCE                            0.689778
SEAT OFFERED Y CLASS                            0.685456
AIR TRAFFIC CONTROL                             0.682647
PASSENGER REVENUE NETT (EXCLUDE EBT) C CLASS    0.679644
PASSENGER REVENUE GROSS C CLASS                 0.679595
OTHER REVENUE PASSENGER                         0.676267
PASSENGER REVENUE NETT Y CLASS                  0.668330
PASSENGER REVENUE NETT C CLASS                  0.667227
PASSENGER REVENUE NETT (EXCLUDE EBT) Y CLASS    0.665728
PASSENGER REVENUE GROSS Y CLASS                 0.665659
CATERING                                        0.625374
OTHER REVENUE                                   0.603330
PASSENGER COMMISSION                            0.601498
PASSENGER CARRIED C CLASS                       0.591475
STATION                                         0.590949
MARKETING                                       0.587931
TOTAL OVERHEAD COST BO                          0.584409
AIRCRAFT MAINTENANCE                            0.553287
CREDIT CARD COMMISSION                          0.549683
ATK CARGO (000)                                 0.548927
RTK FREIGHT (000)                               0.533264
dtype: float64

c:\Oscar\GDI\ML GI\.venv\Lib\site-packages\numpy\lib\_function_base_impl.py:3045: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
c:\Oscar\GDI\ML GI\.venv\Lib\site-packages\numpy\lib\_function_base_impl.py:3046: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

### HANDLING

In [115]:
df_num = df.select_dtypes(include=["number"])

corr = df_num.corrwith(df_num['HANDLING']).sort_values(ascending=False).dropna()

print(corr.head(50))

HANDLING                                        1.000000
LANDING                                         0.732266
TOTAL DIRECT COSTS                              0.729117
TOTAL DIRECT AND INDIRECT COSTS                 0.727172
TOTAL DIRECT FLIGHT COSTS                       0.722809
TOTAL BO COSTS                                  0.715057
TOTAL DIRECT,INDIRECT,FLEET COSTS               0.714944
TOTAL COSTS                                     0.709631
ASK (000) C CLASS                               0.707095
COCKPIT CREW PERSON                             0.689632
BLOCK HOURS                                     0.686510
FUEL BURN (IN LITER)                            0.683605
CABIN CREW TRAVEL                               0.681485
FLIGHT HOURS                                    0.680105
LEASE AIRCRAFT                                  0.679383
TOTAL INDIRECT COSTS                            0.677698
FUEL AIRCRAFT                                   0.672462
COCKPIT CREW TRAVEL                             0.670379
SEAT OFFERED C CLASS                            0.669681
TOTAL DIRECT TRAFFIC COSTS                      0.668157
ATK (000)                                       0.667801
FLIGHT KILOMETERS                               0.665015
ATK PASSENGER (000)                             0.663103
ASK (000)                                       0.661278
ASK (000) Y CLASS                               0.652467
TOTAL FLEET COST                                0.652284
CABIN CREW PERSON                               0.643155
RPK (000) C CLASS                               0.643028
SEAT OFFERED                                    0.629336
RTK (000)                                       0.626704
INSURANCE                                       0.625488
CATERING                                        0.622467
VARIABLE MAINTENANCE                            0.611552
SEAT OFFERED Y CLASS                            0.606665
RTK PASSENGER (000)                             0.599436
ADMINISTRATION HO                               0.599138
PASSENGER REVENUE NETT (EXCLUDE EBT) C CLASS    0.597404
PASSENGER REVENUE GROSS C CLASS                 0.597355
RPK (000)                                       0.597255
NETT REVENUES                                   0.591731
PASSENGER REVENUE NETT C CLASS                  0.589719
MAINTENANCE RESERVE                             0.585243
RPK (000) Y CLASS                               0.584034
PASSENGER REVENUE NETT                          0.580501
PASSENGER REVENUE GROSS                         0.579856
PASSENGER COMMISSION                            0.578936
PASSENGER CARRIED C CLASS                       0.557756
AIR TRAFFIC CONTROL                             0.557409
PASSENGER REVENUE NETT Y CLASS                  0.542197
PASSENGER REVENUE NETT (EXCLUDE EBT) Y CLASS    0.539889
dtype: float64

c:\Oscar\GDI\ML GI\.venv\Lib\site-packages\numpy\lib\_function_base_impl.py:3045: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
c:\Oscar\GDI\ML GI\.venv\Lib\site-packages\numpy\lib\_function_base_impl.py:3046: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

In [47]:
corr.to_csv("correlation.csv")

### AIR TRAFFIC CONTROL

In [ ]:
df_num = df.select_dtypes(include=["number"])

corr = df_num.corrwith(df_num['AIR TRAFFIC CONTROL']).sort_values(ascending=False).dropna()

print(corr.head(50))

AIR TRAFFIC CONTROL                  1.000000
CABIN CREW PERSON                    0.838056
TOTAL INDIRECT COSTS                 0.834713
LEASE AIRCRAFT                       0.834246
TOTAL FLEET COST                     0.832443
TOTAL DIRECT,INDIRECT,FLEET COSTS    0.829669
TOTAL DIRECT FLIGHT COSTS            0.828713
TOTAL BO COSTS                       0.827855
TOTAL COSTS                          0.824963
TOTAL DIRECT AND INDIRECT COSTS      0.823491
ATK (000)                            0.821873
COCKPIT CREW PERSON                  0.820498
FUEL AIRCRAFT                        0.819637
FUEL BURN (IN LITER)                 0.819141
TOTAL DIRECT COSTS                   0.819099
MAINTENANCE RESERVE                  0.813695
ATK PASSENGER (000)                  0.813386
ASK (000)                            0.813312
CABIN CREW TRAVEL                    0.811941
ASK (000) Y CLASS                    0.807405
ASK (000) C CLASS                    0.801466
FLIGHT KILOMETERS                    0.793545
FLIGHT HOURS                         0.783813
BLOCK HOURS                          0.783321
COCKPIT CREW TRAVEL                  0.775213
RTK (000)                            0.760913
RTK PASSENGER (000)                  0.754567
RPK (000)                            0.754117
RPK (000) Y CLASS                    0.747133
ADMINISTRATION HO                    0.724101
dtype: float64

c:\Oscar\GDI\ML GI\.venv\Lib\site-packages\numpy\lib\_function_base_impl.py:3045: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
c:\Oscar\GDI\ML GI\.venv\Lib\site-packages\numpy\lib\_function_base_impl.py:3046: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

## Cat Corr

In [33]:
def anova_eta_squared(df, cat_col, target_col):
    groups = [
        df[df[cat_col] == cat][target_col].dropna()
        for cat in df[cat_col].dropna().unique()
    ]

    # minimal 2 grup
    if len(groups) < 2:
        return np.nan

    f_stat, p_val = f_oneway(*groups)

    overall_mean = df[target_col].mean()

    ss_between = sum(
        len(g) * (g.mean() - overall_mean) ** 2 for g in groups
    )
    ss_total = sum(
        (df[target_col] - overall_mean) ** 2
    )

    eta_sq = ss_between / ss_total if ss_total != 0 else np.nan

    return eta_sq

In [280]:
df_cat = df.select_dtypes(include=["object"])
categorical_cols  = ['AIRCRAFT TYPE', 
                     'SERVICE TYPE', 
                     'SUB-SERVICE',
                     'ROUNDTRIPROUTE', 
                     'FLIGHT ROUTE', 
                     'AC REG',
                     'QUARTER',
                     'STATUS',
                     'AIRCRAFT TYPE GROUPING',
                     'FLIGHT TYPE',
                     'GA Service', 
                     'Region']
df_cat

,PERIODE,AIRCRAFT TYPE,FLIGHT NUMBER_CITYPAIR,SERVICE TYPE,SUB-SERVICE,ROUNDTRIPROUTE,FLIGHT ROUTE,AC REG,QUARTER,STATUS,AIRCRAFT TYPE GROUPING,FLIGHT TYPE,GA Service,Region
0,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGNR,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
1,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGFJ,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
2,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGNA,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
3,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGNR,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
4,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGMW,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110775,MAY,AC738,GA6054.KDI-UPG.[KDI-UPG],DOM,DOM_4 (UPG),UPG-KDI-UPG,KDI-UPG,PKGUF,Q2,ACTUAL,B738NG,PAX & CARGO,IBT,DOM_EAST
110776,MAY,AC73H,GA2084.CGK-YIA.[CGK-YIA],DOM,DOM_3 (SUB),CGK-YIA-CGK,CGK-YIA,PKGUH,Q2,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
110777,MAY,AC73H,GA2094.YIA-CGK.[YIA-CGK],DOM,DOM_3 (SUB),CGK-YIA-CGK,YIA-CGK,PKGUH,Q2,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
110778,MAY,AC73H,GA4324.CGK-AMI.[CGK-AMI],DOM,DOM_2 (JKT),CGK-AMI-CGK,CGK-AMI,PKGUI,Q2,ACTUAL,B738NG,PAX & CARGO,IBT,DOM_EAST
110779,MAY,AC73H,GA4344.AMI-CGK.[AMI-CGK],DOM,DOM_2 (JKT),CGK-AMI-CGK,AMI-CGK,PKGUI,Q2,ACTUAL,B738NG,PAX & CARGO,IBT,DOM_EAST

### LANDING

In [281]:
anova_results = []

for col in categorical_cols:
    eta = anova_eta_squared(df, col, "LANDING")
    anova_results.append({
        "feature": col,
        "eta_squared": eta
    })

anova_df = pd.DataFrame(anova_results).sort_values(
    "eta_squared", ascending=False
)

anova_df

                   feature  eta_squared
4             FLIGHT ROUTE     0.924902
3           ROUNDTRIPROUTE     0.869027
2              SUB-SERVICE     0.824754
10              GA Service     0.824719
11                  Region     0.719191
1             SERVICE TYPE     0.675900
5                   AC REG     0.635556
0            AIRCRAFT TYPE     0.632864
8   AIRCRAFT TYPE GROUPING     0.627319
6                  QUARTER     0.000327
7                   STATUS          NaN
9              FLIGHT TYPE          NaN

### HANDLING

In [283]:
anova_results = []

for col in categorical_cols:
    eta = anova_eta_squared(df, col, "HANDLING")
    anova_results.append({
        "feature": col,
        "eta_squared": eta
    })

anova_df = pd.DataFrame(anova_results).sort_values(
    "eta_squared", ascending=False
)

anova_df

                   feature  eta_squared
4             FLIGHT ROUTE     0.957647
3           ROUNDTRIPROUTE     0.751808
2              SUB-SERVICE     0.729299
10              GA Service     0.728878
11                  Region     0.645983
1             SERVICE TYPE     0.645716
5                   AC REG     0.533235
0            AIRCRAFT TYPE     0.530681
8   AIRCRAFT TYPE GROUPING     0.525810
6                  QUARTER     0.001016
7                   STATUS          NaN
9              FLIGHT TYPE          NaN

### AIR TRAFFIC CONTROL

In [284]:
anova_results = []

for col in categorical_cols:
    eta = anova_eta_squared(df, col, "AIR TRAFFIC CONTROL")
    anova_results.append({
        "feature": col,
        "eta_squared": eta
    })

anova_df = pd.DataFrame(anova_results).sort_values(
    "eta_squared", ascending=False
)

anova_df

                   feature  eta_squared
4             FLIGHT ROUTE     0.748179
3           ROUNDTRIPROUTE     0.722753
2              SUB-SERVICE     0.646527
10              GA Service     0.646376
5                   AC REG     0.469666
0            AIRCRAFT TYPE     0.457969
8   AIRCRAFT TYPE GROUPING     0.456625
11                  Region     0.397909
1             SERVICE TYPE     0.298846
6                  QUARTER     0.003318
7                   STATUS          NaN
9              FLIGHT TYPE          NaN

# Model

## LANDING

### FITUR

In [ ]:
fitur_num = [ 
    'ASK (000) C CLASS',
    'ASK (000) Y CLASS',
    'SEAT OFFERED C CLASS',
    'ATK PASSENGER (000)',
    'ASK (000)',            
    'ATK (000)', 
    'SEAT OFFERED',
    'BLOCK HOURS',          
    'FLIGHT KILOMETERS',       
]

fitur_cat = [
    'AIRCRAFT TYPE GROUPING',
    'AIRCRAFT TYPE',        
    'SERVICE TYPE',         
    'ROUNDTRIPROUTE', 
    'FLIGHT ROUTE', 
    'AC REG',
    'Region'
]

fitur = fitur_num + fitur_cat

In [268]:
# fitur_num = [
#     'FLIGHT KILOMETERS',    
#     'ATK (000)', 
#     'SEAT OFFERED',
#     'ATK PASSENGER (000)',    
# ]

# fitur_cat = [
#     'AIRCRAFT TYPE',        
#     'FLIGHT ROUTE', 
# ]

# fitur = fitur_num + fitur_cat

In [269]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import mean_absolute_percentage_error, mean_absolute_error, r2_score
from xgboost import XGBRegressor

In [270]:
def train_model(target_name, df_data,fitur,fitur_cat):
    print(f"--- TRAINING MODEL FOR: {target_name} ---")
    
    data = df_data[df_data[target_name] > 0].copy()
    
    X = data[fitur]
    y = data[target_name]
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    categorical_cols = fitur_cat
    numeric_cols = list(set(fitur) - set(categorical_cols))
    
    encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
    encoder.fit(X_train[categorical_cols])
    
    X_train_enc = encoder.transform(X_train[categorical_cols])
    X_test_enc = encoder.transform(X_test[categorical_cols])
    enc_cols = encoder.get_feature_names_out(categorical_cols)
    
    X_train_final = pd.concat([
        X_train[numeric_cols].reset_index(drop=True),
        pd.DataFrame(X_train_enc, columns=enc_cols)
    ], axis=1)
    
    X_test_final = pd.concat([
        X_test[numeric_cols].reset_index(drop=True),
        pd.DataFrame(X_test_enc, columns=enc_cols)
    ], axis=1)
    
    model = XGBRegressor(
        n_estimators=500,
        max_depth=6,
        learning_rate=0.05,
        n_jobs=-1,
        objective="reg:absoluteerror" 
    )
    
    model.fit(X_train_final, y_train)
    y_pred = model.predict(X_test_final)
    
    # Evaluasi
    mape = mean_absolute_percentage_error(y_test, y_pred)

    print(f"MAPE: {mape:.4f} ({mape*100:.2f}%)")
    
    return model, encoder, X_test_final, y_test, y_pred

In [271]:
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_percentage_error
import pandas as pd
from tqdm import tqdm

def backward_feature_elimination(target_name, df_data, fitur, fitur_cat, tol=0.005, n_estimators=500):
    """
    Backward Feature Elimination untuk XGBoost dengan progress bar
    """
    # --- Data split ---
    data = df_data[df_data[target_name] > 0].copy()
    X = data[fitur]
    y = data[target_name]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    # --- Encode categorical ---
    if fitur_cat:
        categorical_cols = fitur_cat
        numeric_cols = list(set(fitur) - set(categorical_cols))
        
        encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
        encoder.fit(X_train[categorical_cols])
        
        X_train_enc = encoder.transform(X_train[categorical_cols])
        X_test_enc = encoder.transform(X_test[categorical_cols])
        enc_cols = encoder.get_feature_names_out(categorical_cols)
        
        X_train_final = pd.concat([
            X_train[numeric_cols].reset_index(drop=True),
            pd.DataFrame(X_train_enc, columns=enc_cols)
        ], axis=1)
        
        X_test_final = pd.concat([
            X_test[numeric_cols].reset_index(drop=True),
            pd.DataFrame(X_test_enc, columns=enc_cols)
        ], axis=1)
    else:
        X_train_final = X_train.copy()
        X_test_final = X_test.copy()
    
    
    # --- Full model ---
    model_full = XGBRegressor(
        n_estimators=n_estimators, max_depth=6, learning_rate=0.05, n_jobs=-1,
        objective="reg:absoluteerror"
    )
    model_full.fit(X_train_final, y_train)
    y_pred_full = model_full.predict(X_test_final)
    mape_full = mean_absolute_percentage_error(y_test, y_pred_full)
    print(f"Full model MAPE: {mape_full:.4f}")
    
    # --- Backward elimination dengan tqdm ---
    features = list(X_train_final.columns)
    best_features = features.copy()
    
    # fitur asli = numeric + categorical
    original_features = fitur_num + fitur_cat   # 10 numeric + 7 categorical = 17
    best_original_features = original_features.copy()

    for feat in tqdm(original_features, desc="Backward Elimination", unit="feat"):
        print(feat)
        # jika feat kategorikal → hapus semua kolom hasil encoding untuk fitur ini
        if feat in fitur_cat:
            cols_to_remove = [c for c in best_features if c.startswith(feat)]
        else:
            cols_to_remove = [feat]
        
        temp_features = [f for f in best_features if f not in cols_to_remove]
        
        # ... training model sama seperti sebelumnya

        model = XGBRegressor(
            n_estimators=n_estimators, max_depth=6, learning_rate=0.05, n_jobs=-1,
            objective="reg:absoluteerror"
        )
        model.fit(X_train_final[temp_features], y_train)
        y_pred = model.predict(X_test_final[temp_features])
        mape = mean_absolute_percentage_error(y_test, y_pred)

        
        if (abs(mape - mape_full) <= tol) or (mape <= mape_full):
            print("remove")
            best_original_features.remove(feat)
            for col in cols_to_remove:
                best_features.remove(col)

        print(f"MAPE: {mape:.4f} ({mape*100:.2f}%)")
        print(f"MAPE full: {mape_full:.4f} ({mape_full*100:.2f}%)\n")
        
    
    print(f"\nFinal features ({len(best_original_features)}): {best_original_features}")
    
    # --- Train final model full trees ---
    final_model = XGBRegressor(
        n_estimators=2000, max_depth=6, learning_rate=0.05, n_jobs=-1,
        objective="reg:absoluteerror"
    )
    final_model.fit(X_train_final[best_features], y_train)
    
    return final_model, best_original_features, X_test_final[best_features], y_test, y_pred_full

In [272]:
model_bfe, features_bfe, X_test_bfe, y_test_bfe, y_pred_full = backward_feature_elimination(
    target_name="LANDING",
    df_data=df1,
    fitur=fitur,
    fitur_cat=fitur_cat,
    tol=0.005,       # MAPE ±0.5%
    n_estimators=2000 # pakai lebih sedikit trees saat seleksi
)

Full model MAPE: 0.0949

Backward Elimination:   0%|          | 0/16 [00:00<?, ?feat/s]

BLOCK HOURS

Backward Elimination:   6%|▋         | 1/16 [00:56<14:11, 56.75s/feat]

remove
MAPE: 0.0995 (9.95%)
MAPE full: 0.0949 (9.49%)

FLIGHT KILOMETERS

Backward Elimination:  12%|█▎        | 2/16 [01:53<13:12, 56.61s/feat]

MAPE: 0.1000 (10.00%)
MAPE full: 0.0949 (9.49%)

ASK (000)

Backward Elimination:  19%|█▉        | 3/16 [02:52<12:28, 57.60s/feat]

MAPE: 0.1089 (10.89%)
MAPE full: 0.0949 (9.49%)

ATK (000)

Backward Elimination:  25%|██▌       | 4/16 [03:51<11:38, 58.17s/feat]

MAPE: 0.1163 (11.63%)
MAPE full: 0.0949 (9.49%)

SEAT OFFERED

Backward Elimination:  31%|███▏      | 5/16 [04:50<10:46, 58.74s/feat]

MAPE: 0.1001 (10.01%)
MAPE full: 0.0949 (9.49%)

ASK (000) C CLASS

Backward Elimination:  38%|███▊      | 6/16 [05:48<09:43, 58.34s/feat]

MAPE: 0.1042 (10.42%)
MAPE full: 0.0949 (9.49%)

ASK (000) Y CLASS

Backward Elimination:  44%|████▍     | 7/16 [06:45<08:42, 58.05s/feat]

MAPE: 0.1010 (10.10%)
MAPE full: 0.0949 (9.49%)

SEAT OFFERED C CLASS

Backward Elimination:  50%|█████     | 8/16 [07:43<07:42, 57.77s/feat]

remove
MAPE: 0.0955 (9.55%)
MAPE full: 0.0949 (9.49%)

ATK PASSENGER (000)

Backward Elimination:  56%|█████▋    | 9/16 [08:43<06:50, 58.64s/feat]

MAPE: 0.1333 (13.33%)
MAPE full: 0.0949 (9.49%)

AIRCRAFT TYPE GROUPING

Backward Elimination:  62%|██████▎   | 10/16 [09:41<05:49, 58.29s/feat]

remove
MAPE: 0.0994 (9.94%)
MAPE full: 0.0949 (9.49%)

AIRCRAFT TYPE

Backward Elimination:  69%|██████▉   | 11/16 [10:38<04:49, 57.90s/feat]

MAPE: 0.1037 (10.37%)
MAPE full: 0.0949 (9.49%)

SERVICE TYPE

Backward Elimination:  75%|███████▌  | 12/16 [11:38<03:54, 58.54s/feat]

MAPE: 0.1008 (10.08%)
MAPE full: 0.0949 (9.49%)

ROUNDTRIPROUTE

Backward Elimination:  81%|████████▏ | 13/16 [12:32<02:51, 57.17s/feat]

remove
MAPE: 0.0976 (9.76%)
MAPE full: 0.0949 (9.49%)

FLIGHT ROUTE

Backward Elimination:  88%|████████▊ | 14/16 [13:19<01:48, 54.09s/feat]

MAPE: 0.1574 (15.74%)
MAPE full: 0.0949 (9.49%)

AC REG

Backward Elimination:  94%|█████████▍| 15/16 [14:15<00:54, 54.91s/feat]

MAPE: 0.1194 (11.94%)
MAPE full: 0.0949 (9.49%)

Region

Backward Elimination: 100%|██████████| 16/16 [15:12<00:00, 57.05s/feat]

remove
MAPE: 0.0993 (9.93%)
MAPE full: 0.0949 (9.49%)


Final features (11): ['FLIGHT KILOMETERS', 'ASK (000)', 'ATK (000)', 'SEAT OFFERED', 'ASK (000) C CLASS', 'ASK (000) Y CLASS', 'ATK PASSENGER (000)', 'AIRCRAFT TYPE', 'SERVICE TYPE', 'FLIGHT ROUTE', 'AC REG']

In [273]:
model_landing, features_landing, X_test_landing, y_test_landing, y_pred_landing = model_bfe, features_bfe, X_test_bfe, y_test_bfe, y_pred_full

In [274]:
print("\nLANDING")
results_landing = pd.DataFrame({'Actual': y_test_landing.values, 'Predicted': y_pred_landing})
results_landing['Diff'] = results_landing['Actual'] - results_landing['Predicted']
print(results_landing.head())

LANDING
       Actual   Predicted       Diff
0  122.290000  127.284172  -4.994172
1   25.160000   32.865105  -7.705105
2   44.274500   45.589096  -1.314596
3   59.060667   47.715752  11.344915
4   50.451207   44.169388   6.281819

## HANDLING

### FITUR

In [275]:
fitur_num = [
    'BLOCK HOURS',          
    'FLIGHT KILOMETERS',    
    'ASK (000)',            
    'ATK (000)', 
    'SEAT OFFERED',
    'ASK (000) C CLASS',
    'ASK (000) Y CLASS',
    'SEAT OFFERED C CLASS',
    'ATK PASSENGER (000)',
    'SEAT OFFERED Y CLASS'    
]

fitur_cat = [
    'AIRCRAFT TYPE GROUPING',
    'AIRCRAFT TYPE',
    'SUB-SERVICE',           
    'SERVICE TYPE',
    'ROUNDTRIPROUTE', 
    'FLIGHT ROUTE',
    'GA Service',
    'AC REG',
    'Region'
]

fitur = fitur_num + fitur_cat

In [276]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import mean_absolute_percentage_error, mean_absolute_error, r2_score
from xgboost import XGBRegressor

In [277]:
def train_model(target_name, df_data,fitur,fitur_cat):
    print(f"--- TRAINING MODEL FOR: {target_name} ---")
    
    data = df_data[df_data[target_name] > 0].copy()
    
    X = data[fitur]
    y = data[target_name]
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    categorical_cols = fitur_cat
    numeric_cols = list(set(fitur) - set(categorical_cols))
    
    encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
    encoder.fit(X_train[categorical_cols])
    
    X_train_enc = encoder.transform(X_train[categorical_cols])
    X_test_enc = encoder.transform(X_test[categorical_cols])
    enc_cols = encoder.get_feature_names_out(categorical_cols)
    
    X_train_final = pd.concat([
        X_train[numeric_cols].reset_index(drop=True),
        pd.DataFrame(X_train_enc, columns=enc_cols)
    ], axis=1)
    
    X_test_final = pd.concat([
        X_test[numeric_cols].reset_index(drop=True),
        pd.DataFrame(X_test_enc, columns=enc_cols)
    ], axis=1)
    
    model = XGBRegressor(
        n_estimators=500,
        max_depth=6,
        learning_rate=0.05,
        n_jobs=-1,
        objective="reg:absoluteerror" 
    )
    
    model.fit(X_train_final, y_train)
    y_pred = model.predict(X_test_final)
    
    # Evaluasi
    mape = mean_absolute_percentage_error(y_test, y_pred)

    print(f"MAPE: {mape:.4f} ({mape*100:.2f}%)")
    
    return model, encoder, X_test_final, y_test, y_pred

In [278]:
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_percentage_error
import pandas as pd
from tqdm import tqdm

def backward_feature_elimination(target_name, df_data, fitur, fitur_cat, tol=0.005, n_estimators=500):
    """
    Backward Feature Elimination untuk XGBoost dengan progress bar
    """
    # --- Data split ---
    data = df_data[df_data[target_name] > 0].copy()
    X = data[fitur]
    y = data[target_name]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    # --- Encode categorical ---
    if fitur_cat:
        categorical_cols = fitur_cat
        numeric_cols = list(set(fitur) - set(categorical_cols))
        
        encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
        encoder.fit(X_train[categorical_cols])
        
        X_train_enc = encoder.transform(X_train[categorical_cols])
        X_test_enc = encoder.transform(X_test[categorical_cols])
        enc_cols = encoder.get_feature_names_out(categorical_cols)
        
        X_train_final = pd.concat([
            X_train[numeric_cols].reset_index(drop=True),
            pd.DataFrame(X_train_enc, columns=enc_cols)
        ], axis=1)
        
        X_test_final = pd.concat([
            X_test[numeric_cols].reset_index(drop=True),
            pd.DataFrame(X_test_enc, columns=enc_cols)
        ], axis=1)
    else:
        X_train_final = X_train.copy()
        X_test_final = X_test.copy()
    
    
    # --- Full model ---
    model_full = XGBRegressor(
        n_estimators=n_estimators, max_depth=6, learning_rate=0.05, n_jobs=-1,
        objective="reg:absoluteerror"
    )
    model_full.fit(X_train_final, y_train)
    y_pred_full = model_full.predict(X_test_final)
    mape_full = mean_absolute_percentage_error(y_test, y_pred_full)
    print(f"Full model MAPE: {mape_full:.4f}")
    
    # --- Backward elimination dengan tqdm ---
    features = list(X_train_final.columns)
    best_features = features.copy()
    
    # fitur asli = numeric + categorical
    original_features = fitur_num + fitur_cat   # 10 numeric + 7 categorical = 17
    best_original_features = original_features.copy()

    for feat in tqdm(original_features, desc="Backward Elimination", unit="feat"):
        print(feat)
        # jika feat kategorikal → hapus semua kolom hasil encoding untuk fitur ini
        if feat in fitur_cat:
            cols_to_remove = [c for c in best_features if c.startswith(feat)]
        else:
            cols_to_remove = [feat]
        
        temp_features = [f for f in best_features if f not in cols_to_remove]
        
        # ... training model sama seperti sebelumnya

        model = XGBRegressor(
            n_estimators=n_estimators, max_depth=6, learning_rate=0.05, n_jobs=-1,
            objective="reg:absoluteerror"
        )
        model.fit(X_train_final[temp_features], y_train)
        y_pred = model.predict(X_test_final[temp_features])
        mape = mean_absolute_percentage_error(y_test, y_pred)

        
        if (abs(mape - mape_full) <= tol) or (mape <= mape_full):
            print("remove")
            best_original_features.remove(feat)
            for col in cols_to_remove:
                best_features.remove(col)

        print(f"MAPE: {mape:.4f} ({mape*100:.2f}%)")
        print(f"MAPE full: {mape_full:.4f} ({mape_full*100:.2f}%)\n")
        
    
    print(f"\nFinal features ({len(best_original_features)}): {best_original_features}")
    
    # --- Train final model full trees ---
    final_model = XGBRegressor(
        n_estimators=2000, max_depth=6, learning_rate=0.05, n_jobs=-1,
        objective="reg:absoluteerror"
    )
    final_model.fit(X_train_final[best_features], y_train)
    
    return final_model, best_original_features, X_test_final[best_features], y_test, y_pred_full

In [279]:
model_handling, features_handling, X_test_handling, y_test_handling, y_pred_handling = backward_feature_elimination(
    target_name="HANDLING",
    df_data=df1,
    fitur=fitur,
    fitur_cat=fitur_cat,
    tol=0.005,       # MAPE ±0.5%
    n_estimators=2000 # pakai lebih sedikit trees saat seleksi
)

Full model MAPE: 0.0645

Backward Elimination:   0%|          | 0/19 [00:00<?, ?feat/s]

BLOCK HOURS

Backward Elimination:   5%|▌         | 1/19 [01:01<18:24, 61.35s/feat]

remove
MAPE: 0.0660 (6.60%)
MAPE full: 0.0645 (6.45%)

FLIGHT KILOMETERS

Backward Elimination:  11%|█         | 2/19 [01:59<16:51, 59.49s/feat]

remove
MAPE: 0.0663 (6.63%)
MAPE full: 0.0645 (6.45%)

ASK (000)

Backward Elimination:  16%|█▌        | 3/19 [02:56<15:33, 58.37s/feat]

remove
MAPE: 0.0685 (6.85%)
MAPE full: 0.0645 (6.45%)

ATK (000)

Backward Elimination:  21%|██        | 4/19 [03:53<14:27, 57.84s/feat]

MAPE: 0.0725 (7.25%)
MAPE full: 0.0645 (6.45%)

SEAT OFFERED

Backward Elimination:  26%|██▋       | 5/19 [04:49<13:21, 57.25s/feat]

remove
MAPE: 0.0690 (6.90%)
MAPE full: 0.0645 (6.45%)

ASK (000) C CLASS

Backward Elimination:  32%|███▏      | 6/19 [05:46<12:22, 57.15s/feat]

remove
MAPE: 0.0677 (6.77%)
MAPE full: 0.0645 (6.45%)

ASK (000) Y CLASS

Backward Elimination:  37%|███▋      | 7/19 [06:41<11:17, 56.46s/feat]

remove
MAPE: 0.0680 (6.80%)
MAPE full: 0.0645 (6.45%)

SEAT OFFERED C CLASS

Backward Elimination:  42%|████▏     | 8/19 [07:36<10:14, 55.88s/feat]

remove
MAPE: 0.0667 (6.67%)
MAPE full: 0.0645 (6.45%)

ATK PASSENGER (000)

Backward Elimination:  47%|████▋     | 9/19 [08:33<09:21, 56.13s/feat]

MAPE: 0.0835 (8.35%)
MAPE full: 0.0645 (6.45%)

SEAT OFFERED Y CLASS

Backward Elimination:  53%|█████▎    | 10/19 [09:30<08:27, 56.39s/feat]

remove
MAPE: 0.0674 (6.74%)
MAPE full: 0.0645 (6.45%)

AIRCRAFT TYPE GROUPING

Backward Elimination:  58%|█████▊    | 11/19 [10:27<07:34, 56.84s/feat]

remove
MAPE: 0.0676 (6.76%)
MAPE full: 0.0645 (6.45%)

AIRCRAFT TYPE

Backward Elimination:  58%|█████▊    | 11/19 [11:13<08:09, 61.19s/feat]

KeyboardInterrupt:

In [ ]:
print("\nHANDLING")
results_handling = pd.DataFrame({'Actual': y_test_handling.values, 'Predicted': y_pred_handling})
results_handling['Diff'] = results_handling['Actual'] - results_handling['Predicted']
print(results_handling.head())

COCKPIT CREW TRAVEL
       Actual   Predicted       Diff
0  182.585041  156.679657  25.905384
1  106.171559  119.615593 -13.444034
2  184.391236  184.417679  -0.026442
3  128.758906  129.485184  -0.726277
4  126.732800  123.699890   3.032910

COCKPIT CREW TRAVEL
       Actual   Predicted       Diff
0  395.460020  386.801361   8.658659
1  161.768471  173.225525 -11.457054
2  268.813794  277.358032  -8.544238
3  138.513795  134.575378   3.938417
4  157.169144  160.428909  -3.259765

## AIR TRAFFIC CONTROL

### FITUR

In [ ]:
fitur_num = [
    'BLOCK HOURS',          
    'FLIGHT KILOMETERS',    
    'ASK (000)',            
    'ATK (000)', 
    'SEAT OFFERED',
    'ASK (000) C CLASS',
    'ASK (000) Y CLASS',
    'SEAT OFFERED C CLASS',
    'ATK PASSENGER (000)',    
]

fitur_cat = [
    'AIRCRAFT TYPE GROUPING',
    'AIRCRAFT TYPE',        
    'SERVICE TYPE',
    'SUB-SERVICE',         
    'ROUNDTRIPROUTE', 
    'FLIGHT ROUTE', 
    'AC REG',
    'Region',
    'GA Service'
]

fitur = fitur_num + fitur_cat

In [ ]:
# fitur_num = [
#     'FLIGHT KILOMETERS',    
#     'ATK (000)', 
#     'SEAT OFFERED',
#     'ATK PASSENGER (000)',    
# ]

# fitur_cat = [
#     'AIRCRAFT TYPE',        
#     'FLIGHT ROUTE', 
# ]

# fitur = fitur_num + fitur_cat

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import mean_absolute_percentage_error, mean_absolute_error, r2_score
from xgboost import XGBRegressor

In [ ]:
def train_model(target_name, df_data,fitur,fitur_cat):
    print(f"--- TRAINING MODEL FOR: {target_name} ---")
    
    data = df_data[df_data[target_name] > 0].copy()
    
    X = data[fitur]
    y = data[target_name]
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    categorical_cols = fitur_cat
    numeric_cols = list(set(fitur) - set(categorical_cols))
    
    encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
    encoder.fit(X_train[categorical_cols])
    
    X_train_enc = encoder.transform(X_train[categorical_cols])
    X_test_enc = encoder.transform(X_test[categorical_cols])
    enc_cols = encoder.get_feature_names_out(categorical_cols)
    
    X_train_final = pd.concat([
        X_train[numeric_cols].reset_index(drop=True),
        pd.DataFrame(X_train_enc, columns=enc_cols)
    ], axis=1)
    
    X_test_final = pd.concat([
        X_test[numeric_cols].reset_index(drop=True),
        pd.DataFrame(X_test_enc, columns=enc_cols)
    ], axis=1)
    
    model = XGBRegressor(
        n_estimators=500,
        max_depth=6,
        learning_rate=0.05,
        n_jobs=-1,
        objective="reg:absoluteerror" 
    )
    
    model.fit(X_train_final, y_train)
    y_pred = model.predict(X_test_final)
    
    # Evaluasi
    mape = mean_absolute_percentage_error(y_test, y_pred)

    print(f"MAPE: {mape:.4f} ({mape*100:.2f}%)")
    
    return model, encoder, X_test_final, y_test, y_pred

In [ ]:
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_percentage_error
import pandas as pd
from tqdm import tqdm

def backward_feature_elimination(target_name, df_data, fitur, fitur_cat, tol=0.005, n_estimators=500):
    """
    Backward Feature Elimination untuk XGBoost dengan progress bar
    """
    # --- Data split ---
    data = df_data[df_data[target_name] > 0].copy()
    X = data[fitur]
    y = data[target_name]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    # --- Encode categorical ---
    if fitur_cat:
        categorical_cols = fitur_cat
        numeric_cols = list(set(fitur) - set(categorical_cols))
        
        encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
        encoder.fit(X_train[categorical_cols])
        
        X_train_enc = encoder.transform(X_train[categorical_cols])
        X_test_enc = encoder.transform(X_test[categorical_cols])
        enc_cols = encoder.get_feature_names_out(categorical_cols)
        
        X_train_final = pd.concat([
            X_train[numeric_cols].reset_index(drop=True),
            pd.DataFrame(X_train_enc, columns=enc_cols)
        ], axis=1)
        
        X_test_final = pd.concat([
            X_test[numeric_cols].reset_index(drop=True),
            pd.DataFrame(X_test_enc, columns=enc_cols)
        ], axis=1)
    else:
        X_train_final = X_train.copy()
        X_test_final = X_test.copy()
    
    
    # --- Full model ---
    model_full = XGBRegressor(
        n_estimators=n_estimators, max_depth=6, learning_rate=0.05, n_jobs=-1,
        objective="reg:absoluteerror"
    )
    model_full.fit(X_train_final, y_train)
    y_pred_full = model_full.predict(X_test_final)
    mape_full = mean_absolute_percentage_error(y_test, y_pred_full)
    print(f"Full model MAPE: {mape_full:.4f}")
    
    # --- Backward elimination dengan tqdm ---
    features = list(X_train_final.columns)
    best_features = features.copy()
    
    # fitur asli = numeric + categorical
    original_features = fitur_num + fitur_cat   # 10 numeric + 7 categorical = 17
    best_original_features = original_features.copy()

    for feat in tqdm(original_features, desc="Backward Elimination", unit="feat"):
        print(feat)
        # jika feat kategorikal → hapus semua kolom hasil encoding untuk fitur ini
        if feat in fitur_cat:
            cols_to_remove = [c for c in best_features if c.startswith(feat)]
        else:
            cols_to_remove = [feat]
        
        temp_features = [f for f in best_features if f not in cols_to_remove]
        
        # ... training model sama seperti sebelumnya

        model = XGBRegressor(
            n_estimators=n_estimators, max_depth=6, learning_rate=0.05, n_jobs=-1,
            objective="reg:absoluteerror"
        )
        model.fit(X_train_final[temp_features], y_train)
        y_pred = model.predict(X_test_final[temp_features])
        mape = mean_absolute_percentage_error(y_test, y_pred)

        
        if (abs(mape - mape_full) <= tol) or (mape <= mape_full):
            print("remove")
            best_original_features.remove(feat)
            for col in cols_to_remove:
                best_features.remove(col)

        print(f"MAPE: {mape:.4f} ({mape*100:.2f}%)")
        print(f"MAPE full: {mape_full:.4f} ({mape_full*100:.2f}%)\n")
        
    
    print(f"\nFinal features ({len(best_original_features)}): {best_original_features}")
    
    # --- Train final model full trees ---
    final_model = XGBRegressor(
        n_estimators=2000, max_depth=6, learning_rate=0.05, n_jobs=-1,
        objective="reg:absoluteerror"
    )
    final_model.fit(X_train_final[best_features], y_train)
    
    return final_model, best_original_features, X_test_final[best_features], y_test, y_pred_full

In [ ]:
model_atc, features_atc, X_test_atc, y_test_atc, y_pred_atc = backward_feature_elimination(
    target_name="atc",
    df_data=df1,
    fitur=fitur,
    fitur_cat=fitur_cat,
    tol=0.005,       # MAPE ±0.5%
    n_estimators=2000 # pakai lebih sedikit trees saat seleksi
)

Full model MAPE: 0.0949

Backward Elimination:   0%|          | 0/16 [00:00<?, ?feat/s]

BLOCK HOURS

Backward Elimination:   6%|▋         | 1/16 [01:04<16:05, 64.39s/feat]

remove
MAPE: 0.0995 (9.95%)
MAPE full: 0.0949 (9.49%)

FLIGHT KILOMETERS

Backward Elimination:  12%|█▎        | 2/16 [02:06<14:40, 62.92s/feat]

MAPE: 0.1000 (10.00%)
MAPE full: 0.0949 (9.49%)

ASK (000)

Backward Elimination:  19%|█▉        | 3/16 [03:07<13:30, 62.35s/feat]

MAPE: 0.1089 (10.89%)
MAPE full: 0.0949 (9.49%)

ATK (000)

Backward Elimination:  25%|██▌       | 4/16 [04:09<12:24, 62.06s/feat]

MAPE: 0.1163 (11.63%)
MAPE full: 0.0949 (9.49%)

SEAT OFFERED

Backward Elimination:  31%|███▏      | 5/16 [05:10<11:16, 61.47s/feat]

MAPE: 0.1001 (10.01%)
MAPE full: 0.0949 (9.49%)

ASK (000) C CLASS

In [ ]:
print("\nATC")
results_atc = pd.DataFrame({'Actual': y_test_atc.values, 'Predicted': y_pred_atc})
results_atc['Diff'] = results_atc['Actual'] - results_atc['Predicted']
print(results_atc.head())

COCKPIT CREW TRAVEL
       Actual   Predicted       Diff
0  182.585041  156.679657  25.905384
1  106.171559  119.615593 -13.444034
2  184.391236  184.417679  -0.026442
3  128.758906  129.485184  -0.726277
4  126.732800  123.699890   3.032910

COCKPIT CREW TRAVEL
       Actual   Predicted       Diff
0  395.460020  386.801361   8.658659
1  161.768471  173.225525 -11.457054
2  268.813794  277.358032  -8.544238
3  138.513795  134.575378   3.938417
4  157.169144  160.428909  -3.259765