In [13]:
import pandas as pd
import pandas as pd

# Tampilkan semua kolom tanpa terpotong
pd.set_option('display.max_columns', None)

In [25]:
df = pd.read_excel("05. Database RP May 2025 - AC REGISTER.xlsx")
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114,Unnamed: 115,Unnamed: 116,Unnamed: 117,Unnamed: 118,Unnamed: 119,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129,Unnamed: 130,Unnamed: 131,Unnamed: 132,Unnamed: 133,Unnamed: 134,Unnamed: 135,Unnamed: 136,Unnamed: 137,Unnamed: 138,Unnamed: 139,Unnamed: 140,Unnamed: 141,Unnamed: 142,Unnamed: 143,Unnamed: 144,Unnamed: 145
0,NaN,YEAR,PERIODE,AIRCRAFT TYPE,FLIGHT NUMBER_CITYPAIR,SERVICE TYPE,SUB-SERVICE,ROUNDTRIPROUTE,FLIGHT ROUTE,AC REG,DATE,PASSENGER REVENUE GROSS,EXCESS BAGGAGE REVENUE,PASSENGER REVENUE DISCOUNT,PASSENGER REVENUE NETT,FREIGHT REVENUE GROSS,FREIGHT REVENUE DISCOUNT,FREIGHT REVENUE NETT,MAIL REVENUE,OTHER REVENUE,NETT REVENUES,COSTS :,DIRECT COSTS :,DIRECT TRAFFIC COSTS :,PASSENGER COMMISSION,FREIGHT COMMISSION,CREDIT CARD COMMISSION,CATERING,ON BOARD SERVICE,RESERVATION,TOTAL DIRECT TRAFFIC COSTS,DIRECT FLIGHT COSTS :,FUEL AIRCRAFT,LANDING,HANDLING,AIR TRAFFIC CONTROL,COCKPIT CREW TRAVEL,CABIN CREW TRAVEL,VARIABLE MAINTENANCE,TOTAL DIRECT FLIGHT COSTS,TOTAL DIRECT COSTS,CONTRIBUTION MARGIN 1,INDIRECT COSTS :,COCKPIT CREW PERSON,CABIN CREW PERSON,AIRCRAFT MAINTENANCE,TOTAL INDIRECT COSTS,TOTAL DIRECT AND INDIRECT COSTS,CONTRIBUTION MARGIN 2,DEPRECIATION AIRCRAFT,LEASE AIRCRAFT,INSURANCE,MAINTENANCE RESERVE,TOTAL FLEET COST,"TOTAL DIRECT,INDIRECT,FLEET COSTS",CONTRIBUTION MARGIN 3,STATION,SALES ORGANIZATION,MARKETING,ADMINISTRATION BO,TOTAL OVERHEAD COST BO,TOTAL BO COSTS,ROUTE RESULT PERFORMANCE BO,ADMINISTRATION HO,TOTAL COSTS,ROUTE RESULT 1,ADJUSTMENT,ROUTE RESULT 2,FLIGHT ROUTES,NUMBER OF LANDING,BLOCK HOURS,FLIGHT HOURS,FLIGHT KILOMETERS,ATK (000),FUEL BURN (IN LITER),SEAT OFFERED,PASSENGER CARRIED,ASK (000),RPK (000),SLF (%),FREIGHT CARRIED,MAIL CARRIED,CARGO CARRIED,RTK FREIGHT (000),RTK MAIL (000),RTK CARGO (000),RTK PASSENGER (000),RTK (000),ATK CARGO (000),ATK CARGO GF (000),ATK FREIGHT GF (000),ATK MAIL GF (000),ATK PASSENGER (000),CLF (%),CLF-GF (%),LOAD FACTOR (%),BREAK EVEN LF (%),BREAK EVEN SLF-RR1 (%),NETT REVENUE/ATK (USC),NETT REVENUE/ASK (USC),PAX YIELD (USC),FREIGHT YIELD (USC),MAIL YIELD (USC),CARGO YIELD (USC),COST/ASK RR 1 (USC),COST/ASK EXCFUEL-RR1,COST PER RPK (USC),COST PER ATK (USC),COST/BLOCKHOURS,MARGIN/ASK RR 1(USC),AVERAGE FUEL PRICE,PROFIT MARGIN (%),COST COVERAGE (%),AVERAGE STAGE LENGTH,PASSENGER REVENUE GROSS F CLASS,PASSENGER REVENUE GROSS C CLASS,PASSENGER REVENUE GROSS Y CLASS,PASSENGER REVENUE DISCOUNT F CLASS,PASSENGER REVENUE DISCOUNT C CLASS,PASSENGER REVENUE DISCOUNT Y CLASS,PASSENGER REVENUE NETT F CLASS,PASSENGER REVENUE NETT C CLASS,PASSENGER REVENUE NETT Y CLASS,PASSENGER REVENUE NETT (EXCLUDE EBT) F CLASS,PASSENGER REVENUE NETT (EXCLUDE EBT) C CLASS,PASSENGER REVENUE NETT (EXCLUDE EBT) Y CLASS,SEAT OFFERED F CLASS,SEAT OFFERED C CLASS,SEAT OFFERED Y CLASS,PASSENGER CARRIED F CLASS,PASSENGER CARRIED C CLASS,PASSENGER CARRIED Y CLASS,ASK (000) F CLASS,ASK (000) C CLASS,ASK (000) Y CLASS,RPK (000) F CLASS,RPK (000) C CLASS,RPK (000) Y CLASS,OTHER REVENUE PASSENGER,OTHER REVENUE FREIGHT,QUARTER,STATUS,AIRCRAFT TYPE GROUPING,FLIGHT TYPE,GA Service,Region
1,NaN,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGNR,30012024,4097.39336,41.899458,0.706168,4138.58665,4.33,0,4.33,0,383.531648,4526.448297,NaN,NaN,NaN,146.331215,0.252392,13.765684,363.075018,0.990068,408.315673,932.73005,NaN,1256.095846,30.289484,358.895323,154.756355,77.115384,93.222903,239.000762,2209.376056,3142.106106,1384.342191,NaN,299.002595,46.533742,14.305586,359.841923,3501.948029,1024.500268,254.956363,661.655443,14.989873,454.143155,1385.744834,4887.692863,-361.244566,31.192382,5.614019,0.128285,18.941017,55.875704,4943.568567,-417.12027,122.408937,5065.977504,-539.529207,39.744139,-579.273346,1,1,0.733333,0.383333,191,3.638548,1747,162,151,30.942,28.841,93.209877,9,0,9,0.001719,0,0.001719,2.79757,2.821526,0.637419,0.553912,0.553903,0.553903,3.000871,0.269701,0.310361,77.545362,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,57.686882,4165.471873,0,0.0001,0.706067,0,57.686482,4215.173124,0,57.686875,4164.620068,0,12,150,0,3,148,0,2.292,28.65,0,0.573,28.268,382.16466,1.366988,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
2,NaN,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGFJ,31012024,4580.064734,46.835198,0.789354,4626.110578,47.76,0,47.76,0,442.261415,5116.131993,NaN,NaN,NaN,163.568976,2.783893,15.531319,363.075018,0.990068,461.509055,1007.458329,NaN,1547.291506,30.289484,358.895323,154.756355,92.312743,93.222903,315.046459,2591.814772,3599.2731,1516.858893,NaN,388.627069,46.533742,18.857364,454.018174,4053.291275,1062.840718,336.078842,872.182175,16.942681,612.105992,1837.309689,5890.600964,-774.468971,35.255974,6.345386,0.144997,21.408561,63.154919,5953.755883,-837.62389,138.355779,6092.111662,-975.979669,47.794474,-1023.774143,1,1,0.966667,0.516667,191,3.638548,2152,162,151,30.942,28.841,93.209877,123,0,123,0.023495,0,0.023495,2.79757,2.843474,0.637419,0.553912,0.553903,0.553903,3.000871,3.685911,4.241598,78.148585,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,759.890061,3976.008816,0,0.000112,0.789242,0,759.884803,4023.449447,0,759.889973,3975.195755,0,12,150,0,5,146,0,2.292,28.65,0,0.955,27.886,427.183511,15.077904,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
3,NaN,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGNA,01012024,5248.905413,53.674683,0.904626,5301.67547,151.53,0,151.53,0,537.404658,5990.610128,NaN,NaN,NaN,187.455447,8.832565,18.124257,365.479488,0.996625,540.392786,1121.281168,NaN,1164.782639,30.289484,358.895323,154.756355,73.858808,93.222903,222.705255,2098.510766,3219.791934,2770.818194,NaN,279.79735,46.533742,13.330205,339.661298,3559.453232,2431.156897,237.572974,616.542572,19.838619,493.633864,1367.58803,4927.041262,1063.568867,41.282124,7.429975,0.169781,25.067833,73.949714,5000.990976,989.619153,162.004329,5162.995304,827.614824,40.505273,787.109551,1,1,0.683333,0.416667,191,3.638548,1620,162,152,30.942,29.032,93.82716,180,0,180,0.034382,0,0.034382,2.816097,2.873122,0.637419,0.553912,0.553903,0.553903,3.000871,5.394015,6.207217,78.963427,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,259.915266,5003.755505,0,0.000128,0.904497,0,259.913467,5063.458922,0,259.915236,5002.732278,0,12,150,0,1,151,0,2.292,28.65,0,0.191,28.841,489.566409,47.838249,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
4,NaN,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGNR,02012024,6358.607841,65.022368,1.095878,6422.534332,4.36,0,4.36,0,594.445025,7021.339356,NaN,NaN,NaN,227.086522,0.254141,21.354586,382.31078,1.042522,633.371402,1265.419954,NaN,1328.71501,30.289484,358.895323,154.756355,82.543012,93.222903,266.159939,2314.582026,3580.00198,3441.337376,NaN,331.011335,46.533742,15.931221,393.476299,3973.478279,3047.861077,283.928677,736.843562,23.252002,552.869928,1596.894168,5570.372447,1450.966909,48.385022,8.708358,0.198993,29.380941,86.673315,5657.045762,1364.293594,189.878384,5846.924146,1174.415211,45.870903,1128.544307,1,1,0.816667,0.466667,191,3.638548,1848,162,159,30.942,30.369,98.148148,9,0,9,0.001719,0,0.001719,2.945786,2.970919,0.637419,0.553912,0.553903,0.553903,3.000871,0.269701,0.310361,81.651203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1803.219124,4552.398247,0,0.000156,1.095722,0,1803.206646,4606.716195,0,1803.218913,4551.467319,0,12,150,0,13,146,0,2.292,28.65,0,2.483,27.886,593.068566,1.376459,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110776,NaN,2025,MAY,AC738,GA6054.KDI-UPG.[KDI-UPG],DOM,DOM_4 (UPG),UPG-KDI-UPG,KDI-UPG,PKGUF,24052025,8005.084,-0.843,-0.051,8004.292,0,0,0,0,460.586,8464.878,NaN,NaN,NaN,108.665,0,39.504297,309.88,32.163,819.951,1310.163297,NaN,1888.962,61.781,138.074,86.791,96.747,107.324,528.304,2907.983,4218.146297,4246.731703,NaN,399.652,127.997,24.4913,552.1403,4770.286596,3694.591404,349.298927,683.495005,18.985764,678.361573,1730.141269,6500.427866,1964.450134,70.597,9.246,2.419,53.399,135.661,6636.088866,1828.789134,303.945021,6940.033887,1524.844113,-146.615,1671.459113,1,1,0.9,0.633333,336,6.401,2479,162,158,54.432,53.088,97.530864,0,0,0,0,0,0,5.15,5.149,1.121,0.9744,0.974,0.974,5.279,0,0,80.440556,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,820.777,7184.308,0,-0.004,-0.047,0,820.716,7183.576,0,820.781,7184.355,0,12,150,0,12,146,0,4.032,50.4,0,4.032,49.056,460.586,0,Q2,ACTUAL,B738NG,PAX & CARGO,IBT,DOM_EAST
110777,NaN,2025,MAY,AC73H,GA2084.CGK-YIA.[CGK-YIA],DOM,DOM_3 (SUB),CGK-YIA-CGK,CGK-YIA,PKGUH,28052025,6477.089,24.671,-0.047,6501.807,304.91,0,304.91,0,460.849,7267.566,NaN,NaN,NaN,262.142,9.77,31.963821,236.79,29.284,594.228,1164.177821,NaN,2008.047,65.141,327.444,98.851,117.624,132.126,730.894,3480.127,4644.304821,2623.261179,NaN,515.661,170.51,32.869902,719.040902,5363.345723,1904.220277,446.326407,873.354729,24.259587,866.795343,2210.736066,7574.081789,-306.515789,93.486,12.243,3.203,70.712,179.644,7753.725789,-486.159789,402.490394,8156.216183,-888.650183,-264.542,-624.108183,1,1,1.15,0.85,424,8.077,3544,170,114,72.08,48.336,67.058824,507.5,0,507.5,0.215,0,0.215,4.689,4.917,1.086,1.229767,1.23,1.23,6.991,19.797422,17.482992,60.876563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,674.619,5802.47,0,-0.003,-0.044,0,674.575,5827.232,0,674.622,5802.514,0,8,162,0,7,107,0,3.392,68.688,0,2.968,45.368,372.671,88.178,Q2,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
110778,NaN,2025,MAY,AC73H,GA2094.YIA-CGK.[YIA-CGK],DOM,DOM_3 (SUB),CGK-YIA-CGK,YIA-CGK,PKGUH,28052025,7729.572,34.973,-0.048,7764.593,810.19,0,810.19,0,679.035,9253.818,NaN,NaN,NaN,323.63,40.32,38.144666,243.57,30.312,612.621,1288.597666,NaN,2349.846,66.681,379.414,98.851,120.408,132.126,659.237,3806.563,5095.160666,4158.657334,NaN,530.608,170.766,29.647363,731.021363,5826.182029,3427.635971,459.134034,898.416213,24.955732,891.6686,2274.174579,8100.356608,1153.461392,93.486,12.243,3.203,70.712,179.644,8280.000608,973.817392,402.490394,8682.491002,571.326998,-272.21,843.536998,1,1,1.183333,0.766667,424,8.077,3165,170,118,72.08,50.032,69.411765,49,0,49,0.021,0,0.021,4.853,4.891,1.086,1.229767,1.23,1.23,6.991,1.933702,1.707641,60.554661,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1523.609,6205.963,0,-0.003,-0.045,0,1523.558,6241.035,0,1523.612,6206.008,0,8,162,0,8,110,0,3.392,68.688,0,3.392,46.64,444.734,234.301,Q2,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
110779,NaN,2025,MAY,AC73H,GA4324.CGK-AMI.[CGK-AMI],DOM,DOM_2 (JKT),CGK-AMI-CGK,CGK-AMI,PKGUI,29052025,15713.245,41.607,-0.182,15755.034,1373.88,0,1373.88,0,1301.409,18430.323,NaN,NaN,NaN,573.266,38.08,77.543712,449.54,114.064,904.834,2157.327712,NaN,3729.392,50.381,327.444,188.221,188.606,293.876,1418.793,6196.713,8354.040712,10076.282288,NaN,896.802,435.184,63.806281,1395.792281,9749.832993,8680.490007,776.219838,1518.87779,42.190587,1507.470161,3844.758376,13594.591369,4835.731631,242.756,31.792,8.317,183.617,466.482,14061.073369,4369.249631,1045.146047,15106.219416,3324.103584,-460.072,3784.175584,1,1,2,1.65,1101,20.974,6582,170,171,187.17,188.271,100.588235,3376.5,0,3376.5,3.718,0,3.718,18.262,22.015,2.82,3.637177,3.193,3.193,18.152,131.843972,102.222141,104.963288,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1499.764,14213.481,0,-0.007,-0.175,0,1499.649,14255.385,0,1499.771,14213.656,0,8,162,0,7,164,0,8.808,178.362,0,7.707,180.564,904.093,397.316,Q2,ACTUAL,B738NG,PAX & CARGO,IBT,DOM_EAST
110780,NaN,2025,MAY,AC73H,GA4344.AMI-CGK.[AMI-CGK],DOM,DOM_2 (JKT),CGK-AMI-CGK,AMI-CGK,PKGUI,29052025,8425.103,33.184,6.667,8451.62,902.05,0,902.05,0,745.232,10098.902,NaN,NaN,NaN,319.813,33.96,41.543883,296.99,60.701,482.521,1235.528883,NaN,4391.674,66.681,379.414,188.221,206.7,293.876,1605.1,7131.666,8367.194883,1731.707117,NaN,993.956,436.849,72.184883,1502.989883,9870.184766,228.717234,860.439691,1683.67603,46.768266,1671.030674,4261.91466,14132.099426,-4033.197426,242.756,31.792,8.317,183.617,466.482,14598.581426,-4499.679426,1045.146047,15643.727473,-5544.825473,-509.914,-5034.911473,1,1,2.216667,1.866667,1101,20.974,6075,170,91,187.17,100.191,53.529412,1991,0,1991,2.192,0,2.192,9.719,11.942,2.82,3.216021,3.193,3.193,18.152,77.730496,68.158759,56.93716,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1657.367,6767.736,0,-0.005,6.672,0,1657.285,6794.335,0,1657.372,6761.064,0,8,162,0,5,86,0,8.808,178.362,0,5.505,94.686,484.366,260.866,Q2,ACTUAL,B738NG,PAX & CARGO,IBT,DOM_EAST

In [ ]:
# Gunakan baris ke-1 sebagai header
df.columns = df.iloc[0]  # set baris ke-1 sebagai header
df = df.drop([0])     # hapus baris pertama (NaN) dan baris header lama

# Reset index
df = df.reset_index(drop=True)
df = df.iloc[:,1:]
df

,YEAR,PERIODE,AIRCRAFT TYPE,FLIGHT NUMBER_CITYPAIR,SERVICE TYPE,SUB-SERVICE,ROUNDTRIPROUTE,FLIGHT ROUTE,AC REG,DATE,PASSENGER REVENUE GROSS,EXCESS BAGGAGE REVENUE,PASSENGER REVENUE DISCOUNT,PASSENGER REVENUE NETT,FREIGHT REVENUE GROSS,FREIGHT REVENUE DISCOUNT,FREIGHT REVENUE NETT,MAIL REVENUE,OTHER REVENUE,NETT REVENUES,COSTS :,DIRECT COSTS :,DIRECT TRAFFIC COSTS :,PASSENGER COMMISSION,FREIGHT COMMISSION,CREDIT CARD COMMISSION,CATERING,ON BOARD SERVICE,RESERVATION,TOTAL DIRECT TRAFFIC COSTS,DIRECT FLIGHT COSTS :,FUEL AIRCRAFT,LANDING,HANDLING,AIR TRAFFIC CONTROL,COCKPIT CREW TRAVEL,CABIN CREW TRAVEL,VARIABLE MAINTENANCE,TOTAL DIRECT FLIGHT COSTS,TOTAL DIRECT COSTS,CONTRIBUTION MARGIN 1,INDIRECT COSTS :,COCKPIT CREW PERSON,CABIN CREW PERSON,AIRCRAFT MAINTENANCE,TOTAL INDIRECT COSTS,TOTAL DIRECT AND INDIRECT COSTS,CONTRIBUTION MARGIN 2,DEPRECIATION AIRCRAFT,LEASE AIRCRAFT,INSURANCE,MAINTENANCE RESERVE,TOTAL FLEET COST,"TOTAL DIRECT,INDIRECT,FLEET COSTS",CONTRIBUTION MARGIN 3,STATION,SALES ORGANIZATION,MARKETING,ADMINISTRATION BO,TOTAL OVERHEAD COST BO,TOTAL BO COSTS,ROUTE RESULT PERFORMANCE BO,ADMINISTRATION HO,TOTAL COSTS,ROUTE RESULT 1,ADJUSTMENT,ROUTE RESULT 2,FLIGHT ROUTES,NUMBER OF LANDING,BLOCK HOURS,FLIGHT HOURS,FLIGHT KILOMETERS,ATK (000),FUEL BURN (IN LITER),SEAT OFFERED,PASSENGER CARRIED,ASK (000),RPK (000),SLF (%),FREIGHT CARRIED,MAIL CARRIED,CARGO CARRIED,RTK FREIGHT (000),RTK MAIL (000),RTK CARGO (000),RTK PASSENGER (000),RTK (000),ATK CARGO (000),ATK CARGO GF (000),ATK FREIGHT GF (000),ATK MAIL GF (000),ATK PASSENGER (000),CLF (%),CLF-GF (%),LOAD FACTOR (%),BREAK EVEN LF (%),BREAK EVEN SLF-RR1 (%),NETT REVENUE/ATK (USC),NETT REVENUE/ASK (USC),PAX YIELD (USC),FREIGHT YIELD (USC),MAIL YIELD (USC),CARGO YIELD (USC),COST/ASK RR 1 (USC),COST/ASK EXCFUEL-RR1,COST PER RPK (USC),COST PER ATK (USC),COST/BLOCKHOURS,MARGIN/ASK RR 1(USC),AVERAGE FUEL PRICE,PROFIT MARGIN (%),COST COVERAGE (%),AVERAGE STAGE LENGTH,PASSENGER REVENUE GROSS F CLASS,PASSENGER REVENUE GROSS C CLASS,PASSENGER REVENUE GROSS Y CLASS,PASSENGER REVENUE DISCOUNT F CLASS,PASSENGER REVENUE DISCOUNT C CLASS,PASSENGER REVENUE DISCOUNT Y CLASS,PASSENGER REVENUE NETT F CLASS,PASSENGER REVENUE NETT C CLASS,PASSENGER REVENUE NETT Y CLASS,PASSENGER REVENUE NETT (EXCLUDE EBT) F CLASS,PASSENGER REVENUE NETT (EXCLUDE EBT) C CLASS,PASSENGER REVENUE NETT (EXCLUDE EBT) Y CLASS,SEAT OFFERED F CLASS,SEAT OFFERED C CLASS,SEAT OFFERED Y CLASS,PASSENGER CARRIED F CLASS,PASSENGER CARRIED C CLASS,PASSENGER CARRIED Y CLASS,ASK (000) F CLASS,ASK (000) C CLASS,ASK (000) Y CLASS,RPK (000) F CLASS,RPK (000) C CLASS,RPK (000) Y CLASS,OTHER REVENUE PASSENGER,OTHER REVENUE FREIGHT,QUARTER,STATUS,AIRCRAFT TYPE GROUPING,FLIGHT TYPE,GA Service,Region
0,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGNR,30012024,4097.39336,41.899458,0.706168,4138.58665,4.33,0,4.33,0,383.531648,4526.448297,NaN,NaN,NaN,146.331215,0.252392,13.765684,363.075018,0.990068,408.315673,932.73005,NaN,1256.095846,30.289484,358.895323,154.756355,77.115384,93.222903,239.000762,2209.376056,3142.106106,1384.342191,NaN,299.002595,46.533742,14.305586,359.841923,3501.948029,1024.500268,254.956363,661.655443,14.989873,454.143155,1385.744834,4887.692863,-361.244566,31.192382,5.614019,0.128285,18.941017,55.875704,4943.568567,-417.12027,122.408937,5065.977504,-539.529207,39.744139,-579.273346,1,1,0.733333,0.383333,191,3.638548,1747,162,151,30.942,28.841,93.209877,9,0,9,0.001719,0,0.001719,2.79757,2.821526,0.637419,0.553912,0.553903,0.553903,3.000871,0.269701,0.310361,77.545362,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,57.686882,4165.471873,0,0.0001,0.706067,0,57.686482,4215.173124,0,57.686875,4164.620068,0,12,150,0,3,148,0,2.292,28.65,0,0.573,28.268,382.16466,1.366988,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
1,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGFJ,31012024,4580.064734,46.835198,0.789354,4626.110578,47.76,0,47.76,0,442.261415,5116.131993,NaN,NaN,NaN,163.568976,2.783893,15.531319,363.075018,0.990068,461.509055,1007.458329,NaN,1547.291506,30.289484,358.895323,154.756355,92.312743,93.222903,315.046459,2591.814772,3599.2731,1516.858893,NaN,388.627069,46.533742,18.857364,454.018174,4053.291275,1062.840718,336.078842,872.182175,16.942681,612.105992,1837.309689,5890.600964,-774.468971,35.255974,6.345386,0.144997,21.408561,63.154919,5953.755883,-837.62389,138.355779,6092.111662,-975.979669,47.794474,-1023.774143,1,1,0.966667,0.516667,191,3.638548,2152,162,151,30.942,28.841,93.209877,123,0,123,0.023495,0,0.023495,2.79757,2.843474,0.637419,0.553912,0.553903,0.553903,3.000871,3.685911,4.241598,78.148585,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,759.890061,3976.008816,0,0.000112,0.789242,0,759.884803,4023.449447,0,759.889973,3975.195755,0,12,150,0,5,146,0,2.292,28.65,0,0.955,27.886,427.183511,15.077904,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
2,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGNA,01012024,5248.905413,53.674683,0.904626,5301.67547,151.53,0,151.53,0,537.404658,5990.610128,NaN,NaN,NaN,187.455447,8.832565,18.124257,365.479488,0.996625,540.392786,1121.281168,NaN,1164.782639,30.289484,358.895323,154.756355,73.858808,93.222903,222.705255,2098.510766,3219.791934,2770.818194,NaN,279.79735,46.533742,13.330205,339.661298,3559.453232,2431.156897,237.572974,616.542572,19.838619,493.633864,1367.58803,4927.041262,1063.568867,41.282124,7.429975,0.169781,25.067833,73.949714,5000.990976,989.619153,162.004329,5162.995304,827.614824,40.505273,787.109551,1,1,0.683333,0.416667,191,3.638548,1620,162,152,30.942,29.032,93.82716,180,0,180,0.034382,0,0.034382,2.816097,2.873122,0.637419,0.553912,0.553903,0.553903,3.000871,5.394015,6.207217,78.963427,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,259.915266,5003.755505,0,0.000128,0.904497,0,259.913467,5063.458922,0,259.915236,5002.732278,0,12,150,0,1,151,0,2.292,28.65,0,0.191,28.841,489.566409,47.838249,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
3,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGNR,02012024,6358.607841,65.022368,1.095878,6422.534332,4.36,0,4.36,0,594.445025,7021.339356,NaN,NaN,NaN,227.086522,0.254141,21.354586,382.31078,1.042522,633.371402,1265.419954,NaN,1328.71501,30.289484,358.895323,154.756355,82.543012,93.222903,266.159939,2314.582026,3580.00198,3441.337376,NaN,331.011335,46.533742,15.931221,393.476299,3973.478279,3047.861077,283.928677,736.843562,23.252002,552.869928,1596.894168,5570.372447,1450.966909,48.385022,8.708358,0.198993,29.380941,86.673315,5657.045762,1364.293594,189.878384,5846.924146,1174.415211,45.870903,1128.544307,1,1,0.816667,0.466667,191,3.638548,1848,162,159,30.942,30.369,98.148148,9,0,9,0.001719,0,0.001719,2.945786,2.970919,0.637419,0.553912,0.553903,0.553903,3.000871,0.269701,0.310361,81.651203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1803.219124,4552.398247,0,0.000156,1.095722,0,1803.206646,4606.716195,0,1803.218913,4551.467319,0,12,150,0,13,146,0,2.292,28.65,0,2.483,27.886,593.068566,1.376459,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
4,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGMW,19012024,4807.854135,49.164545,0.828612,4856.190067,97.35,0,97.35,0,479.163014,5432.703081,NaN,NaN,NaN,171.704075,5.674455,16.462224,360.670548,0.983512,490.065868,1045.560681,NaN,1246.748825,30.289484,358.895323,154.756355,76.029859,93.222903,233.568926,2193.511674,3239.072355,2193.630726,NaN,292.600847,46.533742,13.980459,353.115048,3592.187403,1840.515678,249.1619,646.61782,17.991044,513.379219,1427.149982,5019.337385,413.365696,37.43751,6.73802,0.153969,22.73326,67.062758,5086.400143,346.302938,146.916824,5233.316968,199.386113,41.056968,158.329146,1,1,0.716667,0.433333,191,3.638548,1734,162,150,30.942,28.65,92.592593,321,0,321,0.061315,0,0.061315,2.779043,2.862921,0.637419,0.553912,0.553903,0.553903,3.000871,9.619327,11.069537,78.683058,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,275.54807,4498.982388,0,0.000118,0.828495,0,275.546164,4552.662994,0,275.548038,4498.062384,0,12,150,0,3,147,0,2.292,28.65,0,0.573,28.077,448.429472,30.733542,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110775,2025,MAY,AC738,GA6054.KDI-UPG.[KDI-UPG],DOM,DOM_4 (UPG),UPG-KDI-UPG,KDI-UPG,PKGUF,24052025,8005.084,-0.843,-0.051,8004.292,0,0,0,0,460.586,8464.878,NaN,NaN,NaN,108.665,0,39.504297,309.88,32.163,819.951,1310.163297,NaN,1888.962,61.781,138.074,86.791,96.747,107.324,528.304,2907.983,4218.146297,4246.731703,NaN,399.652,127.997,24.4913,552.1403,4770.286596,3694.591404,349.298927,683.495005,18.985764,678.361573,1730.141269,6500.427866,1964.450134,70.597,9.246,2.419,53.399,135.661,6636.088866,1828.789134,303.945021,6940.033887,1524.844113,-146.615,1671.459113,1,1,0.9,0.633333,336,6.401,2479,162,158,54.432,53.088,97.530864,0,0,0,0,0,0,5.15,5.149,1.121,0.9744,0.974,0.974,5.279,0,0,80.440556,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,820.777,7184.308,0,-0.004,-0.047,0,820.716,7183.576,0,820.781,7184.355,0,12,150,0,12,146,0,4.032,50.4,0,4.032,49.056,460.586,0,Q2,ACTUAL,B738NG,PAX & CARGO,IBT,DOM_EAST
110776,2025,MAY,AC73H,GA2084.CGK-YIA.[CGK-YIA],DOM,DOM_3 (SUB),CGK-YIA-CGK,CGK-YIA,PKGUH,28052025,6477.089,24.671,-0.047,6501.807,304.91,0,304.91,0,460.849,7267.566,NaN,NaN,NaN,262.142,9.77,31.963821,236.79,29.284,594.228,1164.177821,NaN,2008.047,65.141,327.444,98.851,117.624,132.126,730.894,3480.127,4644.304821,2623.261179,NaN,515.661,170.51,32.869902,719.040902,5363.345723,1904.220277,446.326407,873.354729,24.259587,866.795343,2210.736066,7574.081789,-306.515789,93.486,12.243,3.203,70.712,179.644,7753.725789,-486.159789,402.490394,8156.216183,-888.650183,-264.542,-624.108183,1,1,1.15,0.85,424,8.077,3544,170,114,72.08,48.336,67.058824,507.5,0,507.5,0.215,0,0.215,4.689,4.917,1.086,1.229767,1.23,1.23,6.991,19.797422,17.482992,60.876563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,674.619,5802.47,0,-0.003,-0.044,0,674.575,5827.232,0,674.622,5802.514,0,8,162,0,7,107,0,3.392,68.688,0,2.968,45.368,372.671,88.178,Q2,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
110777,2025,MAY,AC73H,GA2094.YIA-CGK.[YIA-CGK],DOM,DOM_3 (SUB),CGK-YIA-CGK,YIA-CGK,PKGUH,28052025,7729.572,34.973,-0.048,7764.593,810.19,0,810.19,0,679.035,9253.818,NaN,NaN,NaN,323.63,40.32,38.144666,243.57,30.312,612.621,1288.597666,NaN,2349.846,66.681,379.414,98.851,120.408,132.126,659.237,3806.563,5095.160666,4158.657334,NaN,530.608,170.766,29.647363,731.021363,5826.182029,3427.635971,459.134034,898.416213,24.955732,891.6686,2274.174579,8100.356608,1153.461392,93.486,12.243,3.203,70.712,179.644,8280.000608,973.817392,402.490394,8682.491002,571.326998,-272.21,843.536998,1,1,1.183333,0.766667,424,8.077,3165,170,118,72.08,50.032,69.411765,49,0,49,0.021,0,0.021,4.853,4.891,1.086,1.229767,1.23,1.23,6.991,1.933702,1.707641,60.554661,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1523.609,6205.963,0,-0.003,-0.045,0,1523.558,6241.035,0,1523.612,6206.008,0,8,162,0,8,110,0,3.392,68.688,0,3.392,46.64,444.734,234.301,Q2,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
110778,2025,MAY,AC73H,GA4324.CGK-AMI.[CGK-AMI],DOM,DOM_2 (JKT),CGK-AMI-CGK,CGK-AMI,PKGUI,29052025,15713.245,41.607,-0.182,15755.034,1373.88,0,1373.88,0,1301.409,18430.323,NaN,NaN,NaN,573.266,38.08,77.543712,449.54,114.064,904.834,2157.327712,NaN,3729.392,50.381,327.444,188.221,188.606,293.876,1418.793,6196.713,8354.040712,10076.282288,NaN,896.802,435.184,63.806281,1395.792281,9749.832993,8680.490007,776.219838,1518.87779,42.190587,1507.470161,3844.758376,13594.591369,4835.731631,242.756,31.792,8.317,183.617,466.482,14061.073369,4369.249631,1045.146047,15106.219416,3324.103584,-460.072,3784.175584,1,1,2,1.65,1101,20.974,6582,170,171,187.17,188.271,100.588235,3376.5,0,3376.5,3.718,0,3.718,18.262,22.015,2.82,3.637177,3.193,3.193,18.152,131.843972,102.222141,104.963288,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1499.764,14213.481,0,-0.007,-0.175,0,1499.649,14255.385,0,1499.771,14213.656,0,8,162,0,7,164,0,8.808,178.362,0,7.707,180.564,904.093,397.316,Q2,ACTUAL,B738NG,PAX & CARGO,IBT,DOM_EAST
110779,2025,MAY,AC73H,GA4344.AMI-CGK.[AMI-CGK],DOM,DOM_2 (JKT),CGK-AMI-CGK,AMI-CGK,PKGUI,29052025,8425.103,33.184,6.667,8451.62,902.05,0,902.05,0,745.232,10098.902,NaN,NaN,NaN,319.813,33.96,41.543883,296.99,60.701,482.521,1235.528883,NaN,4391.674,66.681,379.414,188.221,206.7,293.876,1605.1,7131.666,8367.194883,1731.707117,NaN,993.956,436.849,72.184883,1502.989883,9870.184766,228.717234,860.439691,1683.67603,46.768266,1671.030674,4261.91466,14132.099426,-4033.197426,242.756,31.792,8.317,183.617,466.482,14598.581426,-4499.679426,1045.146047,15643.727473,-5544.825473,-509.914,-5034.911473,1,1,2.216667,1.866667,1101,20.974,6075,170,91,187.17,100.191,53.529412,1991,0,1991,2.192,0,2.192,9.719,11.942,2.82,3.216021,3.193,3.193,18.152,77.730496,68.158759,56.93716,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1657.367,6767.736,0,-0.005,6.672,0,1657.285,6794.335,0,1657.372,6761.064,0,8,162,0,5,86,0,8.808,178.362,0,5.505,94.686,484.366,260.866,Q2,ACTUAL,B738NG,PAX & CARGO,IBT,DOM_EAST

In [30]:
for column in df.columns:
    nunique = df[column].nunique()
    unique = list(df[column].unique())
    print(column)
    print(df[column])
    print(f"nunique: {nunique}")
    if nunique <= 50:
        print(f"unique: {unique}")
    print("")

YEAR
0         2024
1         2024
2         2024
3         2024
4         2024
          ...
110775    2025
110776    2025
110777    2025
110778    2025
110779    2025
Name: YEAR, Length: 110780, dtype: object
nunique: 2
unique: [2024, 2025]

PERIODE
0         JAN
1         JAN
2         JAN
3         JAN
4         JAN
         ...
110775    MAY
110776    MAY
110777    MAY
110778    MAY
110779    MAY
Name: PERIODE, Length: 110780, dtype: object
nunique: 12
unique: ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC']

AIRCRAFT TYPE
0         AC738
1         AC738
2         AC738
3         AC738
4         AC738
          ...
110775    AC738
110776    AC73H
110777    AC73H
110778    AC73H
110779    AC73H
Name: AIRCRAFT TYPE, Length: 110780, dtype: object
nunique: 11
unique: ['AC738', 'AC773', 'AC73G', 'AC330', 'AC33R', 'AC334', 'AC32E', 'AC339', 'AC777', 'AC33E', 'AC73H']

FLIGHT NUMBER_CITYPAIR
0         GA0072.CGK-TKG.[CGK-TKG]
1         GA0072.CGK-TKG.[CGK-TKG]
2         GA0072.CGK-TKG.[CGK-TKG]
3         GA0072.CGK-TKG.[CGK-TKG]
4         GA0072.CGK-TKG.[CGK-TKG]
                    ...
110775    GA6054.KDI-UPG.[KDI-UPG]
110776    GA2084.CGK-YIA.[CGK-YIA]
110777    GA2094.YIA-CGK.[YIA-CGK]
110778    GA4324.CGK-AMI.[CGK-AMI]
110779    GA4344.AMI-CGK.[AMI-CGK]
Name: FLIGHT NUMBER_CITYPAIR, Length: 110780, dtype: object
nunique: 1088

SERVICE TYPE
0         DOM
1         DOM
2         DOM
3         DOM
4         DOM
         ...
110775    DOM
110776    DOM
110777    DOM
110778    DOM
110779    DOM
Name: SERVICE TYPE, Length: 110780, dtype: object
nunique: 2
unique: ['DOM', 'INT']

SUB-SERVICE
0         DOM_2 (JKT)
1         DOM_2 (JKT)
2         DOM_2 (JKT)
3         DOM_2 (JKT)
4         DOM_2 (JKT)
             ...
110775    DOM_4 (UPG)
110776    DOM_3 (SUB)
110777    DOM_3 (SUB)
110778    DOM_2 (JKT)
110779    DOM_2 (JKT)
Name: SUB-SERVICE, Length: 110780, dtype: object
nunique: 11
unique: ['DOM_2 (JKT)', 'INT_5 (AMS)-EUR', 'DOM_1 (MES)', 'DOM_3 (SUB)', 'DOM_3 (DPS)', 'DOM_4 (UPG)', 'INT_4 (SYD)', 'INT_1 (SIN)', 'INT_2 (TYO)', 'INT_3 (SHA)', 'INT_5 (AMS)-MEA']

ROUNDTRIPROUTE
0         CGK-TKG-CGK
1         CGK-TKG-CGK
2         CGK-TKG-CGK
3         CGK-TKG-CGK
4         CGK-TKG-CGK
             ...
110775    UPG-KDI-UPG
110776    CGK-YIA-CGK
110777    CGK-YIA-CGK
110778    CGK-AMI-CGK
110779    CGK-AMI-CGK
Name: ROUNDTRIPROUTE, Length: 110780, dtype: object
nunique: 78

FLIGHT ROUTE
0         CGK-TKG
1         CGK-TKG
2         CGK-TKG
3         CGK-TKG
4         CGK-TKG
           ...
110775    KDI-UPG
110776    CGK-YIA
110777    YIA-CGK
110778    CGK-AMI
110779    AMI-CGK
Name: FLIGHT ROUTE, Length: 110780, dtype: object
nunique: 153

AC REG
0         PKGNR
1         PKGFJ
2         PKGNA
3         PKGNR
4         PKGMW
          ...
110775    PKGUF
110776    PKGUH
110777    PKGUH
110778    PKGUI
110779    PKGUI
Name: AC REG, Length: 110780, dtype: object
nunique: 70

DATE
0         30012024
1         31012024
2         01012024
3         02012024
4         19012024
            ...
110775    24052025
110776    28052025
110777    28052025
110778    29052025
110779    29052025
Name: DATE, Length: 110780, dtype: object
nunique: 517

PASSENGER REVENUE GROSS
0          4097.39336
1         4580.064734
2         5248.905413
3         6358.607841
4         4807.854135
             ...
110775       8005.084
110776       6477.089
110777       7729.572
110778      15713.245
110779       8425.103
Name: PASSENGER REVENUE GROSS, Length: 110780, dtype: object
nunique: 110271

EXCESS BAGGAGE REVENUE
0         41.899458
1         46.835198
2         53.674683
3         65.022368
4         49.164545
            ...
110775       -0.843
110776       24.671
110777       34.973
110778       41.607
110779       33.184
Name: EXCESS BAGGAGE REVENUE, Length: 110780, dtype: object
nunique: 110224

PASSENGER REVENUE DISCOUNT
0         0.706168
1         0.789354
2         0.904626
3         1.095878
4         0.828612
            ...
110775      -0.051
110776      -0.047
110777      -0.048
110778      -0.182
110779       6.667
Name: PASSENGER REVENUE DISCOUNT, Length: 110780, dtype: object
nunique: 109462

PASSENGER REVENUE NETT
0          4138.58665
1         4626.110578
2          5301.67547
3         6422.534332
4         4856.190067
             ...
110775       8004.292
110776       6501.807
110777       7764.593
110778      15755.034
110779        8451.62
Name: PASSENGER REVENUE NETT, Length: 110780, dtype: object
nunique: 110271

FREIGHT REVENUE GROSS
0            4.33
1           47.76
2          151.53
3            4.36
4           97.35
           ...
110775          0
110776     304.91
110777     810.19
110778    1373.88
110779     902.05
Name: FREIGHT REVENUE GROSS, Length: 110780, dtype: object
nunique: 89353

FREIGHT REVENUE DISCOUNT
0         0
1         0
2         0
3         0
4         0
         ..
110775    0
110776    0
110777    0
110778    0
110779    0
Name: FREIGHT REVENUE DISCOUNT, Length: 110780, dtype: object
nunique: 1
unique: [0]

FREIGHT REVENUE NETT
0            4.33
1           47.76
2          151.53
3            4.36
4           97.35
           ...
110775          0
110776     304.91
110777     810.19
110778    1373.88
110779     902.05
Name: FREIGHT REVENUE NETT, Length: 110780, dtype: object
nunique: 89353

MAIL REVENUE
0         0
1         0
2         0
3         0
4         0
         ..
110775    0
110776    0
110777    0
110778    0
110779    0
Name: MAIL REVENUE, Length: 110780, dtype: object
nunique: 26533

OTHER REVENUE
0         383.531648
1         442.261415
2         537.404658
3         594.445025
4         479.163014
             ...
110775       460.586
110776       460.849
110777       679.035
110778      1301.409
110779       745.232
Name: OTHER REVENUE, Length: 110780, dtype: object
nunique: 110313

NETT REVENUES
0         4526.448297
1         5116.131993
2         5990.610128
3         7021.339356
4         5432.703081
             ...
110775       8464.878
110776       7267.566
110777       9253.818
110778      18430.323
110779      10098.902
Name: NETT REVENUES, Length: 110780, dtype: object
nunique: 110325

COSTS :
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
110775    NaN
110776    NaN
110777    NaN
110778    NaN
110779    NaN
Name: COSTS :, Length: 110780, dtype: object
nunique: 0
unique: [nan]

DIRECT COSTS :
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
110775    NaN
110776    NaN
110777    NaN
110778    NaN
110779    NaN
Name: DIRECT COSTS :, Length: 110780, dtype: object
nunique: 0
unique: [nan]

DIRECT TRAFFIC COSTS :
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
110775    NaN
110776    NaN
110777    NaN
110778    NaN
110779    NaN
Name: DIRECT TRAFFIC COSTS :, Length: 110780, dtype: object
nunique: 0
unique: [nan]

PASSENGER COMMISSION
0         146.331215
1         163.568976
2         187.455447
3         227.086522
4         171.704075
             ...
110775       108.665
110776       262.142
110777        323.63
110778       573.266
110779       319.813
Name: PASSENGER COMMISSION, Length: 110780, dtype: object
nunique: 110269

FREIGHT COMMISSION
0         0.252392
1         2.783893
2         8.832565
3         0.254141
4         5.674455
            ...
110775           0
110776        9.77
110777       40.32
110778       38.08
110779       33.96
Name: FREIGHT COMMISSION, Length: 110780, dtype: object
nunique: 92375

CREDIT CARD COMMISSION
0         13.765684
1         15.531319
2         18.124257
3         21.354586
4         16.462224
            ...
110775    39.504297
110776    31.963821
110777    38.144666
110778    77.543712
110779    41.543883
Name: CREDIT CARD COMMISSION, Length: 110780, dtype: object
nunique: 110278

CATERING
0         363.075018
1         363.075018
2         365.479488
3          382.31078
4         360.670548
             ...
110775        309.88
110776        236.79
110777        243.57
110778        449.54
110779        296.99
Name: CATERING, Length: 110780, dtype: object
nunique: 88586

ON BOARD SERVICE
0         0.990068
1         0.990068
2         0.996625
3         1.042522
4         0.983512
            ...
110775      32.163
110776      29.284
110777      30.312
110778     114.064
110779      60.701
Name: ON BOARD SERVICE, Length: 110780, dtype: object
nunique: 89649

RESERVATION
0         408.315673
1         461.509055
2         540.392786
3         633.371402
4         490.065868
             ...
110775       819.951
110776       594.228
110777       612.621
110778       904.834
110779       482.521
Name: RESERVATION, Length: 110780, dtype: object
nunique: 110316

TOTAL DIRECT TRAFFIC COSTS
0           932.73005
1         1007.458329
2         1121.281168
3         1265.419954
4         1045.560681
             ...
110775    1310.163297
110776    1164.177821
110777    1288.597666
110778    2157.327712
110779    1235.528883
Name: TOTAL DIRECT TRAFFIC COSTS, Length: 110780, dtype: object
nunique: 110411

DIRECT FLIGHT COSTS :
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
110775    NaN
110776    NaN
110777    NaN
110778    NaN
110779    NaN
Name: DIRECT FLIGHT COSTS :, Length: 110780, dtype: object
nunique: 0
unique: [nan]

FUEL AIRCRAFT
0         1256.095846
1         1547.291506
2         1164.782639
3          1328.71501
4         1246.748825
             ...
110775       1888.962
110776       2008.047
110777       2349.846
110778       3729.392
110779       4391.674
Name: FUEL AIRCRAFT, Length: 110780, dtype: object
nunique: 76406

LANDING
0         30.289484
1         30.289484
2         30.289484
3         30.289484
4         30.289484
            ...
110775       61.781
110776       65.141
110777       66.681
110778       50.381
110779       66.681
Name: LANDING, Length: 110780, dtype: object
nunique: 4665

HANDLING
0         358.895323
1         358.895323
2         358.895323
3         358.895323
4         358.895323
             ...
110775       138.074
110776       327.444
110777       379.414
110778       327.444
110779       379.414
Name: HANDLING, Length: 110780, dtype: object
nunique: 3091

AIR TRAFFIC CONTROL
0         154.756355
1         154.756355
2         154.756355
3         154.756355
4         154.756355
             ...
110775        86.791
110776        98.851
110777        98.851
110778       188.221
110779       188.221
Name: AIR TRAFFIC CONTROL, Length: 110780, dtype: object
nunique: 5164

COCKPIT CREW TRAVEL
0         77.115384
1         92.312743
2         73.858808
3         82.543012
4         76.029859
            ...
110775       96.747
110776      117.624
110777      120.408
110778      188.606
110779        206.7
Name: COCKPIT CREW TRAVEL, Length: 110780, dtype: object
nunique: 71188

CABIN CREW TRAVEL
0         93.222903
1         93.222903
2         93.222903
3         93.222903
4         93.222903
            ...
110775      107.324
110776      132.126
110777      132.126
110778      293.876
110779      293.876
Name: CABIN CREW TRAVEL, Length: 110780, dtype: object
nunique: 69497

VARIABLE MAINTENANCE
0         239.000762
1         315.046459
2         222.705255
3         266.159939
4         233.568926
             ...
110775       528.304
110776       730.894
110777       659.237
110778      1418.793
110779        1605.1
Name: VARIABLE MAINTENANCE, Length: 110780, dtype: object
nunique: 74126

TOTAL DIRECT FLIGHT COSTS
0         2209.376056
1         2591.814772
2         2098.510766
3         2314.582026
4         2193.511674
             ...
110775       2907.983
110776       3480.127
110777       3806.563
110778       6196.713
110779       7131.666
Name: TOTAL DIRECT FLIGHT COSTS, Length: 110780, dtype: object
nunique: 105024

TOTAL DIRECT COSTS
0         3142.106106
1           3599.2731
2         3219.791934
3          3580.00198
4         3239.072355
             ...
110775    4218.146297
110776    4644.304821
110777    5095.160666
110778    8354.040712
110779    8367.194883
Name: TOTAL DIRECT COSTS, Length: 110780, dtype: object
nunique: 110780

CONTRIBUTION MARGIN 1
0          1384.342191
1          1516.858893
2          2770.818194
3          3441.337376
4          2193.630726
              ...
110775     4246.731703
110776     2623.261179
110777     4158.657334
110778    10076.282288
110779     1731.707117
Name: CONTRIBUTION MARGIN 1, Length: 110780, dtype: object
nunique: 110780

INDIRECT COSTS :
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
110775    NaN
110776    NaN
110777    NaN
110778    NaN
110779    NaN
Name: INDIRECT COSTS :, Length: 110780, dtype: object
nunique: 0
unique: [nan]

COCKPIT CREW PERSON
0         299.002595
1         388.627069
2          279.79735
3         331.011335
4         292.600847
             ...
110775       399.652
110776       515.661
110777       530.608
110778       896.802
110779       993.956
Name: COCKPIT CREW PERSON, Length: 110780, dtype: object
nunique: 74408

CABIN CREW PERSON
0         46.533742
1         46.533742
2         46.533742
3         46.533742
4         46.533742
            ...
110775      127.997
110776       170.51
110777      170.766
110778      435.184
110779      436.849
Name: CABIN CREW PERSON, Length: 110780, dtype: object
nunique: 10188

AIRCRAFT MAINTENANCE
0         14.305586
1         18.857364
2         13.330205
3         15.931221
4         13.980459
            ...
110775      24.4913
110776    32.869902
110777    29.647363
110778    63.806281
110779    72.184883
Name: AIRCRAFT MAINTENANCE, Length: 110780, dtype: object
nunique: 73427

TOTAL INDIRECT COSTS
0          359.841923
1          454.018174
2          339.661298
3          393.476299
4          353.115048
             ...
110775       552.1403
110776     719.040902
110777     731.021363
110778    1395.792281
110779    1502.989883
Name: TOTAL INDIRECT COSTS, Length: 110780, dtype: object
nunique: 74770

TOTAL DIRECT AND INDIRECT COSTS
0         3501.948029
1         4053.291275
2         3559.453232
3         3973.478279
4         3592.187403
             ...
110775    4770.286596
110776    5363.345723
110777    5826.182029
110778    9749.832993
110779    9870.184766
Name: TOTAL DIRECT AND INDIRECT COSTS, Length: 110780, dtype: object
nunique: 110780

CONTRIBUTION MARGIN 2
0         1024.500268
1         1062.840718
2         2431.156897
3         3047.861077
4         1840.515678
             ...
110775    3694.591404
110776    1904.220277
110777    3427.635971
110778    8680.490007
110779     228.717234
Name: CONTRIBUTION MARGIN 2, Length: 110780, dtype: object
nunique: 110780

DEPRECIATION AIRCRAFT
0         254.956363
1         336.078842
2         237.572974
3         283.928677
4           249.1619
             ...
110775    349.298927
110776    446.326407
110777    459.134034
110778    776.219838
110779    860.439691
Name: DEPRECIATION AIRCRAFT, Length: 110780, dtype: object
nunique: 60586

LEASE AIRCRAFT
0         661.655443
1         872.182175
2         616.542572
3         736.843562
4          646.61782
             ...
110775    683.495005
110776    873.354729
110777    898.416213
110778    1518.87779
110779    1683.67603
Name: LEASE AIRCRAFT, Length: 110780, dtype: object
nunique: 60681

INSURANCE
0         14.989873
1         16.942681
2         19.838619
3         23.252002
4         17.991044
            ...
110775    18.985764
110776    24.259587
110777    24.955732
110778    42.190587
110779    46.768266
Name: INSURANCE, Length: 110780, dtype: object
nunique: 107860

MAINTENANCE RESERVE
0          454.143155
1          612.105992
2          493.633864
3          552.869928
4          513.379219
             ...
110775     678.361573
110776     866.795343
110777       891.6686
110778    1507.470161
110779    1671.030674
Name: MAINTENANCE RESERVE, Length: 110780, dtype: object
nunique: 62016

TOTAL FLEET COST
0         1385.744834
1         1837.309689
2          1367.58803
3         1596.894168
4         1427.149982
             ...
110775    1730.141269
110776    2210.736066
110777    2274.174579
110778    3844.758376
110779     4261.91466
Name: TOTAL FLEET COST, Length: 110780, dtype: object
nunique: 107914

TOTAL DIRECT,INDIRECT,FLEET COSTS
0          4887.692863
1          5890.600964
2          4927.041262
3          5570.372447
4          5019.337385
              ...
110775     6500.427866
110776     7574.081789
110777     8100.356608
110778    13594.591369
110779    14132.099426
Name: TOTAL DIRECT,INDIRECT,FLEET COSTS, Length: 110780, dtype: object
nunique: 110780

CONTRIBUTION MARGIN 3
0         -361.244566
1         -774.468971
2         1063.568867
3         1450.966909
4          413.365696
             ...
110775    1964.450134
110776    -306.515789
110777    1153.461392
110778    4835.731631
110779   -4033.197426
Name: CONTRIBUTION MARGIN 3, Length: 110780, dtype: object
nunique: 110780

STATION
0         31.192382
1         35.255974
2         41.282124
3         48.385022
4          37.43751
            ...
110775       70.597
110776       93.486
110777       93.486
110778      242.756
110779      242.756
Name: STATION, Length: 110780, dtype: object
nunique: 106790

SALES ORGANIZATION
0         5.614019
1         6.345386
2         7.429975
3         8.708358
4          6.73802
            ...
110775       9.246
110776      12.243
110777      12.243
110778      31.792
110779      31.792
Name: SALES ORGANIZATION, Length: 110780, dtype: object
nunique: 106787

MARKETING
0         0.128285
1         0.144997
2         0.169781
3         0.198993
4         0.153969
            ...
110775       2.419
110776       3.203
110777       3.203
110778       8.317
110779       8.317
Name: MARKETING, Length: 110780, dtype: object
nunique: 106775

ADMINISTRATION BO
0         18.941017
1         21.408561
2         25.067833
3         29.380941
4          22.73326
            ...
110775       53.399
110776       70.712
110777       70.712
110778      183.617
110779      183.617
Name: ADMINISTRATION BO, Length: 110780, dtype: object
nunique: 106247

TOTAL OVERHEAD COST BO
0         55.875704
1         63.154919
2         73.949714
3         86.673315
4         67.062758
            ...
110775      135.661
110776      179.644
110777      179.644
110778      466.482
110779      466.482
Name: TOTAL OVERHEAD COST BO, Length: 110780, dtype: object
nunique: 107039

TOTAL BO COSTS
0          4943.568567
1          5953.755883
2          5000.990976
3          5657.045762
4          5086.400143
              ...
110775     6636.088866
110776     7753.725789
110777     8280.000608
110778    14061.073369
110779    14598.581426
Name: TOTAL BO COSTS, Length: 110780, dtype: object
nunique: 110780

ROUTE RESULT PERFORMANCE BO
0          -417.12027
1          -837.62389
2          989.619153
3         1364.293594
4          346.302938
             ...
110775    1828.789134
110776    -486.159789
110777     973.817392
110778    4369.249631
110779   -4499.679426
Name: ROUTE RESULT PERFORMANCE BO, Length: 110780, dtype: object
nunique: 110780

ADMINISTRATION HO
0          122.408937
1          138.355779
2          162.004329
3          189.878384
4          146.916824
             ...
110775     303.945021
110776     402.490394
110777     402.490394
110778    1045.146047
110779    1045.146047
Name: ADMINISTRATION HO, Length: 110780, dtype: object
nunique: 107020

TOTAL COSTS
0          5065.977504
1          6092.111662
2          5162.995304
3          5846.924146
4          5233.316968
              ...
110775     6940.033887
110776     8156.216183
110777     8682.491002
110778    15106.219416
110779    15643.727473
Name: TOTAL COSTS, Length: 110780, dtype: object
nunique: 110780

ROUTE RESULT 1
0         -539.529207
1         -975.979669
2          827.614824
3         1174.415211
4          199.386113
             ...

In [15]:
df

1,YEAR,PERIODE,AIRCRAFT TYPE,FLIGHT NUMBER_CITYPAIR,SERVICE TYPE,SUB-SERVICE,ROUNDTRIPROUTE,FLIGHT ROUTE,PASSENGER REVENUE GROSS,EXCESS BAGGAGE REVENUE,PASSENGER REVENUE DISCOUNT,PASSENGER REVENUE NETT,FREIGHT REVENUE GROSS,FREIGHT REVENUE DISCOUNT,FREIGHT REVENUE NETT,MAIL REVENUE,OTHER REVENUE,NETT REVENUES,COSTS :,DIRECT COSTS :,DIRECT TRAFFIC COSTS :,PASSENGER COMMISSION,FREIGHT COMMISSION,CREDIT CARD COMMISSION,CATERING,ON BOARD SERVICE,RESERVATION,TOTAL DIRECT TRAFFIC COSTS,DIRECT FLIGHT COSTS :,FUEL AIRCRAFT,LANDING,HANDLING,AIR TRAFFIC CONTROL,COCKPIT CREW TRAVEL,CABIN CREW TRAVEL,VARIABLE MAINTENANCE,TOTAL DIRECT FLIGHT COSTS,TOTAL DIRECT COSTS,CONTRIBUTION MARGIN 1,INDIRECT COSTS :,COCKPIT CREW PERSON,CABIN CREW PERSON,AIRCRAFT MAINTENANCE,TOTAL INDIRECT COSTS,TOTAL DIRECT AND INDIRECT COSTS,CONTRIBUTION MARGIN 2,DEPRECIATION AIRCRAFT,LEASE AIRCRAFT,INSURANCE,MAINTENANCE RESERVE,TOTAL FLEET COST,"TOTAL DIRECT,INDIRECT,FLEET COSTS",CONTRIBUTION MARGIN 3,STATION,SALES ORGANIZATION,MARKETING,ADMINISTRATION BO,TOTAL OVERHEAD COST BO,TOTAL BO COSTS,ROUTE RESULT PERFORMANCE BO,FLIGHT INTERRUPTED,ADMINISTRATION HO,TOTAL COSTS,ROUTE RESULT 1,ADJUSTMENT,ROUTE RESULT 2,FLIGHT ROUTES,NUMBER OF LANDING,BLOCK HOURS,FLIGHT HOURS,FLIGHT KILOMETERS,ATK (000),FUEL BURN (IN LITER),SEAT OFFERED,PASSENGER CARRIED,ASK (000),RPK (000),SLF (%),FREIGHT CARRIED,MAIL CARRIED,CARGO CARRIED,RTK FREIGHT (000),RTK MAIL (000),RTK CARGO (000),RTK PASSENGER (000),RTK (000),ATK CARGO (000),ATK CARGO GF (000),ATK FREIGHT GF (000),ATK MAIL GF (000),ATK PASSENGER (000),CLF (%),CLF-GF (%),LOAD FACTOR (%),BREAK EVEN LF (%),BREAK EVEN SLF-RR1 (%),NETT REVENUE/ATK (USC),NETT REVENUE/ASK (USC),PAX YIELD (USC),FREIGHT YIELD (USC),MAIL YIELD (USC),CARGO YIELD (USC),COST/ASK RR 1 (USC),COST/ASK EXCFUEL-RR1,COST PER RPK (USC),COST PER ATK (USC),COST/BLOCKHOURS,MARGIN/ASK RR 1(USC),AVERAGE FUEL PRICE,PROFIT MARGIN (%),COST COVERAGE (%),AVERAGE STAGE LENGTH,PASSENGER REVENUE GROSS F CLASS,PASSENGER REVENUE GROSS C CLASS,PASSENGER REVENUE GROSS Y CLASS,PASSENGER REVENUE DISCOUNT F CLASS,PASSENGER REVENUE DISCOUNT C CLASS,PASSENGER REVENUE DISCOUNT Y CLASS,PASSENGER REVENUE NETT F CLASS,PASSENGER REVENUE NETT C CLASS,PASSENGER REVENUE NETT Y CLASS,PASSENGER REVENUE NETT (EXCLUDE EBT) F CLASS,PASSENGER REVENUE NETT (EXCLUDE EBT) C CLASS,PASSENGER REVENUE NETT (EXCLUDE EBT) Y CLASS,SEAT OFFERED F CLASS,SEAT OFFERED C CLASS,SEAT OFFERED Y CLASS,PASSENGER CARRIED F CLASS,PASSENGER CARRIED C CLASS,PASSENGER CARRIED Y CLASS,ASK (000) F CLASS,ASK (000) C CLASS,ASK (000) Y CLASS,RPK (000) F CLASS,RPK (000) C CLASS,RPK (000) Y CLASS,OTHER REVENUE PASSENGER,OTHER REVENUE FREIGHT,QUARTER,STATUS,AIRCRAFT TYPE GROUPING,FLIGHT TYPE,AC BLENDED,CITY PAIR,GA Service,DEP,ARR,Region
0,2024,JAN,AC330,GA0118.CGK-MES.[CGK-MES],GA DOM,DOM_1 (MES),GA-CGK-MES-CGK,GA-CGK-MES,22750.433,29.714,18.508,22761.64,449.74,0,449.74,6890.85,2262.56,32364.79,NaN,NaN,NaN,945.224,24.11,77.016,665.8,8.022,581.316,2301.488,NaN,10693.711,151.459,645.635,649.356,192.181,496.531,866.632,13695.505,15996.993,16367.797,NaN,1140.251,497.083,61.986,1699.32,17696.313,14668.477,848.074087,3331.365726,141.031622,1809.725126,6130.196561,23826.509561,8538.280439,457.566,82.353,1.882,277.849,819.65,24646.159561,7718.630439,0,1795.637,26441.796561,5922.993439,-8.639,5931.632439,1,1,2.5,1.9,1391,60.545,14873,251,168,349.141,233.688,66.93,427.5,11476.5,11904,0.595,15.964,16.558,22.668,39.25,26.688,16.692,16.692,16.692,33.861,62.05,99.19722,64.83,45.25,46.72,53.46,9.27,9.73,75.63,43.17,44.33,6.67,3.61,9.96,38.46,9313.99,2.6,0.72,28.05,138.94,1391,0,4407.707,18342.726,0,0.002,18.506,0,4407.622,18354.017,0,4407.705,18324.22,0,36,215,0,12,156,0,50.076,299.065,0,16.692,216.996,2120.576,141.983,Q1,ACTUAL,A333,PAX & CARGO,All Airbus,CGK-MES,IBB,CGK,MES,DOM_WEST
1,2024,JAN,AC330,GA0121.MES-CGK.[MES-CGK],GA DOM,DOM_1 (MES),GA-CGK-MES-CGK,GA-MES-CGK,36371.179,68.352,4.674,36434.857,103.05,0,103.05,0,3425.029,39962.936,NaN,NaN,NaN,1296.263,6.56,123.21,900.39,11.651,842.195,3180.269,NaN,12238.925,124.779,686.075,649.356,179.155,496.531,881.836,15256.657,18436.926,21526.01,NaN,1049.031,496.341,63.073,1608.445,20045.371,19917.565,780.22816,3064.856468,129.749092,1664.947116,5639.780836,25685.151836,14277.784164,457.566,82.353,1.882,277.849,819.65,26504.801836,13458.134164,0,1795.637,28300.438836,11662.497164,-10.292,11672.789164,1,1,2.3,1.933,1391,60.545,14449,251,244,349.141,339.404,97.21,201,0,201,0.28,0,0.28,32.922,33.255,26.688,16.692,16.692,16.692,33.861,1.05,1.67745,54.93,35.11,62.14,66.01,11.45,10.71,36.86,*,36.86,7.64,4.14,7.86,44.09,11604.9,3.8,0.85,33.21,149.67,1391,0,10007.352,26363.828,0,0.003,4.671,0,10007.189,26427.668,0,10007.349,26359.157,0,36,215,0,23,221,0,50.076,299.065,0,31.993,307.411,3392.496,32.533,Q1,ACTUAL,A333,PAX & CARGO,All Airbus,MES-CGK,IBB,MES,CGK,DOM_WEST
2,2024,JAN,AC330,GA0182.CGK-MES.[CGK-MES],GA DOM,DOM_1 (MES),GA-CGK-MES-CGK,GA-CGK-MES,38487.162,81.734,0.042,38568.854,19255.68,0,19255.68,1184.07,9669.362,68677.966,NaN,NaN,NaN,1486.816,964.52,130.395,1211.82,14.039,1106.414,4914.004,NaN,20696.462,302.919,1291.271,1298.713,373.507,993.061,1710.458,26666.391,31580.395,37097.571,NaN,2204.485,993.547,122.34,3320.372,34900.767,33777.199,1639.496825,6440.196222,272.642331,3498.560613,11850.895992,46751.662992,21926.303008,915.133,164.706,3.763,555.698,1639.3,48390.962992,20287.003008,76.88,3591.275,52059.117992,16618.848008,-17.371,16636.219008,2,2,4.833,3.75,2782,121.089,28785,502,294,698.282,408.954,58.57,18585.5,1361,19946.5,25.852,1.893,27.746,39.669,67.481,53.376,33.384,33.384,33.384,67.722,51.98,83.11167,55.73,36.26,38.1,56.72,9.84,9.41,74.48,62.54,73.67,6.64,3.68,11.35,38.32,9599.79,3.19,0.72,32.44,147.96,1391,0,8089.802,30397.361,0,0.003,0.039,0,8089.632,30479.222,0,8089.798,30397.322,0,72,430,0,24,270,0,100.152,598.13,0,33.384,375.57,3590.32,6079.042,Q1,ACTUAL,A333,PAX & CARGO,All Airbus,CGK-MES,IBB,CGK,MES,DOM_WEST
3,2024,JAN,AC330,GA0185.MES-CGK.[MES-CGK],GA DOM,DOM_1 (MES),GA-CGK-MES-CGK,GA-MES-CGK,59939.755,279.142,0.064,60218.833,4821.9,0,4821.9,0,7113.83,72154.563,NaN,NaN,NaN,2379.531,310.64,203.077,1674.52,21.297,1594.483,6183.548,NaN,25248.658,249.559,1372.151,1298.713,384.362,993.061,1824.488,31370.992,37554.54,34600.023,NaN,2280.502,994.165,130.496,3405.163,40959.703,31194.86,1696.148175,6662.731453,282.063244,3619.450252,12260.393123,53220.096123,18934.466877,915.133,164.706,3.763,555.698,1639.3,54859.396123,17295.166877,0,3591.275,58450.671123,13703.891877,-19.986,13723.877877,2,2,5,4,2782,121.089,29808,502,446,698.282,620.386,88.84,11389,0,11389,15.842,0,15.842,60.177,76.245,53.376,33.384,33.384,33.384,67.722,29.68,47.45387,62.97,45.52,64.23,59.59,10.33,9.66,30.44,*,30.44,7.72,4.1,8.68,44.49,10775.58,2.62,0.85,25.33,133.87,1391,0,13494.024,46445.73,0,0.006,0.058,0,13493.728,46725.105,0,13494.018,46445.672,0,72,430,0,42,404,0,100.152,598.13,0,58.422,561.964,5591.55,1522.28,Q1,ACTUAL,A333,PAX & CARGO,All Airbus,MES-CGK,IBB,MES,CGK,DOM_WEST
4,2024,JAN,AC330,GA0212.CGK-YIA.[CGK-YIA],GA DOM,DOM_3 (SUB),GA-CGK-YIA-CGK,GA-CGK-YIA,10063.72,202.275,0.008,10265.988,48.36,0,48.36,0,954.074,11268.422,NaN,NaN,NaN,395.849,2.92,34.096,407.59,2.518,597.407,1440.38,NaN,5460.817,124.349,645.635,305.696,117.28,234.525,395.306,7283.608,8723.988,2544.434,NaN,615.735,153.699,28.274,797.708,9521.696,1746.726,457.960007,1798.937492,76.157076,977.251568,3310.306143,12832.002143,-1563.580143,139.474,25.103,0.574,84.693,249.844,13081.846143,-1813.424143,0,547.34,13629.186143,-2360.764143,-6.054,-2354.710143,1,1,1.35,0.867,424,18.455,7595,251,173,106.424,73.352,68.92,198,0,198,0.084,0,0.084,7.115,7.305,8.135,5.088,5.088,5.088,10.321,1.03,1.650943,39.58,44.25,77.04,61.06,10.59,13.72,57.6,*,57.6,11.68,6.54,16.94,67.33,9204.48,-1.09,0.72,-10.27,90.64,424,0,1284.862,8778.858,0,0,0.007,0,1284.841,8981.148,0,1284.862,8778.851,0,36,215,0,10,163,0,15.264,91.16,0,4.24,69.112,938.806,15.267,Q1,ACTUAL,A333,PAX & CARGO,All Airbus,CGK-YIA,IBB,CGK,YIA,DOM_WEST
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8987,2025,MAR,AC73G,GA2424.CGK-SRG.[CGK-SRG],GA DOM,DOM_3 (SUB),GA-CGK-SRG-CGK,GA-CGK-SRG,8654.943,61.087,0.207,8715.824,51.45,NaN,51.45,0,241.466,9008.74,NaN,NaN,NaN,221.743,1.86,26.164,310.5,40.256,532.862,1133.385,NaN,2460.758,28.368,283.429,311.428,110.262,92.716,761.725,4048.686,5182.071,3826.669,NaN,634.661,134.23,117.198,886.089,6068.16,2940.58,506.000442,1136.32989,23.294766,1016.025231,2681.650328,8749.810328,258.929672,67.767,10.388,4.775,55.698,138.628,8888.438328,120.301672,0,345.423,9233.861328,-225.121328,-83.428,-141.693328,1,1,1.3,0.883,422,8.039,3723,161,156,67.942,65.832,96.89,147,0,147,0.062,0,0.062,6.386,6.483,1.45,1.223967,1.224,1.224,6.589,4.28,5.065497,80.64,73.45,*,112.06,13.26,13.15,82.94,*,82.94,12.23,8.6,12.62,103.33,6389.65,1.03,0.66,7.79,107.38,422,0,1360.866,7294.078,0,0.011,0.196,0,1360.791,7355.033,0,1360.855,7293.882,0,8,153,0,8,148,0,3.376,64.566,0,3.376,62.456,224.785,16.681,Q1,ACTUAL,B738NG,PAX & CARGO,B738NG,CGK-SRG,IBB,CGK,SRG,DOM_WEST
8988,2025,MAR,AC73G,GA2454.SRG-CGK.[SRG-CGK],GA DOM,DOM_3 (SUB),GA-CGK-SRG-CGK,GA-SRG-CGK,6622.859,16.827,0.171,6639.515,24.93,NaN,24.93,0,180.09,6844.535,NaN,NaN,NaN,215.642,0.88,20.021,261.91,33.289,440.466,972.208,NaN,2353.125,43.138,337.179,311.428,109.178,92.716,632.376,3879.14,4851.348,1993.187,NaN,626.524,134.031,97.297,857.852,5709.2,1135.335,499.383513,1121.470191,22.990142,1002.738747,2646.582593,8355.782593,-1511.247593,67.767,10.388,4.775,55.698,138.628,8494.410593,-1649.875593,0,345.423,8839.833593,-1995.298593,-82.359,-1912.939593,1,1,1.283,0.733,422,8.039,3038,161,129,67.942,54.438,80.12,87,0,87,0.037,0,0.037,5.28,5.327,1.45,1.223967,1.224,1.224,6.589,2.53,3.022958,66.26,78.41,*,85.14,10.07,12.17,67.9,*,67.9,11.66,8.2,14.55,98.54,6172.72,-1.59,0.77,-15.74,85.51,422,0,243.532,6379.327,0,0.001,0.17,0,243.523,6395.993,0,243.531,6379.157,0,8,153,0,1,128,0,3.376,64.566,0,0.422,54.016,172.007,8.083,Q1,ACTUAL,B738NG,PAX & CARGO,B738NG,SRG-CGK,IBB,SRG,CGK,DOM_WEST
8989,2025,MAR,AC73G,GA0509.PNK-CGK.[PNK-CGK],GA DOM,DOM_2 (JKT),GA-CGK-PNK-CGK,GA-PNK-CGK,12370.29,-2.032,25.394,12342.864,306.29,NaN,306.29,0,419.933,13069.087,NaN,NaN,NaN,335.254,15.1,37.319,446.12,65.885,505.336,1405.014,NaN,3478.638,43.138,337.179,354.798,123.263,133.815,991.68,5462.511,6867.525,6201.562,NaN,732.301,222.702,152.579,1107.582,7975.107,5093.98,583.846663,1311.149873,26.878576,1172.336805,3094.211917,11069.318917,1999.768083,116.907,17.92,8.237,96.086,239.15,11308.468917,1760.618083,0,595.896,11904.364917,1164.722083,-96.263,1260.985083,1,1,1.5,1.15,728,13.868,4432,161,148,117.208,107.744,91.93,99,0,99,0.072,0,0.072,10.451,10.522,2.501,2.114112,2.111,2.111,11.366,2.88,3.405685,75.87,61.4,*,94.24,11.15,11.46,424.98,*,424.98,9.25,6.28,10.06,78.19,7229.44,1.9,0.78,17.02,119.46,728,0,168.567,12201.723,0,0.007,25.388,0,168.519,12174.345,0,168.56,12176.336,0,8,153,0,3,145,0,5.824,111.384,0,2.184,105.56,320.627,99.306,Q1,ACTUAL,B738NG,PAX & CARGO,B738NG,PNK-CGK,IBB,PNK,CGK,DOM_WEST
8990,2025,MAR,AC73H,GA0310.CGK-SUB.[CGK-SUB],GA DOM,DOM_3 (SUB),GA-CGK-SUB-CGK,GA-CGK-SUB,13873.2,244.161,8.139,14109.222,107.61,NaN,107.61,2.12,394.999,14613.951,NaN,NaN,NaN,449.476,3.51,41.914,317.63,70.667,570.711,1453.908,NaN,2803.136,38.068,283.429,349.698,112.429,134.176,935.828,4656.764,6110.672,8503.279,NaN,644.916,219.08,139.311,1003.307,7113.979,7499.972,518.845068,1165.175187,23.886095,1041.81664,2749.72299,9863.70199,4750.24901,117.338,17.986,8.268,96.44,240.032,10103.73399,4510.21701,0,598.093,10701.82699,3912.12401,96235.33,-92323.20599,1,1,1.333,1.05,692,13.183,4241,170,167,117.64,115.564,98.24,213.5,34.75,248.25,0.148,0.024,0.172,11.21,11.539,1.773,2.0068,2.007,2.007,11.408,9.69,8.570859,87.53,723.24,*,110.86,12.42,12,72.84,8.82,63.87,93.67,91.28,95.35,835.86,82640.91,-81.24,0.66,-653.99,104.74,692,0,2374.491,11498.709,0,7.789,0.35,0,2366.623,11742.598,0,2366.702,11498.359,0,8,162,0,6,161,0,5.536,112.104,0,4.152,111.412,360.109,34.89,Q1,ACTUAL,B738NG,PAX & CARGO,B738NG,CGK-SUB,IBB,CGK,SUB,DOM_WEST
8991,2025,MAR,AC73H,GA0315.SUB-CGK.[SUB-CGK],GA DOM,DOM_3 (SUB),GA-CGK-SUB-CGK,GA-SUB-CGK,5073.778,-0.953,83.865,4988.96,376.03,NaN,376.03,0,251.518,5616.508,NaN,NaN,NaN,185.929,17.44,15.085,186.22,30.891,252.768,688.333,NaN,2998.863,43.138,337.179,349.698,142.764,134.176,1010.1,5015.918,5704.251,-87.743,NaN,870.637,223.812,150.368,1244.817,6949.068,-1332.56,700.615996,1573.379848,32.254291,1406.804166,3713.0543,10662.1223,-5045.6143,117.338,17.986,8.268,96.44,240.032,10902.1543,-5285.6463,0,598.093,11500.2473,-5883.7393,143563.587,-149447.3263,1,1,1.8,1.133,692,13.183,3924,170,73,117.64,50.516,42.94,763,0,763,0.528,0,0.528,4.9,5.427,1.773,2.0068,2.007,2.007,11.408,29.79,26.310544,41.17,1212.03,*,42.61,4.77,9.88,71.22,*,71.22,123.91,121.36,288.57,1105.79,80984.39,-119.14,0.76,-2495.42,254.33,692,0,1056.027,4017.75,0,0.011,83.854,0,1055.951,3933.009,0,1056.016,3933.896,0,8,162,0,5,68,0,5.536,112.104,0,3.46,47.056,129.6,121.918,Q1,ACTUAL,B738NG,PAX & CARGO,B738NG,SUB-CGK,IBB,SUB,CGK,DOM_WEST