In [486]:
import pandas as pd

In [ ]:
df = pd.read_excel("05. Database RP May 2025 - AC REGISTER.xlsx", sheet_name="Raw", skiprows=1)

In [488]:
df_pkgna_jan = df[
    (df['AC REG'].str.contains('PKGNA', case=False, na=False)) &
    (df['PERIODE'].str.upper() == 'MAR')
]

# Tampilkan DataFrame hasil filter
print(df_pkgna_jan)

       Unnamed: 0  YEAR PERIODE AIRCRAFT TYPE    FLIGHT NUMBER_CITYPAIR  \
11823         NaN  2024     MAR         AC738  GA0073.TKG-CGK.[TKG-CGK]
11918         NaN  2024     MAR         AC738  GA0108.CGK-PLM.[CGK-PLM]
11930         NaN  2024     MAR         AC738  GA0108.CGK-PLM.[CGK-PLM]
11949         NaN  2024     MAR         AC738  GA0113.PLM-CGK.[PLM-CGK]
11961         NaN  2024     MAR         AC738  GA0113.PLM-CGK.[PLM-CGK]
...           ...   ...     ...           ...                       ...
17067         NaN  2024     MAR         AC738  GA0512.CGK-PNK.[CGK-PNK]
17093         NaN  2024     MAR         AC738  GA0513.PNK-CGK.[PNK-CGK]
17292         NaN  2024     MAR         AC738  GA0635.DJJ-TIM.[DJJ-TIM]
17371         NaN  2024     MAR         AC738  GA0634.TIM-DJJ.[TIM-DJJ]
17588         NaN  2024     MAR         AC738  GA0196.CGK-MES.[CGK-MES]

      SERVICE TYPE  SUB-SERVICE ROUNDTRIPROUTE FLIGHT ROUTE AC REG  ...  \
11823          DOM  DOM_2 (JKT)    CGK-TKG-CGK      TKG-CGK  PKGNA  ...
11918          DOM  DOM_2 (JKT)    CGK-PLM-CGK      CGK-PLM  PKGNA  ...
11930          DOM  DOM_2 (JKT)    CGK-PLM-CGK      CGK-PLM  PKGNA  ...
11949          DOM  DOM_2 (JKT)    CGK-PLM-CGK      PLM-CGK  PKGNA  ...
11961          DOM  DOM_2 (JKT)    CGK-PLM-CGK      PLM-CGK  PKGNA  ...
...            ...          ...            ...          ...    ...  ...
17067          DOM  DOM_2 (JKT)    CGK-PNK-CGK      CGK-PNK  PKGNA  ...
17093          DOM  DOM_2 (JKT)    CGK-PNK-CGK      PNK-CGK  PKGNA  ...
17292          DOM  DOM_4 (UPG)    TIM-DJJ-TIM      DJJ-TIM  PKGNA  ...
17371          DOM  DOM_4 (UPG)    TIM-DJJ-TIM      TIM-DJJ  PKGNA  ...
17588          DOM  DOM_1 (MES)    CGK-MES-CGK      CGK-MES  PKGNA  ...

       RPK (000) C CLASS  RPK (000) Y CLASS  OTHER REVENUE PASSENGER  \
11823              1.528             24.448               230.493952
11918              4.170             62.967               545.101595
11930              0.417             62.133               397.767149
11949              4.587             61.299               533.494875
11961              0.417             62.133               417.811825
...                  ...                ...                      ...
17067              6.552            109.200               646.773378
17093              0.728             76.440               382.945027
17292              1.371             39.759               195.522887
17371              1.371             50.727               248.365048
17588             15.301            212.823              1003.743816

       OTHER REVENUE FREIGHT  QUARTER  STATUS  AIRCRAFT TYPE GROUPING  \
11823             227.591150       Q1  ACTUAL                  B738NG
11918              93.988361       Q1  ACTUAL                  B738NG
11930             110.483663       Q1  ACTUAL                  B738NG
11949              56.432661       Q1  ACTUAL                  B738NG
11961              12.499001       Q1  ACTUAL                  B738NG
...                      ...      ...     ...                     ...
17067             252.460705       Q1  ACTUAL                  B738NG
17093               0.000000       Q1  ACTUAL                  B738NG
17292             707.107213       Q1  ACTUAL                  B738NG
17371             229.976443       Q1  ACTUAL                  B738NG
17588            1000.257546       Q1  ACTUAL                  B738NG

       FLIGHT TYPE  GA Service    Region
11823  PAX & CARGO         IBB  DOM_WEST
11918  PAX & CARGO         IBB  DOM_WEST
11930  PAX & CARGO         IBB  DOM_WEST
11949  PAX & CARGO         IBB  DOM_WEST
11961  PAX & CARGO         IBB  DOM_WEST
...            ...         ...       ...
17067  PAX & CARGO         IBB  DOM_WEST
17093  PAX & CARGO         IBB  DOM_WEST
17292  PAX & CARGO         IBT  DOM_EAST
17371  PAX & CARGO         IBT  DOM_EAST
17588  PAX & CARGO         IBB  DOM_WEST

[92 rows x 146 columns]

In [489]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110780 entries, 0 to 110779
Columns: 146 entries, Unnamed: 0 to Region
dtypes: float64(120), int64(12), object(14)
memory usage: 123.4+ MB

In [490]:
df.head()

,Unnamed: 0,YEAR,PERIODE,AIRCRAFT TYPE,FLIGHT NUMBER_CITYPAIR,SERVICE TYPE,SUB-SERVICE,ROUNDTRIPROUTE,FLIGHT ROUTE,AC REG,...,RPK (000) C CLASS,RPK (000) Y CLASS,OTHER REVENUE PASSENGER,OTHER REVENUE FREIGHT,QUARTER,STATUS,AIRCRAFT TYPE GROUPING,FLIGHT TYPE,GA Service,Region
0,NaN,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGNR,...,0.573,28.268,382.164660,1.366988,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
1,NaN,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGFJ,...,0.955,27.886,427.183511,15.077904,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
2,NaN,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGNA,...,0.191,28.841,489.566409,47.838249,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
3,NaN,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGNR,...,2.483,27.886,593.068566,1.376459,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
4,NaN,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGMW,...,0.573,28.077,448.429472,30.733542,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST

In [491]:
df = df.iloc[:, 1:]
df.head()

,YEAR,PERIODE,AIRCRAFT TYPE,FLIGHT NUMBER_CITYPAIR,SERVICE TYPE,SUB-SERVICE,ROUNDTRIPROUTE,FLIGHT ROUTE,AC REG,DATE,...,RPK (000) C CLASS,RPK (000) Y CLASS,OTHER REVENUE PASSENGER,OTHER REVENUE FREIGHT,QUARTER,STATUS,AIRCRAFT TYPE GROUPING,FLIGHT TYPE,GA Service,Region
0,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGNR,30012024,...,0.573,28.268,382.164660,1.366988,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
1,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGFJ,31012024,...,0.955,27.886,427.183511,15.077904,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
2,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGNA,1012024,...,0.191,28.841,489.566409,47.838249,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
3,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGNR,2012024,...,2.483,27.886,593.068566,1.376459,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST
4,2024,JAN,AC738,GA0072.CGK-TKG.[CGK-TKG],DOM,DOM_2 (JKT),CGK-TKG-CGK,CGK-TKG,PKGMW,19012024,...,0.573,28.077,448.429472,30.733542,Q1,ACTUAL,B738NG,PAX & CARGO,IBB,DOM_WEST

## Finding Correlation

In [492]:
df_num = df.select_dtypes(include=["number"])
corr = df_num.corrwith(df_num['VARIABLE MAINTENANCE']).sort_values(ascending=False).dropna()
corr.head(30)

c:\Users\hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\lib\_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
c:\Users\hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\lib\_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

VARIABLE MAINTENANCE                 1.000000
TOTAL DIRECT AND INDIRECT COSTS      0.878740
TOTAL DIRECT FLIGHT COSTS            0.877793
TOTAL DIRECT COSTS                   0.876809
TOTAL DIRECT,INDIRECT,FLEET COSTS    0.872288
TOTAL BO COSTS                       0.871805
COCKPIT CREW PERSON                  0.866245
TOTAL COSTS                          0.866227
TOTAL INDIRECT COSTS                 0.862611
BLOCK HOURS                          0.857835
FLIGHT HOURS                         0.857820
FLIGHT KILOMETERS                    0.855536
FUEL BURN (IN LITER)                 0.843387
ASK (000)                            0.839174
ATK PASSENGER (000)                  0.838884
ATK (000)                            0.837825
LEASE AIRCRAFT                       0.835859
CABIN CREW TRAVEL                    0.834723
FUEL AIRCRAFT                        0.834281
ASK (000) Y CLASS                    0.834267
TOTAL FLEET COST                     0.827219
COCKPIT CREW TRAVEL                  0.822847
ASK (000) C CLASS                    0.821218
CABIN CREW PERSON                    0.819680
RTK (000)                            0.793510
MAINTENANCE RESERVE                  0.792491
RTK PASSENGER (000)                  0.779712
RPK (000)                            0.779668
RPK (000) Y CLASS                    0.770974
RPK (000) C CLASS                    0.745488
dtype: float64

## Remove zero

In [493]:
df = df[df['VARIABLE MAINTENANCE'] >= 0].copy()

In [ ]:
df = df[df['VARIABLE MAINTENANCE'] >= 0].copy()

df1 = df[
    (df['FUEL BURN (IN LITER)'] != 0) &
    (df['FLIGHT HOURS'] != 0) &
    (df['VARIABLE MAINTENANCE'] != 0)
].copy()

## Finding Corelation

In [495]:
df_num = df.select_dtypes(include=["number"])

# Misal ingin korelasi semua numerik dengan VARIABLE MAINTENANCE
corr = df_num.corrwith(df_num['VARIABLE MAINTENANCE']).sort_values(ascending=False).dropna()

print(corr.head(30))

c:\Users\hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\lib\_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
c:\Users\hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\lib\_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

VARIABLE MAINTENANCE                 1.000000
TOTAL DIRECT AND INDIRECT COSTS      0.880812
TOTAL DIRECT FLIGHT COSTS            0.879632
TOTAL DIRECT COSTS                   0.878737
TOTAL DIRECT,INDIRECT,FLEET COSTS    0.874383
TOTAL BO COSTS                       0.873925
COCKPIT CREW PERSON                  0.870631
TOTAL COSTS                          0.868396
TOTAL INDIRECT COSTS                 0.866289
BLOCK HOURS                          0.860999
FLIGHT HOURS                         0.860947
FLIGHT KILOMETERS                    0.858636
FUEL BURN (IN LITER)                 0.845938
ASK (000)                            0.842179
ATK PASSENGER (000)                  0.841893
ATK (000)                            0.840493
LEASE AIRCRAFT                       0.838349
CABIN CREW TRAVEL                    0.837325
ASK (000) Y CLASS                    0.837290
FUEL AIRCRAFT                        0.836549
TOTAL FLEET COST                     0.829340
COCKPIT CREW TRAVEL                  0.824952
ASK (000) C CLASS                    0.823836
CABIN CREW PERSON                    0.822782
RTK (000)                            0.796238
MAINTENANCE RESERVE                  0.794073
RTK PASSENGER (000)                  0.782220
RPK (000)                            0.782170
RPK (000) Y CLASS                    0.773417
RPK (000) C CLASS                    0.748139
dtype: float64

## Group VM per PK Register per Periode

In [496]:
df_group = df1.groupby(["AC REG", "PERIODE"]).agg({
    "VARIABLE MAINTENANCE": "sum",
    "BLOCK HOURS": "sum",
    "FLIGHT HOURS": "sum",
    "FUEL BURN (IN LITER)": "sum",
    "FUEL AIRCRAFT": "sum",
    "ASK (000)": "sum",
    "ATK PASSENGER (000)": "sum",
    "ATK (000)": "sum",
    "LEASE AIRCRAFT": "mean",
    "CABIN CREW TRAVEL": "sum",
    "COCKPIT CREW TRAVEL": "sum",
    "CABIN CREW PERSON": "mean",
    "ROUNDTRIPROUTE": "nunique", 
    "FLIGHT ROUTE": "nunique", 
    "SERVICE TYPE": "first", 
    "AIRCRAFT TYPE": "first",
}).reset_index()

In [497]:
# Filter periode Januari
df_group_jan = df_group[df_group['PERIODE'].str.upper() == 'JAN']

# Tampilkan hasil
print(df_group_jan)

    AC REG PERIODE  VARIABLE MAINTENANCE  BLOCK HOURS  FLIGHT HOURS  \
4    PKGFD     JAN         339734.112424   584.050000    471.700000
16   PKGFF     JAN         351543.104266   577.750000    462.050000
28   PKGFG     JAN         319503.589430   549.200000    434.633333
40   PKGFH     JAN         311847.040406   536.766667    425.533333
52   PKGFI     JAN         319308.135224   551.650000    447.766667
..     ...     ...                   ...          ...           ...
698  PKGUC     JAN         249477.595752   439.900000    335.183333
710  PKGUD     JAN         243808.206954   403.966667    297.800000
722  PKGUE     JAN         195779.113046   342.500000    248.516667
733  PKGUF     JAN         157486.333515   220.716667    177.733333
738  PKGUG     JAN          74151.878750   107.050000     83.050000

     FUEL BURN (IN LITER)  FUEL AIRCRAFT  ASK (000)  ATK PASSENGER (000)  \
4               1701005.0   1.264095e+06  52444.746          5110.265646
16              1688271.0   1.249925e+06  49897.782          4853.660529
28              1606205.0   1.193345e+06  47611.476          4630.577180
40              1556236.0   1.154170e+06  46821.078          4559.184788
52              1625580.0   1.223322e+06  48952.026          4762.821964
..                    ...            ...        ...                  ...
698             1246412.0   9.228082e+05  34567.884          3352.394199
710             1099590.0   8.146542e+05  28413.763          2755.567765
722              938008.0   6.977490e+05  24362.198          2362.649235
733              670560.0   4.695675e+05  19068.696          1849.229574
738              325500.0   2.307852e+05   8523.792           826.613772

       ATK (000)  LEASE AIRCRAFT  CABIN CREW TRAVEL  COCKPIT CREW TRAVEL  \
4    6167.114791     1884.524038       72843.409367         50363.669837
16   5867.609518     1825.544212       70239.694704         50380.157664
28   5598.758708     1789.797940       67804.827280         48117.343158
40   5505.812350     1810.361362       66085.294322         46652.188683
52   5756.395650     1827.019876       68233.408352         47628.086280
..           ...             ...                ...                  ...
698  4064.927513     1487.018934       52668.830397         39907.831567
710  3362.004957     1276.797040       47614.029770         38446.883161
722  2882.613043     1172.944174       41642.354597         32875.785941
733  2242.337731     1603.517372       27766.637362         21505.692241
738  1002.335748     1529.944867       12185.543855         10045.705962

     CABIN CREW PERSON  ROUNDTRIPROUTE  FLIGHT ROUTE SERVICE TYPE  \
4           257.509066              48            95          DOM
16          236.458654              40            80          DOM
28          235.147469              38            76          DOM
40          239.533506              36            71          DOM
52          247.410291              48            94          DOM
..                 ...             ...           ...          ...
698         177.162558              28            56          DOM
710         140.327292              19            38          DOM
722         131.075132              15            30          DOM
733         198.553078              29            57          DOM
738         175.224974              17            34          DOM

    AIRCRAFT TYPE
4           AC738
16          AC738
28          AC738
40          AC738
52          AC738
..            ...
698         AC738
710         AC73G
722         AC73G
733         AC738
738         AC738

[67 rows x 18 columns]

In [498]:
print(df_group)

    AC REG PERIODE  VARIABLE MAINTENANCE  BLOCK HOURS  FLIGHT HOURS  \
0    PKGFD     APR         319683.287665   528.583333    416.650000
1    PKGFD     AUG         179373.919771   267.033333    206.933333
2    PKGFD     DEC         355938.621376   328.483333    262.666667
3    PKGFD     FEB         327272.723442   529.616667    428.166667
4    PKGFD     JAN         339734.112424   584.050000    471.700000
..     ...     ...                   ...          ...           ...
741  PKGUH     APR          14282.535105    26.116667     19.600000
742  PKGUH     MAY         164092.758744   247.783333    190.716667
743  PKGUI     APR         138563.708895   238.050000    187.316667
744  PKGUI     MAR           1945.928000     3.133333      2.183333
745  PKGUI     MAY         149833.201256   222.333333    174.366667

     FUEL BURN (IN LITER)  FUEL AIRCRAFT    ASK (000)  ATK PASSENGER (000)  \
0               1535918.0   1.116134e+06  44029.65600          4278.504961
1                779459.0   6.041519e+05  21725.01000          2114.927406
2                980308.0   6.735596e+05  28531.32925          2780.236960
3               1575187.0   1.222503e+06  46663.29000          4532.427065
4               1701005.0   1.264095e+06  52444.74600          5110.265646
..                    ...            ...          ...                  ...
741               73163.0   4.782787e+04   2025.38000           196.437167
742              720896.0   4.697909e+05  20612.50000          1999.075222
743              690070.0   4.568967e+05  20717.56000          2009.346833
744                8165.0   5.801999e+03    235.28000            22.816000
745              647733.0   4.214048e+05  19032.86000          1845.866778

       ATK (000)  LEASE AIRCRAFT  CABIN CREW TRAVEL  COCKPIT CREW TRAVEL  \
0    5177.562485     1539.472222       52227.525900         37056.645237
1    2554.700505     1461.778827       32891.510051         22838.751359
2    3355.073346     1597.430417       38054.478060         26023.570303
3    5487.256520     1797.052758       64812.618212         47801.625360
4    6167.114791     1884.524038       72843.409367         50363.669837
..           ...             ...                ...                  ...
741   226.961833     1275.574267        2350.036396          1733.275027
742  2309.808411     1325.170565       33388.856284         23760.113714
743  2321.582167     1453.315860       22754.261604         15113.045973
744    26.366000     1369.277517         268.350000           255.191000
745  2132.799589     1407.071970       30405.275716         21155.053286

     CABIN CREW PERSON  ROUNDTRIPROUTE  FLIGHT ROUTE SERVICE TYPE  \
0           213.986858              35            70          DOM
1           195.325090              25            50          DOM
2           180.158282              39            78          DOM
3           281.398636              39            76          DOM
4           257.509066              48            95          DOM
..                 ...             ...           ...          ...
741         195.422250               6            12          DOM
742         338.984837              19            38          DOM
743         247.630617              24            48          DOM
744         221.447000               1             2          DOM
745         369.997892              18            36          DOM

    AIRCRAFT TYPE
0           AC738
1           AC738
2           AC738
3           AC738
4           AC738
..            ...
741         AC73H
742         AC73H
743         AC73H
744         AC73H
745         AC73H

[746 rows x 18 columns]

In [499]:
import numpy as np

df_group['FH_per_BH'] = df_group['FLIGHT HOURS'] / df_group['BLOCK HOURS'].replace(0, np.nan)
df_group['Fuel_per_FH'] = df_group['FUEL BURN (IN LITER)'] / df_group['FLIGHT HOURS'].replace(0, np.nan)
df_group['ATK_per_ASK'] = df_group['ATK (000)'] / df_group['ASK (000)'].replace(0, np.nan)

df_group = df_group.fillna(0)

## Input Selected Features

In [500]:
selected_features = [
    'BLOCK HOURS',
    'FLIGHT HOURS',
    'FUEL BURN (IN LITER)',
    'ASK (000)',
    'ATK PASSENGER (000)',
    'ATK (000)',
    'LEASE AIRCRAFT',
    'CABIN CREW TRAVEL',
    'FUEL AIRCRAFT',
    'COCKPIT CREW TRAVEL',
    'CABIN CREW PERSON',
    'ROUNDTRIPROUTE', 
    'AIRCRAFT TYPE',
    'SERVICE TYPE', 
    'AC REG',
    'FLIGHT ROUTE',
    'PERIODE',
]

In [501]:
selected_features += ["FH_per_BH", "Fuel_per_FH", "ATK_per_ASK"]

## SPlit Data

In [502]:
X = df_group[selected_features].copy()
y = df_group['VARIABLE MAINTENANCE'].copy()

In [503]:
print (X)

     BLOCK HOURS  FLIGHT HOURS  FUEL BURN (IN LITER)    ASK (000)  \
0     528.583333    416.650000             1535918.0  44029.65600
1     267.033333    206.933333              779459.0  21725.01000
2     328.483333    262.666667              980308.0  28531.32925
3     529.616667    428.166667             1575187.0  46663.29000
4     584.050000    471.700000             1701005.0  52444.74600
..           ...           ...                   ...          ...
741    26.116667     19.600000               73163.0   2025.38000
742   247.783333    190.716667              720896.0  20612.50000
743   238.050000    187.316667              690070.0  20717.56000
744     3.133333      2.183333                8165.0    235.28000
745   222.333333    174.366667              647733.0  19032.86000

     ATK PASSENGER (000)    ATK (000)  LEASE AIRCRAFT  CABIN CREW TRAVEL  \
0            4278.504961  5177.562485     1539.472222       52227.525900
1            2114.927406  2554.700505     1461.778827       32891.510051
2            2780.236960  3355.073346     1597.430417       38054.478060
3            4532.427065  5487.256520     1797.052758       64812.618212
4            5110.265646  6167.114791     1884.524038       72843.409367
..                   ...          ...             ...                ...
741           196.437167   226.961833     1275.574267        2350.036396
742          1999.075222  2309.808411     1325.170565       33388.856284
743          2009.346833  2321.582167     1453.315860       22754.261604
744            22.816000    26.366000     1369.277517         268.350000
745          1845.866778  2132.799589     1407.071970       30405.275716

     FUEL AIRCRAFT  COCKPIT CREW TRAVEL  CABIN CREW PERSON  ROUNDTRIPROUTE  \
0     1.116134e+06         37056.645237         213.986858              35
1     6.041519e+05         22838.751359         195.325090              25
2     6.735596e+05         26023.570303         180.158282              39
3     1.222503e+06         47801.625360         281.398636              39
4     1.264095e+06         50363.669837         257.509066              48
..             ...                  ...                ...             ...
741   4.782787e+04          1733.275027         195.422250               6
742   4.697909e+05         23760.113714         338.984837              19
743   4.568967e+05         15113.045973         247.630617              24
744   5.801999e+03           255.191000         221.447000               1
745   4.214048e+05         21155.053286         369.997892              18

    AIRCRAFT TYPE SERVICE TYPE AC REG  FLIGHT ROUTE PERIODE  FH_per_BH  \
0           AC738          DOM  PKGFD            70     APR   0.788239
1           AC738          DOM  PKGFD            50     AUG   0.774934
2           AC738          DOM  PKGFD            78     DEC   0.799635
3           AC738          DOM  PKGFD            76     FEB   0.808446
4           AC738          DOM  PKGFD            95     JAN   0.807636
..            ...          ...    ...           ...     ...        ...
741         AC73H          DOM  PKGUH            12     APR   0.750479
742         AC73H          DOM  PKGUH            38     MAY   0.769691
743         AC73H          DOM  PKGUI            48     APR   0.786880
744         AC73H          DOM  PKGUI             2     MAR   0.696809
745         AC73H          DOM  PKGUI            36     MAY   0.784258

     Fuel_per_FH  ATK_per_ASK
0    3686.350654     0.117593
1    3766.715528     0.117593
2    3732.137056     0.117593
3    3678.910860     0.117593
4    3606.116176     0.117593
..           ...          ...
741  3732.806122     0.112059
742  3779.931836     0.112059
743  3683.975443     0.112059
744  3739.694656     0.112062
745  3714.775378     0.112059

[746 rows x 20 columns]

In [504]:
# from sklearn.model_selection import train_test_split


# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [505]:
from sklearn.model_selection import GroupShuffleSplit

splitter = GroupShuffleSplit(test_size=0.2, random_state=42)
train_idx, test_idx = next(splitter.split(df_group, groups=df_group["AC REG"]))

X_train = X.iloc[train_idx]
X_test = X.iloc[test_idx]
y_train = y.iloc[train_idx]
y_test = y.iloc[test_idx]

In [506]:
categorical_cols = ['AC REG','PERIODE','ROUNDTRIPROUTE','AIRCRAFT TYPE','SERVICE TYPE','FLIGHT ROUTE']
numeric_cols = list(set(selected_features) - set(categorical_cols))

In [507]:
print(numeric_cols)

['BLOCK HOURS', 'CABIN CREW TRAVEL', 'ASK (000)', 'CABIN CREW PERSON', 'Fuel_per_FH', 'ATK_per_ASK', 'ATK (000)', 'COCKPIT CREW TRAVEL', 'FLIGHT HOURS', 'LEASE AIRCRAFT', 'FH_per_BH', 'ATK PASSENGER (000)', 'FUEL BURN (IN LITER)', 'FUEL AIRCRAFT']

## Encoder

In [508]:
from sklearn.preprocessing import OneHotEncoder


encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
encoder.fit(X_train[categorical_cols])

OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [509]:
X_train_encoded = encoder.transform(X_train[categorical_cols])
X_test_encoded = encoder.transform(X_test[categorical_cols])

In [ ]:
X_train_encoded = encoder.transform(X_train[categorical_cols])
X_test_encoded = encoder.transform(X_test[categorical_cols])
encoded_cols = encoder.get_feature_names_out(categorical_cols)

X_train_encoded = pd.DataFrame(X_train_encoded, columns=encoded_cols, index=X_train.index)
X_test_encoded = pd.DataFrame(X_test_encoded, columns=encoded_cols, index=X_test.index)

In [ ]:
X_train_encoded = encoder.transform(X_train[categorical_cols])
X_test_encoded = encoder.transform(X_test[categorical_cols])
encoded_cols = encoder.get_feature_names_out(categorical_cols)

X_train_encoded = pd.DataFrame(X_train_encoded, columns=encoded_cols, index=X_train.index)
X_test_encoded = pd.DataFrame(X_test_encoded, columns=encoded_cols, index=X_test.index)
X_train_final = pd.concat([X_train[numeric_cols], X_train_encoded], axis=1)
X_test_final = pd.concat([X_test[numeric_cols], X_test_encoded], axis=1)

In [512]:
X_test_final

,BLOCK HOURS,CABIN CREW TRAVEL,ASK (000),CABIN CREW PERSON,Fuel_per_FH,ATK_per_ASK,ATK (000),COCKPIT CREW TRAVEL,FLIGHT HOURS,LEASE AIRCRAFT,...,FLIGHT ROUTE_86,FLIGHT ROUTE_87,FLIGHT ROUTE_88,FLIGHT ROUTE_89,FLIGHT ROUTE_90,FLIGHT ROUTE_91,FLIGHT ROUTE_92,FLIGHT ROUTE_95,FLIGHT ROUTE_96,FLIGHT ROUTE_97
0,528.583333,52227.525900,44029.65600,213.986858,3686.350654,0.117593,5177.562485,37056.645237,416.650000,1539.472222,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,267.033333,32891.510051,21725.01000,195.325090,3766.715528,0.117593,2554.700505,22838.751359,206.933333,1461.778827,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,328.483333,38054.478060,28531.32925,180.158282,3732.137056,0.117593,3355.073346,26023.570303,262.666667,1597.430417,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,529.616667,64812.618212,46663.29000,281.398636,3678.910860,0.117593,5487.256520,47801.625360,428.166667,1797.052758,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,584.050000,72843.409367,52444.74600,257.509066,3606.116176,0.117593,6167.114791,50363.669837,471.700000,1884.524038,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
736,295.266667,27865.595282,25317.03600,250.570170,3756.262425,0.117593,2977.095711,18694.619364,234.733333,1498.272666,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
737,258.150000,33391.297629,22718.07000,288.636734,3804.310841,0.117593,2671.476669,22433.934713,208.466667,1718.553430,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
738,107.050000,12185.543855,8523.79200,175.224974,3919.325707,0.117593,1002.335748,10045.705962,83.050000,1529.944867,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
739,206.966667,17955.651288,16982.62200,265.145881,3733.986507,0.117593,1997.030517,16226.578235,165.516667,1533.134013,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
740,303.800000,40283.970128,25068.36600,361.458805,3802.738974,0.117593,2947.854268,28589.719876,236.950000,1433.027818,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## PREDIKSI

In [513]:
from xgboost import XGBRegressor

bst = XGBRegressor(
    n_estimators=500, 
    max_depth=10, 
    learning_rate=0.05, 
    gamma=0.1, 
    objective="reg:squarederror"
)


bst.fit(X_train_final, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=0.1, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=10,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=None, num_parallel_tree=None, ...)

In [514]:
y_pred = bst.predict(X_test_final)

In [ ]:
from sklearn.metrics import mean_absolute_percentage_error

y_pred = bst.predict(X_test_final)
mean_absolute_percentage_error(y_test, y_pred)

0.07421163190030687